### ISSUE TITLE
ME Bridge losing physical connection

### ISSUE THREAD

**Issue by RedStoner** [Seniorendi/AdvancedPeripherals#100]
ME bridge seems to lose its physical connection on load of singleplayer game (not tested in MP). I have been getting nil on me.getItem. I removed the controller that was not connected properly after reload and replaced it. The ME calls seemed to start working immediatly. So to test if the save/reload was reasoning for disconnect, I saved and closed. 
Upon attempting to reload the world, It got stuck loading chunks at 94% and sat there for a good while. I closed/force crashed the game and reloaded. When I loaded into the world this time, the ME Bridge was disconnected again. 
![2021-06-10_17 16 16](https://user-images.githubusercontent.com/1278466/121599095-99968c80-ca10-11eb-8443-4132e193cbe1.png)

Leaving original issue info as some of it is still relevant. 

**Describe**

me.getItem() returning nil on every item in ME system
I have to restart my game upwards of 4-5 times before it actually returns proper values. 
I am playing single player if that makes any difference.

1. load game
2.call me.getItem({name=v.name})
3.

...

**Screenshots/Videos**
printing Item name, and what is returned by me.getItem()
![2021-06-10_16 48 09](https://user-images.githubusercontent.com/1278466/121595049-e3c93f00-ca0b-11eb-8af2-a57e40252e47.png)
Pictures of ME system showing Items in there - 
![2021-06-10_16 48 32](https://user-images.githubusercontent.com/1278466/121595099-ee83d400-ca0b-11eb-9c63-1b58d1a4fd9b.png)
![2021-06-10_16 48 41](https://user-images.githubusercontent.com/1278466/121595104-f04d9780-ca0b-11eb-834c-7ced1ead16ee.png)
![2021-06-10_16 48 54](https://user-images.githubusercontent.com/1278466/121595114-f2175b00-ca0b-11eb-9a80-c6dd8c09950f.png)

**Versions:**

- Forge version: 36.1.0
- AdvancedPeripherals version: 0.6r - tried several of the alpha versions too.

**Crashlog/log (Use https://paste.gg or https://pastebin.com to upload your crashlog/log)**

**Comment by Seniorendi** [comment]
Could you show me your code?

**Comment by RedStoner** [comment]
Its pretty big and in 3 files.

**Comment by RedStoner** [comment]
the debugText call is the print you see in the screenshot

**Comment by RedStoner** [comment]
https://pastebin.com/wKNza0YP

**Comment by RedStoner** [comment]
I really dont believe it to by my code in any way. As this code works sometimes. Its just when the ME bridge wants to return an actual value for the items instead of nil.

**Comment by RedStoner** [comment]
WOW. I found the problem!!!!! - 
![2021-06-10_17 16 16](https://user-images.githubusercontent.com/1278466/121598290-ae265500-ca0f-11eb-8cb6-fcfc50014fae.png)
Seems on reloading the world, the ME cable does NOT connect to the ME Bridge!!!! WTF I had just gone down there to check it, noticed it wasnt connected. Removed/Replaced... System started working fine.  Saved and Closed the world, reloaded world. Game froze at 94% loading and crashed out. reboot and reload world. ME Bridge not connected anymore.

**Comment by RedStoner** [comment]
Going to update this issue with proper information on what I have found.

**Comment by Seniorendi** [comment]
Do you use Performant?

**Comment by RedStoner** [comment]
Performant? Not even sure what that is so I would guess no.

**Comment by Seniorendi** [comment]
Could you send me a full mod list?

**Comment by RedStoner** [comment]
SaveMyStronghold-1.16.4-1.0.jar                   |Save My Stronghold!           |savemystronghold              |1.16.4-1.0          
		inventorysorter-1.16.1-18.1.0.jar                 |Simple Inventory Sorter       |inventorysorter               |18.1.0              
		supermartijn642configlib-1.0.6-mc1.16.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.6               
		advancedperipherals-0.6r.jar                      |Advanced Peripherals          |advancedperipherals           |0.6r                
		spiders-2.0-1.16.4-1.0.4.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.4               
		treeharvester_1.16.5-2.4.jar                      |Tree Harvester                |treeharvester                 |2.4                 
		jei-1.16.5-7.7.0.100.jar                          |Just Enough Items             |jei                           |7.7.0.100           
		metalbarrels-3.3a.jar                             |Metal Barrels                 |metalbarrels                  |3.3a                
		Pehkui-2.2.0+1.16.5-forge.jar                     |Pehkui                        |pehkui                        |2.2.0+1.16.5-forge  
		Neat+1.7-27.jar                                   |Neat                          |neat                          |1.7-27              
		create-mc1.16.5_v0.3.1c.jar                       |Create                        |create                        |mc1.16.5_v0.3.1c+151
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        
		Waystones_1.16.5-7.5.1.jar                        |Waystones                     |waystones                     |7.5.1               
		TerraForged-1.16.5-0.2.10.jar                     |TerraForged                   |terraforged                   |0.2.10              
		journeymap-1.16.5-5.7.1.jar                       |Journeymap                    |journeymap                    |5.7.1               
		appliedenergistics2-8.3.1.jar                     |Applied Energistics 2         |appliedenergistics2           |8.3.1   
		NoFog-1.16.2-Forge-b1.jar                         |NoFog                         |nofog                         |1.0.1               
		NaturesCompass-1.16.5-1.8.6.jar                   |Nature's Compass              |naturescompass                |1.16.5-1.8.6        
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      
		Powah-1.16.5-2.3.16.jar                           |Powah                         |powah                         |2.3.16              
		stoneholm-1.2.1.jar                               |Stoneholm                     |stoneholm                     |1.2                 
		buildinggadgets-1.16.5-3.8.0.jar                  |Building Gadgets              |buildinggadgets               |3.8.0               
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  
		immersive-portals-0.16-mc1.16.5-forge.jar         |Immersive Portals             |immersive_portals             |0.14                
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0   
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2   
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      
		CraftingTweaks_1.16.3-12.2.0.jar                  |Crafting Tweaks               |craftingtweaks                |12.2.0              
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              
		torchmaster-2.3.7.jar                             |Torchmaster                   |torchmaster                   |2.3.7               
		repurposed_structures-1.16.5-2.6.6-forge.jar      |Repurposed Structures         |repurposed_structures         |1.16.5-2.6.6-forge  
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                
		Lollipop-1.16.5-3.2.9.jar                         |Lollipop                      |lollipop                      |3.2.9               
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      
		travel_bag-1.16.5-1.2.6.jar                       |Travel Bag                    |travel_bag                    |1.2.6               
		collective-1.16.5-2.26.jar                        |Collective                    |collective                    |2.26                
		StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               
		angelring-1.16.5-1.3.4.1.jar                      |Angel Ring                    |angelring                     |1.3.4.1             
		BetterStrongholds-1.16.4-1.1.jar                  |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.1          
		structurize-0.13.175-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.175-ALPHA      
		vinecollector-1.2.jar                             |VineCollector                 |vinecollector                 |1.2                 
		minecolonies-0.14.201-BETA-universal.jar          |MineColonies                  |minecolonies                  |0.14.201-BETA       
		mcw-roofs-2.0.1-mc1.16.5-4.jar                    |Macaw's Roofs                 |mcwroofs                      |2.0.1               
		architectury-1.17.17-forge.jar                    |Architectury                  |architectury                  |1.17.17             
		cc-tweaked-1.16.4-1.96.0.jar                      |CC: Tweaked                   |computercraft                 |1.96.0              
		Colony4ComputerCraft-1.16.4-1.2.5.jar             |MineColonies for ComputerCraft|colony4cc                     |1.2.5               
		light-overlay-5.8.1.jar                           |Light Overlay                 |lightoverlay                  |5.8.1               
		cloth-config-4.11.26-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.26             
		chunkloaders-1.1.7-mc1.16.5.jar                   |Chunk Loaders                 |chunkloaders                  |1.1.7               
		exoticbirds-1.16.4-1.1.0.jar                      |Exotic Birds                  |exoticbirds                   |1.1.0               
		BetterMineshafts-Forge-1.16.4-2.0.3.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.3

**Comment by Seniorendi** [comment]
Could you try to update the version of the mod to the latest version?

**Comment by RedStoner** [comment]
latest version of the mod seems to have broken the AR Controller. Spacing on the screen is incredibly spaced out now. 
![2021-06-12_16 17 48](https://user-images.githubusercontent.com/1278466/121788238-c7f3a380-cb99-11eb-8977-4bf7a45cdf3c.png)
You can see the massive difference from the prior screenshots to this one. 
I feel this makes the program completly un-usable. where as last version i just have to replace a cable to use my program. Will be downgrading back to other versions to see where this ar controller got broken.

**Comment by Seniorendi** [comment]
I really don't know, what the issue is. But you could connect the me bridge directly to the ME Controller to prevent this.

**Comment by RedStoner** [comment]
the spatial anchor seems to have resolved the problem. Placing it on the controller would put it really far from where the items are going and in a very inconvenient location. I appreciate the help you have given thus far.
