### ISSUE TITLE
Redstone integrator lets redstone signal pass through it [Issue]

### ISSUE THREAD

**Issue by Hubbit200** [Seniorendi/AdvancedPeripherals#101]
**Describe**

The Redstone Integrator seems to let signals pass right through it, ie. if I have an active input on it then any outputs connected to it activate as well. It seems to only happen when a Redstone Wire Connector from Immersive Engineering is connected and not with redstone dust, however with other mods, such as the computers in CC:Tweaked, it doesn't have this problem, so I'm assuming it needs a fix on this end?

**Reproduce**

See image below, should be easy to reproduce. The Redstone Wire Connectors do have to correctly be set to input/output.

**Screenshots/Videos**
Image shows powered rail activated by detector rail inputting into a different side of the Redstone Integrator. If I swap the Integrator for a Computer for example the powered rail isn't activated.

![image](https://user-images.githubusercontent.com/39741041/121781436-f6c34700-cba4-11eb-9a69-b519db30fcca.png)

**Versions:**

- MC: 1.16.5
- Advanced Peripherals: v0.6.6b, 0.6.2b, 0.6.3b
- Forge: v36.1.18
- ImmersiveEngineering: v5.0.0-135

Let me know if you need any more info!

**Comment by Seniorendi** [comment]
Which Advanced Peripherals version do you use?

**Comment by Hubbit200** [comment]
The latest, 0.6.6b. It also seems to happen on a couple of older versions I just tried

**Comment by SirEndii** [comment]
Fixed in 0.7a
