### ISSUE TITLE
[Feature] Online player detection

### ISSUE THREAD

**Issue by JJSax** [Seniorendi/AdvancedPeripherals#106]
**Describe your feature idea**
The player detector has some cool stuff, but I think an online detector would be cool.  Something that will return an array of all players online.

**Describe alternatives you've considered if you've any**
Currently we can see if a player is within a big radius, but that doesn't work if they are in other dimensions.

**Comment by Wojbie** [comment]
In other mods this feature is usually put in chat box.

**Comment by SirEndii** [comment]
Fixed in 0.7a
