### ISSUE TITLE
[Issue] Unlocalized AP Villager

### ISSUE THREAD

**Issue by NillerMedDild** [Seniorendi/AdvancedPeripherals#107]
**Describe**

No localization for the AP villager.

**Reproduce**

1. Find AP villager
2. Right click the AP villager
3. Observe the name shown in the GUI

...

**Screenshots/Videos**

 https://i.imgur.com/kUcB0Zz.png

**Versions:**

- Forge version: 1.16.5-36.1.31
- AdvancedPeripherals version: advancedperipherals-0.6.7b

Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2449

**Comment by Seniorendi** [comment]
Because of the low priority, I will fix this in 0.7

**Comment by NillerMedDild** [comment]
Sounds good, I'll just add the entry for the time being then :)

**Comment by Seniorendi** [comment]
I use `entity.minecraft.villager.advancedperipherals:computer_scientist` in the lang file. But `entity.minecraft.villager.advancedperipherals.computer_scientist` would be right. There is a `:` instead of a `.`

**Comment by NillerMedDild** [comment]
Yep that did indeed fix it, thanks again.

**Comment by Seniorendi** [comment]
I will reopen this issue, will be closed when 0.7 is release 👍🏻

**Comment by SirEndii** [comment]
Fixed in 0.7a
