### ISSUE TITLE
Enable redstone On/Off feature using the IE redstone wire connector. [Feature]

### ISSUE THREAD

**Issue by rudugampola** [Seniorendi/AdvancedPeripherals#112]
Currently, only the channel can be changed. To turn on redstone to the proxy block requires placement of a redstone torch underneath. It would be nice to be able to turn on/off a redstone signal in addition to changing color.

**Comment by Seniorendi** [comment]
After a deeper look. I recognized that I can't simulate a redstone signal for a redstone connector. But you could set a redstone output with the redstone api from computercraft or the [Redstone Integrator](https://docs.srendi.de/peripherals/redstone_integrator/).
