### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by aburone** [Seniorendi/AdvancedPeripherals#114]
On single player. I have a computer running a task who every couple of minutes searches for items to recycle. When it finishes, restarts the computer.
For whatever reason it's failing and crashes the (single player) server.
I have to kill minecraft with the task manages whenever this happens, so I don't get a crash-report.

When a task fails to run. It should show an error on the computer, or fail silently. But not crash like that

**Versions:**

- Forge version: 1.16.5
- AdvancedPeripherals version: advancedperipherals-0.6.7b.jar

error on debug.log
https://hastebin.com/eparaxemat.properties

**Comment by Seniorendi** [comment]
Hey, could you send me your code?

**Comment by aburone** [comment]
> 
> 
> Hey, could you send me your code?

Sure
https://hastebin.com/buwiqebeni.lua

Thanks!

**Comment by Seniorendi** [comment]
Yeah, I see, my fault. I will fix this in 0.7b

**Comment by SirEndii** [comment]
Fixed in 0.7a
