### ISSUE TITLE
Inventory Reader Stops Stacking

### ISSUE THREAD

**Issue by ThunderLord95** [Seniorendi/AdvancedPeripherals#115]
**Describe**

I have a inventory reader on a 2 second loop to refill my inventory with a specific item if it's less than 64, however when reading my inventory it must change something with the items in my inventory because when I go to put an item back in a chest with the same item using Shift-Click it doesn't stack. It also doesn't stack when picking up the item with your cursor and placing it on the other one. They will only stack again if you read the unread items. (Or Use the Inventory Tweaks Renewed Mod)

**Reproduce**

1. Get Item(s) Out of Chest
2. Make it Read Your Inventory
3. Put Item Into Chest with Same Item that has less than 64

...

**Screenshots/Videos**

If applicable, add screenshots or videos to help explain your problem.

**Versions:**

- Forge version: 1.16.5 (36.1.25)
- AdvancedPeripherals version: 0.6.7b

**Crashlog/log (Use https://paste.gg or https://pastebin.com to upload your crashlog/log)**
No Crash

**Comment by Seniorendi** [comment]
When you restart your game, does this fix the issue?

**Comment by ThunderLord95** [comment]
My post wasn't exactly the clearest so I've made a video to demonstrate what I meant to you.

https://user-images.githubusercontent.com/67135515/123454455-34ad6b80-d5a6-11eb-82df-10f9a82bf74b.mp4
