### ISSUE TITLE
importItemFromChest() voids items if RS system is full, haven't tried ME yet but i'd imagine that's the same case there too

### ISSUE THREAD

**Issue by YesVRC** [Seniorendi/AdvancedPeripherals#118]
Put this in your discord but I don't know which you check more, and I think it's a severe enough bug that it wouldn't hurt to double post.
https://discord.com/channels/734726882058174486/771935468149276682/858894539413520384

if you try and importItemFromChest() and the RS system is full, it will void the items
can we get a way to check using a method, preferrably returning a bool
something like isSystemFull() or something?
or maybe expose RS's "storage API" a bit so we can see the amount stored and check "manually"

other than that, love the mod, heaps of fun

**Comment by Seniorendi** [comment]
I will mark that as an enhancement. I will add a `isSystemFull` and a `getFreeSpace` function.

**Comment by SirEndii** [comment]
Fixed in 0.7a
