### ISSUE TITLE
[Feature] Include player UUID and if the message is hidden on chat box event

### ISSUE THREAD

**Issue by autione** [Seniorendi/AdvancedPeripherals#122]
**Describe your feature idea**
Include 2 arguments with the sender UUID and if the message is hidden (prefixed with $) on the `chat` event of the chat box.

**Describe alternatives you've considered if you've any**
For getting player UUID: Connecting to an API that returns the player UUID along with other info.
For checking if message is hidden: None.

**Additional context**
Maybe use it like this:
```lua
local _, name, message, uuid, hidden = os.pullEvent("chat")
if hidden then
  -- do things...
end
```

**Comment by SirEndii** [comment]
Added in 0.7a
