### ISSUE TITLE
[Feature] `Use` module for turtle or even kinetic augment similar to plethora one

### ISSUE THREAD

**Issue by SirEdvin** [Seniorendi/AdvancedPeripherals#123]
Provide a peripheral that will allow turtle to use items in inventory as real items. Also other features from [kinetic augment](https://plethora.madefor.cc/items/module-kinetic.html) can be added.

**Comment by Seniorendi** [comment]
I will reopen this until 0.7 is released

**Comment by SirEndii** [comment]
Added in 0.7a
