### ISSUE TITLE
Chat disabled due to Advanced Peripherals error

### ISSUE THREAD

**Issue by sharkck** [Seniorendi/AdvancedPeripherals#128]
Here is the log from a freshly restarted server... All I did here was start the server, join then try to type in the chat and this is the error:
https://pastebin.com/MkjyWsqA

Here is the log file from before I restarted:
[2021-07-02-1.log](https://github.com/Seniorendi/AdvancedPeripherals/files/6756191/2021-07-02-1.log)

Not sure what is going on here.  To my knowledge, there aren't any turtles placed or running.

**Comment by Seniorendi** [comment]
Duplicate of #96
This issue is fixed in 0.6.7b
