### ISSUE TITLE
[Feature] Use CC: Tweaked inventory API for inventory peripherals

### ISSUE THREAD

**Issue by RGFTheCoder** [Seniorendi/AdvancedPeripherals#129]
# **Describe your feature idea**
The inventory manager (and ae/rf bridges) could implement the same api as the cctweaked inventory api as it would allow polymorphic code to utilize different inventories with less work. (This doesn't mean removing the old functions as that may break some new ones, just adding an alias to the standard names) This also includes adding support for local directions (left,right) and cabled inventories as imports and exports and would allow exporting from a RF bridge directly to an inventory controller.

## Example renames for Inventory Manager
* `addItemToPlayer -> pullItems`
* `removeItemFromPlayer -> pushItems`
* `getItems` -> `list`
And maybe implementing the others:
* `size()` | Get the size of this inventory.
* `getItemDetail(slot)` | Get detailed information about an item.
* `getItemLimit(slot)` | Get the maximum number of items which can be stored in this

# **Describe alternatives you've considered if you've any**

An alternative is to add a local chest that is also wired and use it as a buffer, but requires extra management code, especially in more complex managed software.

# **Additional context**

This would match the CC: Tweaked api described [here](https://tweaked.cc/generic_peripheral/inventory.html) and should allow a chest to .pushItems to a RF bridge and such, as well as adding slot support to the inventory manager

**Comment by RGFTheCoder** [comment]
Originally described in #89

**Comment by Seniorendi** [comment]
> size() | Get the size of this inventory.

The occupied size? I mean, the size of a player inventory should always be the same

**Comment by Seniorendi** [comment]
Ah nvm. 
These functions are for the connected inventory

**Comment by RGFTheCoder** [comment]
size would always give the constant number and getItemLimit would give the stack size for that slot (usually 64, but enderpearls would have 16). This would mean that some code that uses a chest peripheral would just work if you passed in a RS peripheral or an inventory manager peripheral

**Comment by SirEndii** [comment]
Added in 0.7a
