### ISSUE TITLE
[Issue] Recipie loading errors when ME or RS are not installed.

### ISSUE THREAD

**Issue by Wojbie** [Seniorendi/AdvancedPeripherals#130]
**Describe**

When starting a server recipe loader will throw errors about invalid recipes into log.

**Reproduce**

Start a server without ME or RS installed.

**Versions:**

- Forge version: 1.16.5 - 36.1.32
- AdvancedPeripherals version: advancedperipherals-0.6.7b

**Crashlog/log (Use https://paste.gg or https://pastebin.com to upload your crashlog/log)**
Relevant lines:
https://pastebin.com/EUsfgzrZ

**Comment by Seniorendi** [comment]
There isn't really a way to fix this. The recipes are generated and I can't disable them

**Comment by SirEdvin** [comment]
Should be fixed in next release, #143 details

**Comment by SirEndii** [comment]
Fixed in 0.7a
