### ISSUE TITLE
[Issue] Chatty pocket computers in creative menu are not chatty.

### ISSUE THREAD

**Issue by Wojbie** [Seniorendi/AdvancedPeripherals#131]
**Describe**

Chatty pocket computers in creative menu don't have chatty peripheral on them.

**Reproduce**

Open creative menu. Try to get chatty pocket.

**Screenshots/Videos**

![obraz](https://user-images.githubusercontent.com/5893536/124362443-1cd48800-dc35-11eb-9204-07a3680c6b90.png)

**Versions:**

- Forge version:  1.16.5 - 36.1.32
- AdvancedPeripherals version: advancedperipherals-0.6.7b

**Comment by SirEndii** [comment]
Fixed in 0.7a
