### ISSUE TITLE
[Issue] Disabled features on server still show up in game and in creative menu.

### ISSUE THREAD

**Issue by Wojbie** [Seniorendi/AdvancedPeripherals#132]
**Describe**

After disabling some features (ME/RS Interface and Chunky Turtle) i expected them to not show up as items and in creative menu? Is there a way to verify they are disabled?

**Reproduce**

Disable feature in server config. Start creative world.

**Screenshots/Videos**

![obraz](https://user-images.githubusercontent.com/5893536/124362302-5e186800-dc34-11eb-8fb2-ee8f231e4a70.png)

**Versions:**

- Forge version:  1.16.5 - 36.1.32
- AdvancedPeripherals version: advancedperipherals-0.6.7b

**Comment by SirEdvin** [comment]
You can try to use them as peripheral) They should just provide no interface, but block presents. 

Personally, I am not sure that idea of removing block after disabling is good, because it can cause player crashes if you disable feature after server works already

**Comment by SirEdvin** [comment]
@Seniorendi May I suggest a solution? Someone can add text note with red color that specific item is disabled. What do you think about it?

**Comment by Seniorendi** [comment]
> @Seniorendi May I suggest a solution? Someone can add text note with red color that specific item is disabled. What do you think about it?

Sounds good

**Comment by SirEndii** [comment]
Fixed in 0.7a
