### ISSUE TITLE
RS Recipe Loading doesnt work with many Recipes (.listCraftableItems())

### ISSUE THREAD

**Issue by gamenTV** [Seniorendi/AdvancedPeripherals#133]
### Descripe

If you have too many recipes in the system and try to retrieve them with bridge.listCraftableItems() the computer gives the error: "Java Exception Thrown: Java.util.ConcurrentModificationException".

After some time .listItems() also crashes the program.

### Steps to reproduce

1. Create Some Code with .listCraftableItems()
2. Create your RS System with a bunch of recipes
3. Run the Script
![image](https://user-images.githubusercontent.com/50620722/124504958-bb452280-ddc8-11eb-9b9b-0427cc361e81.png)

### Version

0.6.7b (Latest)

### Minecraft, Forge and maybe other related mods versions

forge-1.16.5-36.1.32

### Crashlog/log

https://pastebin.com/3e2GmqTK

**Comment by SirEndii** [comment]
Fixed in 0.7a
