### ISSUE TITLE
[Feature] Environment Sensor

### ISSUE THREAD

**Issue by YetiWiz** [Seniorendi/AdvancedPeripherals#134]
### Describe your idea

The Environment Sensor would allow you to get information about the surrounding entities and blocks. The idea comes from the [Block Scanner](https://plethora.madefor.cc/items/module-scanner.html) and [Entity Sensor](https://plethora.madefor.cc/items/module-sensor.html) from Plethora.
You could get a list of surrounding mobs, for example, and retrieve their meta information (name, position, etc.).

**Comment by SirEdvin** [comment]
Well, we already have in `dev` branch something like Block Scanner, but with another name)

**Comment by SirEdvin** [comment]
Reopened until release

**Comment by SirEndii** [comment]
Fixed in 0.7a
