### ISSUE TITLE
[Feature] Villager children become "curious"

### ISSUE THREAD

**Issue by fatboychummy** [Seniorendi/AdvancedPeripherals#135]
### Describe your idea

Now I'm not sure if this is even possible to program given the restrictions of minecraft, but I had a random idea since AP adds the computer villagers. This is quite a silly idea, but decided to post it here for the hell of it and see what some thoughts are.

Villager children, like irl children, should walk up to computers or monitors they see and queue `key`/`monitor_touch` events and whatnot at random. You know, because kids like to do that when they see an unattended computer.

**Comment by Seniorendi** [comment]
This is a funny idea! But there isn't a way I could control the villager or the monitor events, sorry.
