### ISSUE TITLE
Environment turtle getBlockLightLevel always returns 9

### ISSUE THREAD

**Issue by FreekDS** [Seniorendi/AdvancedPeripherals#137]
### Descripe

When using an environment turtle, the method `getBlockLightLevel()` does not work as intended.
It always returns 9 and the returned value cannot be manipulated by placing light sources around the turtle.

_This issue was found by playing the [Valhelsia 3](https://www.curseforge.com/minecraft/modpacks/valhelsia-3) modpack (v3.3.3)_

### Steps to reproduce

1. Place an environment turtle
2. Enter the lua console by typing `lua`
3. Get the peripheral by typing `env = peripheral.find("environmentDetector")`
4. Check the light level by executing `env.getBlockLightLevel()` (returns 9 on my machine)
5. Change the light level around the turtle by placing any light source near it
6. Re-execute step 4, which gives same light level as before

### Version

0.6r

### Minecraft, Forge and maybe other related mods versions

forge-36.1.25 Minecraft 1.16

**Comment by Seniorendi** [comment]
I can't reproduce this. 
![image](https://user-images.githubusercontent.com/67484093/125160597-22bef180-e17e-11eb-8d1a-ec23a49cc359.png)
With the torch on the left, the detector does return 9, with the torch on the right the detector does return 12.

**Comment by SirEdvin** [comment]
I have also tested it with turtle. On 0.7b problem was fixed already (I assume) and everything works correct.
