### ISSUE TITLE
Mekanism Induction Matrix getEnergy() and getEnergyCapacity() truncated in high values.

### ISSUE THREAD

**Issue by Roukurai** [Seniorendi/AdvancedPeripherals#144]
### Descripe

Calling the peripheral's .getEnergy() or .getEnergyCapacity() return value a capped value of 2147483647 making it unable to determine current energy levels or capacity above this. 

![2021-07-14_09 19 36](https://user-images.githubusercontent.com/34500726/125647712-2fcb6914-c4ce-4cdf-94bb-881d520ccd54.png)
![2021-07-14_09 19 33](https://user-images.githubusercontent.com/34500726/125647718-580d0752-bbd5-44af-a10a-86f7dbc6dc0b.png)

### Steps to reproduce

Attach Computer to induction matrix size. 
Have either more energy or more capacity than 2147483647 and call the respecting method. 
Value will be capped at 2147483647.

### Version

0.6.7b (Latest)

### Minecraft, Forge and maybe other related mods versions

31.1.31 forge minecraft 1.16.5

**Comment by Seniorendi** [comment]
How did you wrap the peripheral? You need to use a peripheral proxy. See https://docs.srendi.de/peripheralproxy/getstarted/

**Comment by Roukurai** [comment]
Thanks, did not know that was used for it.

**Comment by Seniorendi** [comment]
As tip, in 0.7 you don't need a peripheral proxy anymore. You can directly connect the computer to supported blocks.
