### ISSUE TITLE
Redstone Integrator x redstone torch

### ISSUE THREAD

**Issue by gamenTV** [Seniorendi/AdvancedPeripherals#148]
### Descripe

Redstone Integrator doesn't update attached Redstone torches

### Steps to reproduce

1. Place a computer
2. Place a redstone integrator next to it
3. Attach a redstone torch directly to the redstone integrator
4. Write a script that changes the redstone signal on this site frequently

### Version

0.6.7b (Latest)

### Minecraft, Forge and maybe other related mods versions

forge-1.16.5-36.1.32

### Screenshots or Videos

https://ibb.co/983CMLk

**Comment by SirEndii** [comment]
Fixed in 0.7a
