### ISSUE TITLE
[Feature] Skinnable Turtles and Computers

### ISSUE THREAD

**Issue by kreezxil** [Seniorendi/AdvancedPeripherals#15]
**Describe your feature idea**
Make a special computer or turtle that can take on any texture in the pack or be spray painted with custom designs. That can be saved out as a custom models that can imported into other packs with the same mod.

**Comment by Seniorendi** [comment]
Sounds good!

**Comment by Jason-c-o** [comment]
Shaders, like those found in Immersive Engineering, may be a cool idea. You could equip them in a similar way Pocket Computers equip upgrades with the pocket API.

**Comment by Seniorendi** [comment]
After thinking a little more about it, I can't find a way to change textures or models from another mod. I'm sorry.
