### ISSUE TITLE
Redstone Integrator: Allow use of cardinal directions (north/east/south/west).

### ISSUE THREAD

**Issue by fatboychummy** [Seniorendi/AdvancedPeripherals#150]
### Describe your idea

This is something from Plethora on 1.12.2 and was a feature I quite liked a lot. I know which cardinal direction I need in order to use the integrator, but not the relative direction unless I use special care while placing the blocks.

It also does not help that the redstone integrators have *no* indicator at all about which direction "front" or "back" is. Once you place the integrator, if you forget which way it was placed you have to destroy and replace it.

It is not optimal.

**Comment by Wojbie** [comment]
Alternatively adding some kind of front indicator to the texture would work too. Perhaps we could take me interface with its arrow indicating direction as example?

**Comment by Seniorendi** [comment]
I will change the texture and add the ability to use cardinal and relative directions

**Comment by SirEndii** [comment]
Added in 0.7a

You can now use relative and cardinal directions
