### ISSUE TITLE
Induction Matrix detected as Generic Mekanism Machine

### ISSUE THREAD

**Issue by dualmacops** [Seniorendi/AdvancedPeripherals#152]
### Descripe

Induction Matrix detected as Generic Mekanism Machine, only shows commands for generic block not for Induction Matrix

### Steps to reproduce

Place a Peripheral proxy and on top of an induction matrix and a computer on the side.
wrap the proxy on the side that is placed and show the commands.

![image](https://user-images.githubusercontent.com/9700375/126482347-fa5a15f7-d8c2-4de1-b985-a5eda676de15.png)

### Version

0.6.7b (Latest)

### Minecraft, Forge and maybe other related mods versions

forge-1.16.5-36.1.65 in ATM6 1.7.2

**Comment by Seniorendi** [comment]
Is your matrix connected to a valve?

**Comment by dualmacops** [comment]
> Is your matrix connected to a valve?

Do you mean induction port? Yes i did try with it before posting this bug.

Just to be sure i did try again with it and now is working, idk why

**Comment by Seniorendi** [comment]
Kay, then everything is fine
