### ISSUE TITLE
CME crash 7/23/21w/ AP 0.7 Dev version 

### ISSUE THREAD

**Issue by jig487** [Seniorendi/AdvancedPeripherals#158]
### Descripe

CME crash

Seemed to be stable with just my 3d render engine running. I added a player detector to the side and ran this code while doing animations, which eventually crashed. 

``local function getData(name)
    local pos = pd.getPlayerPos(name)
    print("X of ".. name .." is: ".. pos.x)
    print("Y of ".. name .." is: ".. pos.y)
    print("Z of ".. name .." is: ".. pos.z)
    print(#pos)
end``

### Steps to reproduce

run this code _fast_ 

``local function getData(name)
    local pos = pd.getPlayerPos(name)
    print("X of ".. name .." is: ".. pos.x)
    print("Y of ".. name .." is: ".. pos.y)
    print("Z of ".. name .." is: ".. pos.z)
    print(#pos)
end``

### Version

Own compiled build

### Minecraft, Forge and maybe other related mods versions

1.16.5 MC,  0.7 Advanced Peripherals

### Crashlog/log

https://pastebin.com/jVejMC1d

**Comment by Seniorendi** [comment]
Could you try this build: https://cloud.srendi.de/index.php/s/mBRYYt9DNJQjyz8

**Comment by jig487** [comment]
This build seems to be stable. Haven't been able to crash it with the previous code

**Comment by SirEndii** [comment]
Fixed in 0.7a
