### ISSUE TITLE
/reload causes entire mod to break. Restarting session does not fix.

### ISSUE THREAD

**Issue by manaphoenix** [Seniorendi/AdvancedPeripherals#159]
### Descripe

After using the reload command the mod throws errors anytime a player tries to chat (and the chat msg does not go through).

restarting the session does not fix it.
This was running on a server.

### Steps to reproduce

Load pack with advance peripherals
start a world
type /reload in chat.
breaks everything.

### Version

0.6r

### Minecraft, Forge and maybe other related mods versions

Minecraft: 1.16.5 Forge: 36.2.0

### Crashlog/log

https://pastebin.com/Di4s7dMs

**Comment by Seniorendi** [comment]
Could you try to use the version 0.6.7b?

**Comment by manaphoenix** [comment]
Does not happen in the newest build.

The only reason I wasn't running it was because it was marked as beta and curse automatically defaults to downloading the release.

**Comment by Seniorendi** [comment]
The beta version is very stable, even more stable as 0.6r.
So you can use it if you want

I will close this now
