### ISSUE TITLE
[Feature] Custom Guis for Turtles and Computers

### ISSUE THREAD

**Issue by kreezxil** [Seniorendi/AdvancedPeripherals#16]
**Describe your feature idea**
Have gui module that can be modified in a gui designer that allows to set what variables get displayed where and what items are put where, and items come out where.

The module can be installed in a turtle or computer using a module insert table. The turtle or computer is placed in the table along with the module. After pressing insert. the turtle or computer comes out the other side.

Now the turtle or computer at this point can be reprogrammed only by attacking a computer monitor and keyboard to it, because when you right click it, you'll get the custom gui.

Or you can use the module insert table to remove the module.

Again be able to save out the modified computer or turtle for use inside other packs with this mod.

**Comment by Seniorendi** [comment]
I don't know how hard it's to implement this. I'll leave this feature request open until I start implementing this.

**Comment by Seniorendi** [comment]
Because I do not want to change the textures of the Computercraft GUI's, I will close this. If you want to change the GUI's, you can use a texture pack.
