### ISSUE TITLE
Chat box concatenates string together for sendMessage and sendFormattedMessage

### ISSUE THREAD

**Issue by manaphoenix** [Seniorendi/AdvancedPeripherals#163]
### Descripe

Version is selected as own compiled build because 0.7 is not an option.

When a chatbox is used to send a message it will concatenate the message together multiple times for every player online.

### Steps to reproduce

1. Create a forge server with this mod.
2. Connect a computer to a chatbox.
3. Send a message... Everything will work as expected.
4. Have another player connect to the server.
5. Now, message is sent twice as a concatenated string.

Example:
`sendMessage("Hello world!")`
-- with one player it prints "[DefaultPrefix] Hello world!"
-- with two players it prints "[DefaultPrefix] Hello world!Hello world!"

### Version

Own compiled build

### Minecraft, Forge and maybe other related mods versions

Minecraft: 1.16.5 Forge: 36.2.0

**Comment by SirEndii** [comment]
This is already fixed in 0.7r, forgot to close this
