### ISSUE TITLE
Chunky Turtle Not Unloading Chunks

### ISSUE THREAD

**Issue by alipali737** [Seniorendi/AdvancedPeripherals#165]
### Descripe

We ran a chunky turtle running a strip mining program, however it seems to have left behind a false ticking entity in those chunks meaning they never get unloaded even though the turtle has moved on.

You can see the chunks loaded in this image here: https://imgur.com/a/4bqT8l2
We captured this image using crashutils and as you can see the turtle has left all of its chunks loaded even though we have destroyed it. 

This is definitely an issue with the turtle as there were no other influences involved and we have fully checked multiple of these chunks for other ticking entities. We have restarted the server, attempted to force load then unload the chunks etc in order to update these chunks but nothing has worked.

This same effect also happened in a single player testing world so its consistent.

Any suggestions on how to fix this would be appreciated too.

### Steps to reproduce

Simply run a chunky turtle on its own

### Version

0.6.7b (Latest)

### Minecraft, Forge and maybe other related mods versions

Forge - 36.1.33 - minecraft 1.16.5

### Screenshots or Videos

https://imgur.com/a/4bqT8l2

**Comment by SirEndii** [comment]
Fixed in 0.7.1r
