### ISSUE TITLE
[AV v0.7r] Redstone Integrator Not Updating Block

### ISSUE THREAD

**Issue by Peekofwar** [Seniorendi/AdvancedPeripherals#167]
### Descripe

I went to open the doors to my reactor room, only to notice that the doors never opened. I entered the password again, exited the program (which leaves the redstone signals on), and went above the doors, destroyed and replaced the redstone dust under the redstone integrator, only for the redstone to suddenly spring to life.

I even removed and replaced the integrator to see if that would change anything, only for nothing to change.

### Steps to reproduce

1. Place down a redstone integrator.
2. Place redstone under the integrator.
3. Activate the bottom side.
4. Remove the redstone dust and place it again.

### Version

0.7r (Latest)

### Minecraft, Forge and maybe other related mods versions

Forge v36.2.2, Advanced Peripherals v0.7r, Computercraft: Tweaked v1.98.1

**Comment by SirEndii** [comment]
Fixed in 0.7.1r
