### ISSUE TITLE
Turtle improvement

### ISSUE THREAD

**Issue by gamenTV** [Seniorendi/AdvancedPeripherals#168]
### Describe your idea

A command to use items on blocks would be good

**Comment by SirEdvin** [comment]
did you try weak automata turtle and `useOnBlock`

**Comment by gamenTV** [comment]
didnt know that exists 
how exactly do i have to use it (i do not understand the documentation 😢 )

**Comment by gamenTV** [comment]
![image](https://user-images.githubusercontent.com/50620722/129481345-5c3eb017-61ce-4625-90d9-a1c0b74510fb.png)

**Comment by SirEndii** [comment]
Turtle upgrades are never on the front, use the command `peripherals` to see all peripherals.
