### ISSUE TITLE
failure to run on 1.17

### ISSUE THREAD

**Issue by emmemd** [Seniorendi/AdvancedPeripherals#170]
### Descripe

when i run minecraft with the minimum amount of mod required on forge 1.17. i receive the error 
advanced peripherals (advancedperipherals) encounted an error during the error event phase
before reaching any menu

### Steps to reproduce

1. load cc tweaked 1.17.1      2. load advanced peripherals 1.17      3.run forge 1.17 and you get the error before reaching any menu

### Version

0.7r (Latest)

### Minecraft, Forge and maybe other related mods versions

forge 1.17 

### Crashlog/log

https://gist.github.com/emmemd/68d23e870bc7721ba01ce89eaa10e2ee#file-crash-2021-08-16_14-06-07-fml-txt

**Comment by SirEdvin** [comment]
Try forge 37.0.28, please ...

**Comment by Fydar** [comment]
Change your Forge version to Forge 37.0.28 for now. This is the version that the mod is currently built against.

**Comment by SirEdvin** [comment]
Fixed version was released
