### ISSUE TITLE
Client crash when shift-clicking a memory card into an inventory manager

### ISSUE THREAD

**Issue by VMSaarelainen** [Seniorendi/AdvancedPeripherals#174]
### Descripe

When an inventory manager already has (someone else's) memory card in it, and you try to replace it with your own by shift-clicking the memory card in your inventory, the client crashes.

### Steps to reproduce

1. Put a memory card into an Inventory Manager
2. Create a memory card for yourself
3. Shift-click it into the manager

### Version

0.7r (Latest)

### Minecraft, Forge and maybe other related mods versions

Forge-36.2.0 Minecraft 1.16.5

### Crashlog/log

https://gist.github.com/VMSaarelainen/5970f994fbea28a40253b9269f9ae534

**Comment by SirEndii** [comment]
Do you play on a server or not?

**Comment by VMSaarelainen** [comment]
Yeah, I play on a private server with a friend of mine, for now just for testing/developing. Forgot to include that detail.

**Comment by SirEndii** [comment]
Do you use optifine or similar addons?

**Comment by VMSaarelainen** [comment]
No optifine, but apparently we are running some mods that might be to blame, mouse tweaks and inventory sorter. The full modlist is pretty long, but [here it is.](https://gist.github.com/VMSaarelainen/507005912563dd2ddedd9d8d4ada33af).

**Comment by SirEndii** [comment]
I can't reproduce it with 0.7.1r
Could you try to just use AP and CC:T?

**Comment by VMSaarelainen** [comment]
Yup, still crashes. Here's a video of the crash, the log and the mod pack (from curseforge), also shows my java version. https://drive.google.com/drive/folders/1zS_CAeHYOt0drXFA5-2uI05Z1dgNicNc?usp=sharing
