### ISSUE TITLE
java NullPointerException when trying to push items with an ME bridge into a full inventory

### ISSUE THREAD

**Issue by ralphgod3** [Seniorendi/AdvancedPeripherals#176]
### Descripe

when trying to push items in a full inventory with an me bridge a java nullpointer exception is thrown.

### Steps to reproduce

1. build ae network with me bridge and a computer next to me bridge
2. put inventory next to me bridge and fill completely with items
3. try to export any item into the inventory

### Multiplayer?

Yes

### Version

0.7r (Latest)

### Minecraft, Forge and maybe other related mods versions

Forge 36.2.0 mc 1.16.5 cc 1.98.1

### Screenshots or Videos

https://i.gyazo.com/7374c672d851a34f4c5fd64d1a16b00a.png
pictured is a diamond chests from iron chests but this also works with normal vanilla chests

### Crashlog/log

[latest.log](https://github.com/Seniorendi/AdvancedPeripherals/files/7014934/latest.log)
[debug.log](https://github.com/Seniorendi/AdvancedPeripherals/files/7014935/debug.log)

**Comment by SirEdvin** [comment]
Should be fixed in 0.7.2r
