### ISSUE TITLE
Not properly compiled mod for 1.16 causing crashing

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Seniorendi/AdvancedPeripherals#182]
### Descripe

advancedperipherals-0.7.1r for 1.16.5 causes the game to crash due to the mod not being compiled for java 8.
As 1.16 cannot load java 16 this causes a conundrum where either java causes a crash.

### Steps to reproduce

1. Have java 8
2. try run the mod
3. crash

### Multiplayer?

false

### Version

0.7r (Latest)

### Minecraft, Forge and maybe other related mods versions

Forge 36.2.2 MC 1.16.5

### Crashlog/log

https://gist.github.com/3x1t-5tyl3/ab362a3a33a183700c50575d0242168c

**Comment by SirEndii** [comment]
This is already fixed in the newest version

**Comment by SirEdvin** [comment]
@3x1t-5tyl3 just to be clear, you just need to *redownload* same version from curseforge. It still 0.7.1r (not not only in CF version, but in MC also)

**Comment by 3x1t-5tyl3** [comment]
Interesting. That's good to know. That explains it. Thanks a lot. Sorry for the timewaste. <3
