### ISSUE TITLE
Chunky turtle will crash server if placed.

### ISSUE THREAD

**Issue by Wojbie** [Seniorendi/AdvancedPeripherals#184]
### Descripe

If there is a turtle placed in world with Chunky upgrade placed on it server will crash.

### Steps to reproduce

Start server.
Place chunky turtle.
Crashloop.

Attached 2 crash reports.
First was generated when i placed turtle.
[crash-2021-08-29_18.20.18-server.txt](https://github.com/Seniorendi/AdvancedPeripherals/files/7073021/crash-2021-08-29_18.20.18-server.txt)
Second is on each crash loop.
[crash-2021-08-29_18.25.13-server.txt](https://github.com/Seniorendi/AdvancedPeripherals/files/7073020/crash-2021-08-29_18.25.13-server.txt)

### Multiplayer?

Yes

### Version

0.7.1r (Latest)

### Minecraft, Forge and maybe other related mods versions

Minecraft Version: 1.17.1, forge-1.17.1-37.0.45-universal

**Comment by SirEndii** [comment]
Which CC:T Version do you use?

**Comment by Wojbie** [comment]
cc-tweaked-1.17.1-1.98.2.jar

**Comment by SirEndii** [comment]
I recommend to downgrade CC:T until it works
We will fix that

**Comment by NeuroTypicalCure** [comment]
typo? 
![image](https://user-images.githubusercontent.com/5155910/131624736-988da4c2-fb74-4b31-ba1a-315b51d1aea7.png)

**Comment by SirEdvin** [comment]
Not a typo, 1.98.2 removed events. 

btw, this is fixed in 0.7.1r for 1.17

**Comment by NeuroTypicalCure** [comment]
is that a valid datatype? it's been a while since I did something java related

**Comment by SirEdvin** [comment]
Was valid, this is internal class. 

```java

public class X1{
    public static class X2 {
    }
}
```
