### ISSUE TITLE
Draconic energy core

### ISSUE THREAD

**Issue by Giehek** [Seniorendi/AdvancedPeripherals#186]
### Describe your idea

Add possibility to get informations about draconic energy core and reactor. Now it shows me energy in pylon (not in energy core), and thats useless i think

### Additional context

![2021-09-01_13 14 02](https://user-images.githubusercontent.com/63113462/131663587-2b84d74f-2398-4881-8ba4-b00b044adc6e.png)

**Comment by Giehek** [comment]
![image](https://user-images.githubusercontent.com/63113462/131664073-1661c390-40a7-44fa-9177-65c1556f4c55.png)
This could be new mod integration

**Comment by SirEndii** [comment]
Was my plan 😉

**Comment by SirEndii** [comment]
Because DE does now have CC integration, I will close this

**Comment by ThePotato97** [comment]
> 
> 
> Because DE does now have CC integration, I will close this

No it doesn't?

**Comment by Giehek** [comment]
No, it doesnt. I checked It a few days ago

śr., 27 paź 2021, 03:49 użytkownik ThePotato ***@***.***>
napisał:

**Comment by SirEndii** [comment]
Wait, I will re-check this

**Comment by SirEndii** [comment]
Ah, I got confused by the old computercraft classes from draconic evolution
I will reopen this

**Comment by SirEndii** [comment]
Added in 0.7.4r
I will create the documentation later in the day, but every function is the same as in 1.12. So you could use old scripts too.
