### ISSUE TITLE
Player detector infinite range

### ISSUE THREAD

**Issue by TheTechPny** [Seniorendi/AdvancedPeripherals#189]
### Descripe

The config option does not work, getPlayersInRange ignores this setting and is limitless
https://cdn.discordapp.com/attachments/779400553813377074/882808581085347850/unknown.png

CC Script
https://pastebin.com/raw/7hZBx8RD

### Steps to reproduce

Load up the provided CC script and observe how it bypasses the config settings

### Multiplayer?

Yes

### Version

0.7.1r (Latest)

### Minecraft, Forge and maybe other related mods versions

Forge 36.2.2 Minecraft 1.16.5

**Comment by SirEndii** [comment]
Fixed in 0.7.7r
