### ISSUE TITLE
[Feature] Documentation

### ISSUE THREAD

**Issue by LoganDark** [Seniorendi/AdvancedPeripherals#19]
Right now the only information I can find on this mod is that it does... stuff.

Please consider hosting textual documentation, similar to sites like https://tweaked.cc.

**Comment by Seniorendi** [comment]
I've been working on a documentation for the last hour. I will also publish this in the next few hours. If you want to see them: http://148.251.237.112:2020

**Comment by Seniorendi** [comment]
Added a documentation. 
https://docs.srendi.de
