### ISSUE TITLE
Block Reader reading metadata for blockstate

### ISSUE THREAD

**Issue by jajajafeti** [Seniorendi/AdvancedPeripherals#193]
### Describe your idea

Hey, I just tested out the blockreader and wanted to get the growth level of my wheat, but realised it can only give the data of a tile entity. I would like to have the same feature for the block reader, which all Turtels already have.
The Turtel has the function inspect() and returns a table with metadata of the block state.
http://www.computercraft.info/wiki/Turtle.inspect as you can see here the description.

Thanks.

(and sorry for posting this originaly wrong xd)

**Comment by SirEndii** [comment]
This should already work with `#getBlockData()`
