### ISSUE TITLE
Colony Integrator - getRequest() logs an error for every request returned in the table

### ISSUE THREAD

**Issue by adkinss** [Seniorendi/AdvancedPeripherals#194]
### Describe

When calling getRequests(), the following error is logged for each and every request returned in the table:

> [ComputerCraft-Computer-Runner-0/WARN] [computercraft/]: Received unknown type 'net.minecraft.util.text.StringTextComponent', returning nil.

### Steps to reproduce

The following program demonstrates the error:
> local colony = peripheral.find("colonyIntegrator")
> workRequests = colony.getRequests()

### Multiplayer?

Yes (local server in house)

### Version

0.7.2r (Latest)

### Minecraft, Forge and maybe other related mods versions

Mod Pack: Valhelsia 3.4.2a
Minecraft 1.16.5 and Forge 36.2.2
advancedperipherals-1.16.5-0.7.2r.jar (manually updated to this version)
cc-tweaked-1.16.5-1.98.1.jar
minecolonies-0.14.340-ALPHA-universal.jar

**Comment by adkinss** [comment]
I know that 0.7.3r is preparing for release.  Is there any chance that this issue can be fixed in time for the next release? 

I looked at the last week of logs on my server and I see the following:
- 1,759,641 lines logged to latest.log.
- 1,719,535 lines are the **_Received unknown type_** lines described above.
- 40,106 lines that are not the above error.

97.7% of my log is this one single error.  Looking at it another way, 301M of disk space is nothing but this one error.  Everything outside this error consumes only 6.7M of disk space.  

There are two of us on the server using Minecolonies and Advanced Peripherals and both of us are making use of the getRequests() call.  This is the most efficient way to monitor work requests (as opposed to monitoring requests coming into each of our many builders).  

Thank you,
Scott

**Comment by SquidDev** [comment]
You can temporarily disable the logging by turning off "log_computer_errors" in CC's config if it's causing excessive disk pressure. Though obviously this'd still need to be fixed at some point.

**Comment by SirEndii** [comment]
Could you provide the latest.log.

**Comment by adkinss** [comment]
Here you go:
https://raw.githubusercontent.com/adkinss/Valhelsia-3.4.4-Logs/master/latest.log
https://raw.githubusercontent.com/adkinss/Valhelsia-3.4.4-Logs/master/debug.log
