### ISSUE TITLE
[Feature] Chat Box: Text components

### ISSUE THREAD

**Issue by LoganDark** [Seniorendi/AdvancedPeripherals#20]
**Describe your feature idea**
Right now you can only send strings. I think it would be cool if you could send arbitrary components like the `tellraw` command. For example, you could send a clickable component that, when clicked, sends a command for the computer.

Minecraft already has facilities for converting JSON to text components, and back again. Perhaps you could convert a Lua table to JSON, then convert it to a component? And then add some event for receiving incoming text components, which would be like the same but in reverse.

**Describe alternatives you've considered if you've any**
N/A

**Additional context**
`§`-codes can be buggy, and you can't do interactive content like tooltips and click actions.

**Comment by SirEdvin** [comment]
Reopened until release

**Comment by SirEndii** [comment]
Added in 0.7a
