### ISSUE TITLE
MeBridge:getItem() throws Java.NullPointerException if requested item is a crafting recipe with no stock

### ISSUE THREAD

**Issue by lephro** [Seniorendi/AdvancedPeripherals#201]
### Descripe

Following situation:

Me Network:
- 20x Sand
- Crafting recipe for glass (but 0 glass)

getItem() will throw a Java.NullpointerException, if you request a fingerprint of a crafting recipe (in this example for the glass recipe), that has no stock in the network.

### Steps to reproduce

1. Create a me-network with a crafting recipe, but no items
2. Call MeBridge.getItem, with the fingerprint of the crafting recipe
3. Enjoy a Java.NullpointerException :P 

### Multiplayer?

Yes

### Version

0.7.1r (Latest)

### Minecraft, Forge and maybe other related mods versions

36.2.2

### Screenshots or Videos

https://ibb.co/TkK6RpN

**Comment by SirEndii** [comment]
[advancedperipherals-1.16.5-0.7.2r.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/7287447/advancedperipherals-1.16.5-0.7.2r.zip)

Hey, could you try this version
Unzip the file before using
