### ISSUE TITLE
[Request] Add village structure generation weight to config.

### ISSUE THREAD

**Issue by Vaelzan** [Seniorendi/AdvancedPeripherals#210]
### Describe your idea

Currently the weight of the Computer Scientist structure is fixed at 10 (https://github.com/Seniorendi/AdvancedPeripherals/blob/30522328322612634057e1d4b2a1b6cd0c5c74c0/src/main/java/de/srendi/advancedperipherals/common/village/VillageStructures.java#L34) and can only be changed in the config by disabling generation entirely. It'd be nice to be able to adjust that weight so that pack developers can tweak the frequency of structures to suit the needs of the pack (as the weight may be too high or too low compared to other mods that also add structures to villages).

**Comment by SirEndii** [comment]
Added in 0.7.4.1b
