### ISSUE TITLE
Deepslate ores are not recognized by geo scanner's chunkAnalyze method

### ISSUE THREAD

**Issue by MileyHollenberg** [Seniorendi/AdvancedPeripherals#215]
### Descripe

When trying to create a script to search for diamonds using the geo_scanner peripheral on an advanced turtle I found out that deepslate diamond was not being recognized, after looking a bit further it seems that not a single type of deepslate ores are being recognized at all.

### Steps to reproduce

Inside a chunk with Deepslate ores you can run this script on a turtle with a geo_scanner equipped on the right side

```
geo = peripheral.wrap("right")
data = geo.chunkAnalyze()
for k,v in pairs(data) do
    print(k .. ": " .. v)
end
```

When running this script it will only print regular ores but no deepslate variants will be returned

### Multiplayer?

false

### Version

0.7.2r (Latest)

### Minecraft, Forge and maybe other related mods versions

Forge 37.0.84 Minecraft 1.17.1

**Comment by SirEdvin** [comment]
Oh, this unexpected ....

**Comment by SirEdvin** [comment]
Okey, so .... blame forge: https://github.com/MinecraftForge/MinecraftForge/pull/7891

**Comment by SirEdvin** [comment]
Just to provide more context. To determinate what is ore and what is not, I am using tag `forge:ores` and currently forge doesn't add this tags.

You can define this tags yourself via datapack or wait for forge to fix it

**Comment by SirEndii** [comment]
Thank you SirEdvin
I will close this then
