### ISSUE TITLE
RS Bridge can't export items into Mekanism machines

### ISSUE THREAD

**Issue by samfundev** [Seniorendi/AdvancedPeripherals#222]
### Descripe

I'm not sure if this is intentional behavior but `exportItemToPeripheral` doesn't export items into a Mekanism machine. Specifically, I tried this out with the crusher.

### Steps to reproduce

1. Call `exportItemToPeripheral` on a Mekanism machine.
2. Get a return value of zero and no items get exported.

### Multiplayer?

Yes

### Version

0.7.3r

### Minecraft, Forge and maybe other related mods versions

Forget 36.2.4 Minecraft 1.16.5

**Comment by SirEndii** [comment]
Could maybe work with the mekanism bin.
But I will see how I could add integration for more types of inventories.

**Comment by SirEndii** [comment]
This is more an issue with mekanism itself. They add cc integration in V10.1. This is the reason they override the inventory peripheral functions. Only mekanism could implement functions to support these things.
