### ISSUE TITLE
Configurable energy usage for Refined Storage Bridge

### ISSUE THREAD

**Issue by Havaro** [Seniorendi/AdvancedPeripherals#223]
### Describe your idea

The Rs Bridge currently uses 500FE/t. This value is currently hardcoded. It would be nice to be able to change this in the config. 

### Describe alternatives you've considered if you've any

It is possible to change this value and recompile for me but I think others will benefit from this change too.

**Comment by SirEndii** [comment]
Added in 0.7.5r
