### ISSUE TITLE
Config File Name Typo?

### ISSUE THREAD

**Issue by mcilhargey** [Seniorendi/AdvancedPeripherals#228]
### Descripe

https://github.com/Seniorendi/AdvancedPeripherals/blob/1.16/src/main/java/de/srendi/advancedperipherals/common/configuration/MetaphysicsConfig.java#L43

Is the filename supposed to be metaphysics instead of methaphysics?

### Steps to reproduce

n/a

### Multiplayer?

Yes

### Version

0.7.5r (Latest)

### Minecraft, Forge and maybe other related mods versions

n/a

**Comment by SirEndii** [comment]
Already fixed in 0.7.5r 🙂

**Comment by SirEndii** [comment]
Oh no, misread
I thought you mean the old typo...
Yeah, methaphysics is wrong. <:

**Comment by mcilhargey** [comment]
👍🏻

**Comment by SirEndii** [comment]
Improved in 0.7.7r
