### ISSUE TITLE
[Feature] Turtle chunk loader

### ISSUE THREAD

**Issue by Kollock5** [Seniorendi/AdvancedPeripherals#23]
**Describe your feature idea**
A chunk loader for the turtles that maybe needs to be fueled with ender pearls, maybe you can toggle that in a config file.
not sure if you can implement that but it would be quite nice...

**Comment by Seniorendi** [comment]
Sure, i will add the chunky turtle in the next update(0.4b)

**Comment by Seniorendi** [comment]
Added in 0.4a
