### ISSUE TITLE
Compass Peripheral

### ISSUE THREAD

**Issue by Owningle** [Seniorendi/AdvancedPeripherals#230]
### Describe your idea

Compass peripheral for turtles to allow them to get the direction they are facing (north, east, south, west).

**Comment by Havaro** [comment]
Reminds me of the (old) Compass Upgrade from [MiscPeripherals](http://www.computercraft.info/forums2/index.php?/topic/4587-cc153mc152-miscperipherals-33).

**Comment by SirEndii** [comment]
👍🏻

**Comment by SirEndii** [comment]
Added in 0.7.7r
Currently only has one function, `getFacing`. I will add this to the docs in the near future.
