### ISSUE TITLE
Mekanism induction matrix detected as mekanismMachine

### ISSUE THREAD

**Issue by zephhhhhh** [Seniorendi/AdvancedPeripherals#231]
### Descripe

The mekanism induction matrix multiblock is detected as a generic machine rather than the induction matrix and only exposes the generic machine methods to the computer no matter how the computer is connected.

This issue persists using a modem using peripheral.find, placing the computer directly next to the induction port and using peripheral.wrap, no matter what the computer detects it as a "mekanismMachine"

I've tried rebuilding the multiblock, replacing the modems and wiring, different worlds, different advanced peripheral versions and different cc-tweaked versions but the issue still persists.

### Steps to reproduce

1) Build any size Mekanism induction matrix, I used 3x4 matrix with 1 cell and 1 provider.

2) Place a computer next to an induction port connected to the multiblock.

3) Enter the lua interpreter and type "peripheral.wrap('direction')" to print out the available methods to verify it is detected as a generic mekanism machine

### Multiplayer?

Yes

### Version

0.7.5r (Latest)

### Minecraft, Forge and maybe other related mods versions

Forge 36.2.9 Minecraft 1.16.5

**Comment by SirEndii** [comment]
Should be fixed in 1.16.5-0.7.6r
