### ISSUE TITLE
Calling getBuildings() for minecolonies-1.0.200-ALPHA crashes

### ISSUE THREAD

**Issue by carl010010** [Seniorendi/AdvancedPeripherals#232]
### Descripe

Looks like some incompatibly happens when you use minecolonies-1.0.200-ALPHA and advancedperipherals-1.16.5-0.7.5r. My code that worked in minecolonies-1.0.0-RELEASE, now crashes the game. Minecolonies does recommend running the lastest alpha. [Update to the latest alpha if you are not running the latest. (Alpha does not mean it’s unstable, it just means it’s a relatively small release.)](https://wiki.minecolonies.ldtteam.com/source/misc/troubleshooting)

    colony = peripheral.find('colonyIntegrator')

    mon = peripheral.wrap("left")

    function Test()
        term.redirect(mon)

        line = 1
        for k, v in ipairs(colony.getBuildings()) do
            num = k

            if num < 10 then
                num = "0" .. num
            end

            name = ''

            if v.citizens[1] ~= nil then
                for i, t in ipairs(v.citizens) do
                    name = name .. ' ' .. t.name
                end
            else
                name = " Empty"
            end
            print(num .. ": " .. v.name .. ' ' .. name)

        end
    end
 
    while true do
       mon.clear()
       mon.setCursorPos(1, 1)

        Test()
        sleep(1)
    end

### Steps to reproduce

Have and be inside of a colony
Get peripheral `colony = peripheral.find('colonyIntegrator')`
Call `getBuildings()`
Crash to  desktop

### Multiplayer?

false

### Version

0.7.4.1b (Latest)

### Minecraft, Forge and maybe other related mods versions

Forge 36.2.19 1.16.5

### Crashlog/log

https://pastebin.com/FZzqcd1J

**Comment by carl010010** [comment]
Also I don't know if its possible, but you should try to keep compatibility with minecolonies-1.0.0-RELEASE, as that is what curseForge downloads by default

**Comment by SirEndii** [comment]
1.0.200-ALPHA is currently not on their maven repo(https://github.com/ldtteam/minecolonies/issues/7837)
So I'll for now use cursemaven until their fix that
I will release a fix in the next days

**Comment by SirEndii** [comment]
[advancedperipherals-1.16.5-0.7.6a.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/7704442/advancedperipherals-1.16.5-0.7.6a.zip)

You can this version until I publish it.
Does work server only.
Unzip the file before using.

**Comment by SirEndii** [comment]
Fixed in 1.16.5-0.7.6r
