### ISSUE TITLE
Mekanism induction matrix Get Total Energy and Get Total Max Energy showing as 0

### ISSUE THREAD

**Issue by VeryG00dName** [Seniorendi/AdvancedPeripherals#234]
### Descripe

The mekanism induction matrix multiblock when queried with Get Total Energy or Get Total Max Energy will always return zero

### Steps to reproduce

1. Build any size Mekanism induction matrix, I used 3x4 matrix with 1 cell and 1 provider.
2. Place a computer next to an induction port connected to the multiblock.
3. Enter the lua interpreter and type "peripheral.call('direction','getTotalEnergy')"

### Multiplayer?

LAN

### Version

0.7.4r (Stable latest

### Minecraft, Forge and maybe other related mods versions

Forge 36.2.9 Minecraft 1.16.5

**Comment by SirEndii** [comment]
Hey, could you try this version?
Unzip the file before using.

[advancedperipherals-1.16.5-0.7.6a.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/7699464/advancedperipherals-1.16.5-0.7.6a.zip)

**Comment by VeryG00dName** [comment]
nope still not working
what is strange is that percentage is working

**Comment by SirEndii** [comment]
> what is strange is that percentage is working

I added integration for standard mekanism tile entities, so that every energy supporting mekanism machine does support cc.

> nope still not working

That is strange. Sometimes it does work for me, sometimes not. 

What mekanism version do you use?

**Comment by SirEndii** [comment]
Should be fixed in 1.16.5-0.7.6r
Try to wrap the peripheral manually instead of using `call`
