### ISSUE TITLE
[1.18.1] HUD gets blurry when loaded together with Journey Map (+ CC Tweaked ofcourse.)

### ISSUE THREAD

**Issue by Gbergz** [Seniorendi/AdvancedPeripherals#235]
### Descripe

When Advanced Peripherals is loaded together with Journey Map (+ CC Tweaked ofcourse.), the Health, most icons get blurry after opening the Journey Map fullscreen map.

I've reproduced this in an empty instance only with Journey Map, Advanced Peripherals + CC Tweaked.

It doesn't occur when only Journey Map + CC Tweaked is installed. Only when Advanced Peripherals is added ontop of those.

### Versions:
Forge: 39.0.0
Minecraft: 1.18.1
CC-Tweaked: 1.99.1
Advanced Peripherals: 0.7.7.1r
Journey Map: 5.8.0alpha9

### Images
GIF of issue: https://gyazo.com/260fbea39b73719830d713afa9044188 (without and with AP)

Screenshots:
![image](https://user-images.githubusercontent.com/26634554/146037082-5f69eb9d-7d96-4dbc-8d71-5fa9e09b18cd.png)
![image](https://user-images.githubusercontent.com/26634554/146038037-6afbd354-cdde-4c93-bb60-ebc5bcef4819.png)

Happens on servers and singleplayer.

**-** Gbergz

### Steps to reproduce

1. Install Journey Map, CC Tweaked & Advanced Peripherals.
2. Launch Game. Forge 1.18.1 (39.0.0 is what I'm using.)
3. Enter World.
4. Open Journey Map fullscreen window. (**J** by default.)
5. Exit fullscreen.
6. Now most gui elements are blurry and look very weird, health, armor bar, food bar, crosshair + probably more gui stuff.
7. Profit.

### Multiplayer?

Both mp and sp.

**Comment by SirEndii** [comment]
Do you use the AR Goggles?

And does this also happen when you use remove journey map?

**Comment by Gbergz** [comment]
I don't use AR Goggles.

When Journey Map is removed it doesn't happen as it triggers by opening the fullscreen map. (on J.)

Problem also goes away if advanced peripherals is removed. (cc tweaked + journeymap stays).

**Comment by SirEndii** [comment]
A weird issue. I will give this a low priority. *Don't worry, I'll work on this*
Time to figure out why this does happen...

**Comment by Gbergz** [comment]
Sweet, hopefully it gets fixed soon. Cause it is rather annoying even though it's pretty minor.

**Comment by Gbergz** [comment]
No rush though.

**Comment by SirEndii** [comment]
[advancedperipherals-1.18.1-0.7.7.1r.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/7720846/advancedperipherals-1.18.1-0.7.7.1r.zip)

Hey, could you try this version? 
The AR Goggles may not work.
Unzip the file before using.

**Comment by Gbergz** [comment]
Using that version fixed it, no more blurry hud after opening Journey Map.

**Comment by SirEndii** [comment]
Then I know the issue
can take a while until I release a version for a fix because I need to change some AR stuff

**Comment by SirEndii** [comment]
Already fixed, forgot to close
