### ISSUE TITLE
[1.18.1] Bug with patchouli

### ISSUE THREAD

**Issue by itsdinkd** [Seniorendi/AdvancedPeripherals#236]
### Descripe

Error with patchouli

### Steps to reproduce

load game
check logs

### Multiplayer?

No

### Version

0.7.7.1r (Latest)

### Minecraft, Forge and maybe other related mods versions

39.0.5

### Crashlog/log

https://pastebin.com/ba7LtK4i

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/146628295-248f7907-e626-48b6-b7bf-e69ef75be98a.png)

**Comment by SirEndii** [comment]
Fixed in the latest version
