### ISSUE TITLE
Chat box - Formatted message to player, Formatted prefix, User UUIDs, Message Radius

### ISSUE THREAD

**Issue by Tim3Game** [Seniorendi/AdvancedPeripherals#237]
### Describe your idea

It's more the just one feature request but they should be mostly easy to implement.
- A `sendFormattedMessageToPlayer(string jsonObject, string user, string prefix)` command, which would allow to send a formatted message to a player only.
- A possibility to have formatted prefixes.
- A possibility to use player's UUID instead of just using their player name (which can changed).
- Ability to set a radius for the `sendMessage()` and `sendFormattedMessage()` functions (so it wouldn't send the message globally).

_If accepted I could try to do them and do a pull request of them if needed, but can't promise anything._

**Comment by SirEndii** [comment]
Added now the following
`sendMessage(String message, int range[, String prefixOrJson, String brackets, String bracketColor])` (Use -1 for infinite range)
Added the same for `ToPlayer` with uuid and name support.

**Comment by Tim3Game** [comment]
So I finally got time to do some code and create a pull request with some changes I made. If you don't like them, fell free to change them.

**Comment by SirEndii** [comment]
Improved in 0.7.7r
