### ISSUE TITLE
Chunky Turtle not loading refined storage system

### ISSUE THREAD

**Issue by Emmaliene** [Seniorendi/AdvancedPeripherals#238]
### Descripe

While chunky turtle is loaded in chunk which has refined storage set up in it it does not keep the system loaded when player has moved away from that chunk. I have network transmitters/receivers set up elsewhere on the map in key locations which when I go to them are not recognizing that the system is loaded since this most recent update to the mod.

*** I am running Advanced Peripherals 0.7.8r but this was not an option

![2021-12-21_11 11 08](https://user-images.githubusercontent.com/90182169/146851699-87777240-e085-44ad-bc33-c4b4ffa1d493.png)
![2021-12-21_11 12 07](https://user-images.githubusercontent.com/90182169/146851703-17186140-f715-4a5c-9e74-dcd6793f2b68.png)

### Steps to reproduce

1. Build refined storage set up
2. Place a Network Transmitter and Network Receiver as normal connected with the network card
3. Place chunky turtle in same chunk as the main network
4. Go to location that the network receiver is located at
5. Try to use a wireless terminal, see there is no connection there

### Multiplayer?

Yes

### Version

0.7.7.1r (Latest)

### Minecraft, Forge and maybe other related mods versions

Forge 39.0.6

**Comment by SirEndii** [comment]
Will be hard to test, but I will look into that
And you're sure, the chunk of the turtle is the same chunk of the RS system?

**Comment by Emmaliene** [comment]
I have checked with the chunk view option on and they are definitely in the same chunk unfortunately.

**Comment by SirEndii** [comment]
Could you  do enable the debug mode(configs/AdvancedPeripherals/general.toml) and send me a short log?
Best thing would be that you start the server,  place the turtle, try if it's loaded outside and then stop the server. *if you can do that*

**Comment by Emmaliene** [comment]
I'm not able to do that on the server, I'm playing in the ATM7 modpack and using their public server, I'll see about testing the debug mode rq.

**Comment by Emmaliene** [comment]
Had to split it into three parts xD

https://pastebin.com/eJfyde41
https://pastebin.com/RUAXfpvt
https://pastebin.com/QmMqad76

**Comment by SirEndii** [comment]
Uh, you play on the server
It does only work if their enable the debug mode
No problem,  just a bit harder for me to test

**Comment by Emmaliene** [comment]
I'm sorry I wish I could get it haha

**Comment by SirEndii** [comment]
Fixed in dev
[advancedperipherals-1.18.1-0.7.10b.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/8052146/advancedperipherals-1.18.1-0.7.10b.zip)
You can test it if you want
Unzip the file before using

**Comment by SirEndii** [comment]
Fixed in 0.7.11b
