### ISSUE TITLE
Function for AR-Goggles to get Players Facing Orientation

### ISSUE THREAD

**Issue by MrSushy** [Seniorendi/AdvancedPeripherals#241]
### Describe your idea

I had the Idea to create something like an artificial horizon in planes for when i'm flying with the Elytra. 
This was when i realized, i had no access to the facing orientation of a player. This would give the AR-Goggles a lot more AR possibilities like location- and facing-based informations and fixed AR elements (like e.g. a button label for the normal Minecraft button).

This could be a function of the AR-Goggles or maybe advanced AR-Goggles.

### Describe alternatives you've considered if you've any

This could be a function in the player detector or an addition to the getPlayerPos function.

**Comment by SirEndii** [comment]
Added in 0.7.10b
