### ISSUE TITLE
Compatibility with Draconic Evolution Flux Gate

### ISSUE THREAD

**Issue by PiggyWhiskey** [Seniorendi/AdvancedPeripherals#243]
### Describe your idea

Current support allows the Reactor to be configured with 5 methods. (ActivateReactor, ChargeReactor, GetReactorInfo, SetFailSafe, StopReactor
However most DE management scripts use Flux Gates to manipulate the reactor fully. AP does not currently support these.

Modems on Flux Gates will not activate, and directly connecting and wrapping the peripheral does not connect.

Request DE Flux Gate support be added to allow previous ComputerCraft scripts compatibility

### Linked Issues

https://github.com/Seniorendi/AdvancedPeripherals/issues/186

**Comment by SirEndii** [comment]
Draconic Evolution seems to already have CC integration in the latest version.
![image](https://user-images.githubusercontent.com/67484093/150236206-f4362b98-baa0-4e6b-ad3a-4ff7f81bc554.png)

I'll close this.
