### ISSUE TITLE
Redstone integrator sides are ambigious. 

### ISSUE THREAD

**Issue by Wojbie** [Seniorendi/AdvancedPeripherals#247]
### Descripe

When using redstone integrator it is hard to tell which side of integrator is front when looking at it. As all 6 sides have same texture. Only way to know is to remember which way one placed it and when working with multiples it can get a bit messy + finding one of 50 that were placed wrong can be a chore.
![obraz](https://user-images.githubusercontent.com/5893536/147887568-73de429d-0e56-4644-ae8e-808e9f148c53.png)
Front side is emiting power. All sides look exactly same. I know one can use sides of world in addition to forward ect but it would make sense to sides to be simpler to distinguish?

### Steps to reproduce

Place integrator. Forget which side is front. 

### Multiplayer?

No

### Version

0.7.8r (Latest)

### Minecraft, Forge and maybe other related mods versions

1.18.1

**Comment by SirEndii** [comment]
Currently doing this
![image](https://user-images.githubusercontent.com/67484093/150044882-308ffc76-c44d-4430-9729-044ba391dab4.png)

Changing the second ring of all textures to a very bright aqua. Opinion?

**Comment by SirEndii** [comment]
Improved in 0.7.7r
