### ISSUE TITLE
Over reporting Mekanism induction matrix by 2.5 times

### ISSUE THREAD

**Issue by VeryG00dName** [Seniorendi/AdvancedPeripherals#248]
### Descripe

with the new version of Mekanism 10.1.1 advanced peripherals is over reporting everything for the induction matrix by 2.5 times 

### Steps to reproduce

hook a computer to a Mekanism induction port that is part of a completed induction matrix and get any veritable using peripheral.

### Multiplayer?

LAN

### Version

0.7.6r

### Minecraft, Forge and maybe other related mods versions

Forge 36.2.9 Minecraft 1.16.5

**Comment by SirEndii** [comment]
Not an issue with AP. When you use mekanism V10.1, APs mekanism integration get disabled.
Mekanism does return their values in joules while AP does it in FE.
If you want the values in FE, subtract the values from mekanism by 2.5 or use their helper functions.
