### ISSUE TITLE
[Issue] Some typos in the me bridge documentation 

### ISSUE THREAD

**Issue by Kollock5** [Seniorendi/AdvancedPeripherals#25]
**Describe**
Some typos in the documentation 

getCraftingCPUs => is missing ()
retrieve(string itemname, int amount, string directio´ns) => has an ´ in directions

**Reproduce**
https://docs.srendi.de/Peripherals/mebridge/

**Screenshots/Videos**
![typo](https://user-images.githubusercontent.com/33529319/104574302-243bb100-5656-11eb-89e8-6885b4b19794.PNG)

me bridge looks pretty nice! good work!

**Comment by Seniorendi** [comment]
Thank you, i will fix that today.

**Comment by Seniorendi** [comment]
Fixed!
