### ISSUE TITLE
Fluid Detector, Gas Detector / Flow Detector

### ISSUE THREAD

**Issue by Tim3Game** [Seniorendi/AdvancedPeripherals#250]
### Describe your idea

A Fluid Detector would work the same as a Energy Detector but instead of energy it would detect the flow and type of a fluid. The same is for a Gas Detector, where it could detect Mekanism gas flow. 

### Describe alternatives you've considered if you've any

Another idea was to combine these detectors into one block for like universal pipes, which allow flow of multiple types (energy, items, fluids, gas) in one pipe/block, but maybe having it all in one new block could cause legacy code problems and maybe other ones too.

**Comment by SirEndii** [comment]
Good feature, not sure if I do it in 0.7 or 0.8. So the milestone will be empty

**Comment by SirEndii** [comment]
![](https://cdn.discordapp.com/attachments/808031516905963590/1027570768944566312/unknown.png)
