### ISSUE TITLE
[BUG] BlockReader gives no usefull data

### ISSUE THREAD

**Issue by Klebestreifen** [Seniorendi/AdvancedPeripherals#251]
### Descripe

When I use the BlockRader, it only spits out useless data. I don't think this is intentional.

### Steps to reproduce

1. set up BlockReader with chest at the front.
2. put something into the chest as a test.
3. control the block reader with `getBlockData`

### Multiplayer?

Yes

### Version

0.7.8r (Latest)

### Minecraft, Forge and maybe other related mods versions

39.0.10

### Screenshots or Videos

https://imgur.com/a/KrgM9YR

**Comment by SirEndii** [comment]
Yes, this should not happen. Propably a 1.18 thing which got changed.
