### ISSUE TITLE
Count of Item Request by Minecolony Colonists

### ISSUE THREAD

**Issue by Paraxdq** [Seniorendi/AdvancedPeripherals#252]
Hello, 

I tried to get the amount of items a colonist requests but the only thing i achieved was the following:

local integrator = peripheral.find("colonyIntegrator")
integrator.getRequests() -> items, then i got the name of the item and a value called count which returns 1, even if 32 items are requested. Is this a bug or intended and how am i supposed to get the amount a colonist requests?

Count from Stonewall is 1 and from wheat is 2, but thats not the requested amount only the number on the image itself:
![2022-01-06 23_33_23-Window](https://user-images.githubusercontent.com/32237881/148461812-6563207c-2d2c-485f-bcb8-21b893753ac1.jpg)

Thanks in advance :)

**Comment by SirEndii** [comment]
Please use the discord or the discussions tab in github for questions. But this looks like a bug, I'll move this issue to the proper repository and mark it has bug.

Could you please provide proper versions?

**Comment by Paraxdq** [comment]
Thanks for the response! I hope these additional informations will help you. We are playing on a multiplayer server of Valhelsia 3.4.8, soon 3.4.9.

Version
advancedperipherals-1.16.5-0.7.6r
minecolonies-1.16.5-1.0.311-BETA

Minecraft, Forge and maybe other related mods versions
Modpack Valhelsia 3.4.8 - Forge 36.2.22

Screenshots or Videos
![2022-01-06 23_32_23-Window](https://user-images.githubusercontent.com/32237881/148542473-cbced00c-5674-478b-9703-6f00ec8ab221.jpg)

As you can see on the screenshot, (I don't really know a better way to print out what functions are available for a command so I printed out key value pairs whenever there is a table) and there is the cobblestone wall from the image in the first post where count is 1 but i guess it should be 32.

Crashlog/log
No crash

**Comment by SirEndii** [comment]
Thank you for the information
I'll see what I can do

**Comment by SirEndii** [comment]
Just checked it - it seems that I fixed it in the last months by accident
![image](https://user-images.githubusercontent.com/67484093/176994194-4681dbcf-daaa-4bea-b7f5-3b8f29971d66.png)
`count` is the count of the request. Ignore the `count` from the item, this is just the item stack
