### ISSUE TITLE
Crash on Forge 39.0.45+ Right Click AR Controller

### ISSUE THREAD

**Issue by L0serr** [Seniorendi/AdvancedPeripherals#257]
### Descripe

Only checked the AR Controller because a lot of other mods are broken on any Forge build passed 39.0.44. There may be other blocks but it's always the same error message.

Specifically this part: 
java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag

### Steps to reproduce

1. Load world...
2. Place AR Controller...
3. Right click it...

### Multiplayer?

No

### Version

0.7.8r (Latest)

### Minecraft, Forge and maybe other related mods versions

Forge 39.0.59 Minecraft 1.18.1

### Crashlog/log

https://pastebin.com/4Gu8Vbem

**Comment by SirEndii** [comment]
Fixed in 1.18.1-0.7.9r
