### ISSUE TITLE
Importing a potion bottle via RS Bridge produces uncraftable potion

### ISSUE THREAD

**Issue by oleg-py** [Seniorendi/AdvancedPeripherals#258]
### Descripe

Using RS bridge to import a potion produces an "uncraftable potion" instead of whatever was attempted to be imported. It appears that the NBT part specifying the actual potion type gets lost on import.

### Steps to reproduce

Set up a simple RS network that has a functional storage:
![2022-01-25_14 48 27](https://user-images.githubusercontent.com/4143670/150972110-ad5560b6-5240-47de-aa57-85480b61a2f8.png)

Put a Water Bottle into the chest.
Do the following on the computer:
```
> lua
p = peripheral.find("rsBridge")
p.importItem({ name = "minecraft:potion" }, "TOP")
```

### Multiplayer?

No

### Version

0.7.7.1r

### Minecraft, Forge and maybe other related mods versions

Forge 36.2.22, Minecraft 1.16.5, Enigmatica 6 0.5.25

**Comment by SirEndii** [comment]
Fixed in 0.7.8r
