### ISSUE TITLE
OC2 integration

### ISSUE THREAD

**Issue by SirEndii** [Seniorendi/AdvancedPeripherals#259]
### Describe your idea

Before anyone asks, I'll just create a feature request directly.
Adding [OC2](https://www.curseforge.com/minecraft/mc-mods/oc2?t=kCSXxSMmvEldLgPycfMRkg&s=09) integration to AP.

### Additional context

https://www.curseforge.com/minecraft/mc-mods/oc2?t=kCSXxSMmvEldLgPycfMRkg&s=09

### Linked branch
https://github.com/Seniorendi/AdvancedPeripherals/tree/oc2

**Comment by kristibektashi** [comment]
Will there be OC1 integration when they update? (if they update)

**Comment by SirEndii** [comment]
> Will there be OC1 integration when they update? (if they update)

OC is already updated to modern versions → https://www.curseforge.com/minecraft/mc-mods/oc2
But since oc2 isn't that popular and that there's only an alpha 1.18 version, I'll not add OC2 support in the near future

**Comment by kristibektashi** [comment]
> > Will there be OC1 integration when they update? (if they update)
> 
> OC is already updated to modern versions → https://www.curseforge.com/minecraft/mc-mods/oc2 But since oc2 isn't that popular and that there's only an alpha 1.18 version, I'll not add OC2 support in the near future

I'm not talking about OC2. I meant the original OpenComputers. There have been plans to port it to 1.16.5: https://github.com/MightyPirates/OpenComputers/pull/3572

**Comment by SirEndii** [comment]
OC1 has the same author(s) as OC2 
→ https://www.curseforge.com/minecraft/mc-mods/oc2
→ https://www.curseforge.com/minecraft/mc-mods/opencomputers

I have no clue what this PR exactly is, but there is already a wonderful 1.18 port
We also do not support 1.16 anymore

**Comment by walksanatora** [comment]
> but there is already a wonderful 1.18 port

can you link this? I haven't seen it

**Comment by SirEndii** [comment]
> > but there is already a wonderful 1.18 port
> 
> can you link this? I haven't seen it

https://www.curseforge.com/minecraft/mc-mods/oc2/files

**Comment by walksanatora** [comment]
> > > but there is already a wonderful 1.18 port
> > 
> > 
> > can you link this? I haven't seen it
> 
> https://www.curseforge.com/minecraft/mc-mods/oc2/files

oc2 != oc
oc2 is a RISCV VM, oc is lua

**Comment by SirEndii** [comment]
can't you run lua scripts on oc2 too?

**Comment by SirEndii** [comment]
I'll close this since there isn't currently any active oc port

**Comment by kristibektashi** [comment]
> > > > but there is already a wonderful 1.18 port
> > > 
> > > 
> > > can you link this? I haven't seen it
> > 
> > 
> > https://www.curseforge.com/minecraft/mc-mods/oc2/files
> 
> oc2 != oc 
> oc2 is a RISCV VM, oc is lua

This is exactly my point. OC2 != OC1. OC1 has already been (mostly) ported to 1.16, and most likely will eventually be ported to newer MC versions. I believe it would be nice to have both OC1 and OC2 support when both of these are (eventually) ported to 1.19.

**Comment by kristibektashi** [comment]
> can't you run lua scripts on oc2 too?

OC2 is a full Linux VM, so in certain cases it can be a security risk, especially on public servers. In those cases it is more likely for someone to use OC1 than OC2 (when it is eventually ported)

**Comment by kristibektashi** [comment]
I personally believe both should be supported
