### ISSUE TITLE
[Feature] Read player inventory

### ISSUE THREAD

**Issue by Kollock5** [Seniorendi/AdvancedPeripherals#26]
**Describe your feature idea**
A way to read the player inventory, would be nice if you can stand on a block or click it and get info about the items in your inventory, or maybe as a module for a pocket computer.

Would also be nice if you can directly move items in the player inventory so you can write sorting scripts and stuff like that

**Comment by Seniorendi** [comment]
Sounds good, i will add a block to manage player inventorys in the future.

**Comment by Jason-c-o** [comment]
Also, functions such as "isPlayerEquiped" or "inHotbar(slot)" could be cool. Or "isWearingHelmet" etc.

May also be worth looking into Curios compatibility for this, with it's extra slots.

This is a large ask, I know.

**Comment by Seniorendi** [comment]
Well, I forgot this feature request. I already added a feature like this in 0.5b
But I will add more features like the ones you described.

**Comment by Seniorendi** [comment]
Well, I completely forget this feature request. I already added a block like this in 0.5b.
But I will add the features that you described.

**Comment by Seniorendi** [comment]
Added more functions to the inventory manager in 0.5.3b.
