### ISSUE TITLE
Geo Scanner chunkAnalyze() function does not include negative y in range

### ISSUE THREAD

**Issue by CornOnTheCaleb** [Seniorendi/AdvancedPeripherals#266]
### Descripe

Looking at the code for the Geo Scanner peripheral here: https://github.com/Seniorendi/AdvancedPeripherals/blob/a920c50f6b4a1f210ab27b951298168d70325fd0/src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/peripheral/GeoScannerPeripheral.java

The chunkAnalyze() function checks between y values of 0 and 256. In Minecraft 1.18.1, y values go below 0. I think it would be best to include these negative values in this function as many important ores are located there.

### Steps to reproduce

Look at line 111 of code here: https://github.com/Seniorendi/AdvancedPeripherals/blob/a920c50f6b4a1f210ab27b951298168d70325fd0/src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/peripheral/GeoScannerPeripheral.java

### Multiplayer?

Yes

### Version

1.18.1-0.7.9r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 39.0.59 Minecraft 1.18.1

**Comment by SirEndii** [comment]
I see, thank you for the hint!

Here is a hint for you
You can mark and share lines when you click on them
![image](https://user-images.githubusercontent.com/67484093/152705819-593197b9-a364-4024-9071-2911ad242040.png)
