### ISSUE TITLE
[Feature] Envrionment Detector methods

### ISSUE THREAD

**Issue by Jason-c-o** [Seniorendi/AdvancedPeripherals#27]
**Describe your feature idea**
Some additional methods for the Environment Detector I feel would be useful:

Chunk:
- isSlimeChunk() returns a boolean

Dimension:
- getDimension() returns a string of the current dimension
- isDimension(STRING) returns a boolean
- listDimensions() returns a table of the dimensions generated in the current world file.

Moon:
- getMoon() returns two variables, a number and string, indicating the phase of the moon (as shown here https://minecraft.gamepedia.com/Moon#Phases)
- isMoon(PHASE) returns a boolean

Weather:
- getWeather() returns a string
- isRaining, isSnowing, isThunderstorm, etc returns a boolean

Liquid:
- getLiquid(NAME, RANGE) returns a boolean if a certain liquid is found in range

**Describe alternatives you've considered if you've any**
-Some may be different enough to warrant their own block/component.
-You could also handle them as upgrade chips *for* the environment detector. (The detector could have a slot, or slots, to accept upgrades that allow use of the methods.)

**Additional context**
I'm more interested in the slime chunk method, but all these could be useful.
Apologies if you would prefer these as separate requests, but I felt organizing them by peripheral would be better.

**Comment by Seniorendi** [comment]
Added in https://github.com/Seniorendi/AdvancedPeripherals/commit/f22961faad3b78ee31391233e86300ec344561b8

**Comment by Jason-c-o** [comment]
Awesome, thank you! I've already been playing around with it!
