### ISSUE TITLE
RSBridge Returns Item When It Doesn't Have Any, But Is Craftable

### ISSUE THREAD

**Issue by beemerwt** [Seniorendi/AdvancedPeripherals#270]
### Descripe

When using an RS Bridge, calling "getItem" for an item that isn't in the system will return with { amount: 1 } if a pattern exists to craft the item. See the images below...
![bug1](https://user-images.githubusercontent.com/1851201/154281790-aa1d725e-732b-4b22-a250-4764f7b23235.png)
![bug2](https://user-images.githubusercontent.com/1851201/154281801-0b9fecd2-51cc-4a85-a895-68c9a09c1cc8.png)

If you take out the pattern it will return nil.
![bug3](https://user-images.githubusercontent.com/1851201/154281857-14dde56b-72b7-4b5c-8d69-3a3318d539f3.png)
![bug4](https://user-images.githubusercontent.com/1851201/154281860-a3a583f0-455a-4029-a63e-7ef3f0e66534.png)

It should either return nil or the item with "{ amount: 0 }" because you don't actually have the item. If you wanted to know whether or not you had a pattern for the item you should just call "getPattern" for it.

### Steps to reproduce

1. Connect an RS Bridge to a Refined Storage system
2. Attach a crafter to the Refined Storage system
3. Add any pattern of an item of which you have none stored in your Refined Storage system
4. Call "getItem" on your RS Bridge for that item

It returns the item with amount of 1, when it should return nil.
If you wanted to know if you had the pattern for that item, you would call "getPattern"

### Multiplayer?

Yes

### Version

1.16.5-0.7.6r

### Minecraft, Forge and maybe other related mods versions

Valhelsia 3 3.4.9

**Comment by SirEndii** [comment]
So
The thing with the amount is currently not possible with the RS api
But I added `isCraftable` to the items.
[advancedperipherals-1.16.5-0.7.7.1r.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/8263633/advancedperipherals-1.16.5-0.7.7.1r.zip)
You can test it if you want, only uploading it to the server would be enough.
Unzip the file before using.

**Comment by SirEndii** [comment]
![image](https://user-images.githubusercontent.com/67484093/158621179-053b2b06-d651-41a5-895b-7b9a8069bdef.png)

**Comment by SirEndii** [comment]
Added `isCraftable` for 1.16 in 0.7.8r
Will be added soon for 1.18

**Comment by SirEndii** [comment]
Fixed in 1.18.2-0.7.16b
