### ISSUE TITLE
AR Goggles don't work

### ISSUE THREAD

**Issue by PouPeuu** [Seniorendi/AdvancedPeripherals#273]
### Descripe

I have linked the goggles to the controller. I have even tried the example code but that didn't work either. 

### Steps to reproduce

1. try to use ar goggles

### Multiplayer?

No

### Version

1.18.1-0.7.9r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

39.0.75 Minecraft 1.18.1

**Comment by SirEndii** [comment]
Some functions do work, some functions do not

The ar goggles are currently just bugged, they'll get completely reworked in 1.19 0.8r
