### ISSUE TITLE
rsBridge getPattern  throws java exception on processing patterns

### ISSUE THREAD

**Issue by Dvginkel** [Seniorendi/AdvancedPeripherals#274]
### Descripe

I have a variable that holds all items that I currently have in Refined Storage (bridge.listItems()) , Now I'm looping over that list to get all items that have the #forge:ingots tag, then I'm try to see if there is an corresponding pattern for said item, but I get an error and cant make much of it.

The error is:

autocraft.lua:41: Java Exception Thrown: java.lang.IllegalStateException: cannot get byproduct outputs from processing pattern

and on line 41 of autocraft.lua you find this:  data = bridge.getPattern({name = allItems[k].name})

autocraft.lua full code: https://pastebin.com/jgzZj7Gp 

### Steps to reproduce

I think the autocraft.lua pastebin code explains it best

### Multiplayer?

Yes

### Version

advancedperipherals-1.18.1-0.7.11b.jar

### Minecraft, Forge and maybe other related mods versions

39.0.66

### Screenshots or Videos

https://imgur.com/a/qzYaYt2

### Crashlog/log

https://pastebin.com/xgvDL4sF

**Comment by SirEndii** [comment]
Fixed for 1.16 in 0.7.8r
Will be fixed soon for 1.18

**Comment by SirEndii** [comment]
It seems that I already published this in an older update without a proper changelog
The newest 1.18 version should contain this fix
