### ISSUE TITLE
[Feature] Envrionment Detector as an upgrade for Pocket Computers

### ISSUE THREAD

**Issue by Jason-c-o** [Seniorendi/AdvancedPeripherals#28]
**Describe your feature idea**
Allow pocket computers to equip an environmental detector like they would equip a modem, using the Pocket API.

**Describe alternatives you've considered if you've any**
None.

**Additional context**
A less portable method is obviously to place the detector and attach a modem, then use Rednet to access the block.

**Comment by Jason-c-o** [comment]
Could also open an additional request for the Player Detector as well.

**Comment by Seniorendi** [comment]
> Could also open an additional request for the Player Detector as well.

No, you do not need to do that. I will add the features(Player Detector and Environmental Detector) to the Pocket Computers.

**Comment by Seniorendi** [comment]
Added in 0.4.1b
