### ISSUE TITLE
geoScanner throws java.lang.IllegalStateException on scan.

### ISSUE THREAD

**Issue by alesandreo** [Seniorendi/AdvancedPeripherals#283]
### Descripe

Version: 0.7.13a
CC Tweaked: 1.100.4

Calls to the scan API of the geoScanner throw "java.lang.IllegalStateException: stream has already been operated upon or closed"

Further investigation seems to point to this line: 
LuaConverter.java:94
            data.put("tags", LuaConverter.tagsToList(block.builtInRegistryHolder().tags()));

### Steps to reproduce

Login as a Creative Account (works in survival as well)
Spawn in an Advanced Pocket Computer with a Geo Scanner Peripheral
Equip the computer by placing it in the hotbar and selecting it
Right click to bring up the UI
Once it boots, type lua at the prompt
At the lua prompt type 
`peripheral.find("geoScanner").scan(1)`

It will work if you set a variable as well, and if you use wrap instead of find, just wanted it simple.

This is reproducible on single player and multiplayer.

The version I  am using isn't listed. It is the alpha build for 1.18.2

### Multiplayer?

Yes

### Version

1.18.2-0.7.13a (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.0.(44/46) Minecraft 1.18.2

### Crashlog/log

https://pastebin.com/jLtaEKq2

**Comment by SirEndii** [comment]
Fixed in 0.7.14b

**Comment by Seniorendi** [comment]
Fixed in 0.7.14b
