### ISSUE TITLE
[1.18.2-0.7.13a] Various small issues with Advanced Peripherals village pieces

### ISSUE THREAD

**Issue by TelepathicGrunt** [Seniorendi/AdvancedPeripherals#284]
Hello, I am the dev for Repurposed Structures and I like to make mod compat datapacks to add other mod's village pieces to RS's biome variant villages. Page where I keep track of mods to make datapacks with: https://github.com/TelepathicGrunt/RepurposedStructures/issues/113

I was about to do your mod but as I settled down to start making new biome variants of Advanced Peripherals village pieces, I noticed there's a few issues with them. If these issues can be resolved, it will help me out to make sure I do the new variants correctly to match how Advanced Peripherals wants the blocks placed. Here's a list of what I came across:

- A monitor in the Scientist Plains Village piece is one block too low and causes a flower pot to be floating. 

- The Scientist Savanna Village piece's turtle block and all computer/monitor/speaker blocks will not rotate to face the correct direction if the village piece is rotated (this is usually caused by mod's blocks not overriding the rotate method to return the correct direction property. Has bitten me before too. Example: https://github.com/TelepathicGrunt/Bumblezone/blob/72bd6221216579f3d75d1e6e78e362ff1f7497ab/src/main/java/com/telepathicgrunt/the_bumblezone/blocks/ProperFacingBlock.java#L14 )

- The Scientist Desert Village piece has a floating potted plant. No idea what block was suppose to be under it.

- The outside of the Scientist Plains Village piece has a floating computer not being supported by anything. Very odd looking.
 
Pictures:
![image](https://user-images.githubusercontent.com/40846040/163273676-50e0daea-bd2a-4473-8983-0d03334607a0.png)
![image](https://user-images.githubusercontent.com/40846040/163274020-10700fbc-9a78-4826-85a5-816c2da07b0f.png)
![image](https://user-images.githubusercontent.com/40846040/163274482-26dd1fc9-7d89-4811-8809-3ac5801b3b2e.png)
![image](https://user-images.githubusercontent.com/40846040/163274721-5c956bcf-3d3c-4761-ba3a-defa1dce61db.png)
![image](https://user-images.githubusercontent.com/40846040/163274886-0eefde83-cc80-4041-be8a-b7ac43f4089d.png)

### Steps to reproduce

To reproduce, spawn into a world and use /locate command to find villages and look for the Advanced Peripherals village pieces in them. Or use Structure Blocks to manually spawn in the pieces (Structure Blocks can also load in with a rotation to test the block rotations as well)

### Multiplayer?

No

### Version

1.18.2-0.7.13a Advanced Peripherals with Forge 40.0.48

**Comment by SirEndii** [comment]
Thank you for the report

Yeah, I really messed these structures up

> The Scientist Savanna Village piece's turtle block and all computer/monitor/speaker blocks will not rotate to face the correct direction if the village piece is rotated (this is usually caused by mod's blocks not overriding the rotate method to return the correct direction property. Has bitten me before too. Example: https://github.com/TelepathicGrunt/Bumblezone/blob/72bd6221216579f3d75d1e6e78e362ff1f7497ab/src/main/java/com/telepathicgrunt/the_bumblezone/blocks/ProperFacingBlock.java#L14 )

We use the rotate methods. Also, the computers/monitors/speakers are not from AP, they're from cc.

https://github.com/Seniorendi/AdvancedPeripherals/blob/1.18/src/main/java/de/srendi/advancedperipherals/common/blocks/base/APBlockEntityBlock.java#L42

I'll see why they do not rotate, and I'll fix the structure blocks in the next update 👍🏻

**Comment by SirEndii** [comment]
Some  of these issues will be fixed in https://github.com/cc-tweaked/CC-Tweaked/pull/1083
And I'll publish an update with some structure fixes soon

**Comment by SirEndii** [comment]
Fixed *and* improved in 1.16.5 0.7.8r
Will be soon ported to 1.18

**Comment by SirEndii** [comment]
I regret that I only tested the desert one...
The others are completely broken

**Comment by SirEndii** [comment]
Now fixed for both versions.
Computers are still wrong rotated, but this is because of https://github.com/cc-tweaked/CC-Tweaked/pull/1083

**Comment by TelepathicGrunt** [comment]
Thanks! I’ll begin making the RS-AP compat datapack now to add variations of your buildings to my mod’s villages

**Comment by TelepathicGrunt** [comment]
checking right now with ap 1.18.2-0.7.15b and found a few ap houses with the entrance stairs facing the wrong direction:
![image](https://user-images.githubusercontent.com/40846040/169696035-532761cd-49a4-457c-beb6-96412a7d315a.png)
![image](https://user-images.githubusercontent.com/40846040/169696500-9074c7ee-feb3-4188-b130-a3322096acde.png)
![image](https://user-images.githubusercontent.com/40846040/169696342-b4197ab5-60c7-4ae7-a2bc-1e8e6e30391a.png)

(Also, the one green carpet right in front of the door for the snowy village piece prevents villagers from leaving the house due to no longer able to fit through doorway)

Otherwise, everything looks great!

**Comment by SirEndii** [comment]
I thought I fixed the stairs ._.
I don't like structures

**Comment by TelepathicGrunt** [comment]
If you set the stairs to direction east in the jigsaw block, it should fix it. Right now they are north (Edit: south for the snowy village piece is needed. Not east)

**Comment by SirEndii** [comment]
huh
I'm sure that I did that 🤔 
Maybe I forgot to save something

**Comment by SirEndii** [comment]
Should now be resolved in 0.7.16b
