### ISSUE TITLE
Energy detector doesnt keep transfer limit after restart

### ISSUE THREAD

**Issue by Hiranus** [Seniorendi/AdvancedPeripherals#285]
### Descripe

For some reason energy detector resets its set transfer limit after restarting world.

### Steps to reproduce

1. Set some transfer limit in energy detector
2. Save world
3. Load world
4. See limit restarted back to default value

### Multiplayer?

No

### Version

1.16.5-0.7.7.1r (Latest 1.16)

### Minecraft, Forge and maybe other related mods versions

36,2,31 MC 1.16.5

**Comment by SirEndii** [comment]
Fixed in 0.7.8r
