### ISSUE TITLE
[1.18.2] Server crash. "IllegalArgumentException: You need to cleanup force loaded chunk". (Turtle forceload crash.)

### ISSUE THREAD

**Issue by Gbergz** [Seniorendi/AdvancedPeripherals#287]
### Descripe

Running a server, and apparently an advanced turtle was used to forceload a chunk? which then lead to a crash.

### Steps to reproduce

Not entirely sure,
But trying to forceload a chunk with a Turtle.
Which then crashes the server.
Profit?

### Multiplayer?

Yes

### Version

1.18.2-0.7.13a.

### Minecraft, Forge and maybe other related mods versions

Forge 40.0.52 & MC 1.18.2

### Crashlog/log

https://gist.github.com/Gbergz/584979de48bc609575cce0649126f552

**Comment by SirEndii** [comment]
Thought I fixed that urgh
But thank you

**Comment by SirEndii** [comment]
Fixed in 0.7.14b
