### ISSUE TITLE
[ME Bridge] isItemCraftable, listCraftableItems, isItemCrafting bug if no item stack of items in ME system 

### ISSUE THREAD

**Issue by LauJosefsen** [Seniorendi/AdvancedPeripherals#293]
### Descripe

`isItemCraftable`

- Does not return true, if an item is craftable, but the amount in the ME system is 0.

`listCraftableItems`

- Does not return items that are indeed craftable, but the amount is 0.

`isItemCrafting`

- Gives lua error (Java null pointer exception) if amount is 0.

All these errors are caused by the same bug as #291.

I already have a fix local, but it is blocked waiting on the method I added in #292 :) Diff can be seen: https://github.com/LauJosefsen/AdvancedPeripherals/compare/fix-null-pointer-exception-me-craft-no-stock...LauJosefsen:fix-items-not-being-craftable-if-0-stock

### Steps to reproduce

Have an item craftable but with amount = 0.

Call isItemCraftable, listCraftableItems or isItemCrafting on the item.

### Multiplayer?

No

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.0, Minecraft 1.18.2, AE2 11.0.0-alpha.6

**Comment by SirEndii** [comment]
Thank you for the help! ^^
Love to see some contributions here, I'll look at your PR tomorrow. It's late here in germany (:

**Comment by SirEndii** [comment]
Reopen until released

**Comment by SirEndii** [comment]
Fixed in 0.7.14b
