### ISSUE TITLE
Importing/Exporting with networked peripherals for ME Bridge not working

### ISSUE THREAD

**Issue by AngellusMortis** [Seniorendi/AdvancedPeripherals#299]
### Descripe

`importItemFromPeripheral` and `exportItemToPeripheral` are not working with networked peripherals. The only work with directly connected ones (chest param = side name).

It always gives the error `Target '{name}' does not exist`.

### Steps to reproduce

1. Create ME network with ME Bridge and computer.
2. Place chest and connect to computer with wired modems/network cables
3. Place items in chest and ME network for testing.
4. Run the following script (replace any values as needed)

  ```lua
  b = peripheral.find("meBridge")

  for _, name in ipairs(peripheral.getNames()) do
      print(name)
  end
  
  b.exportItemToPeripheral({name="minecraft:stone"}, "minecraft:chest_0")
  b.importItemFromPeripheral({name="minecraft:cobblestone"}, "minecraft:chest_0")
  ```

### Multiplayer?

No

### Version

0.7.14b (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Tested with minimal mods, all on latest versions.

* Forge 40.1.19
* AE2 = 11.0.0a6
* CC: Tweaked  = 1.100.5

### Screenshots or Videos

CC Network setup:
![java_BERdestNwV](https://user-images.githubusercontent.com/490848/167456989-bc1798f3-984d-4e84-8913-dc57c12cce7f.png)

Output from above script:
![image](https://user-images.githubusercontent.com/490848/167457071-06e248bb-68e5-46e1-983d-01ec897eae82.png)

**Comment by AngellusMortis** [comment]
Issue seems to be gone now. (Forge 40.1.20, AE 11.0 stable, 0.7.15b)

**Comment by ahm23** [comment]
Issue seems to still exist.
Version 0.7.16b (Latest 1.18)

**Comment by ahm23** [comment]
> Issue seems to still exist. Version 0.7.16b (Latest 1.18)

Same setup, same code. Not sure if this is a bug or intended behavior (though hopefully a bug/missing chunk of code).
![image](https://user-images.githubusercontent.com/58716893/186959190-0f8940ea-9128-4a37-af93-0634d3f9ac8e.png)
![image](https://user-images.githubusercontent.com/58716893/186959228-6348a5ee-aa7a-4c70-9027-a442c1adf4c8.png)

**Comment by SirEndii** [comment]
Your rs bridge is not connected with the wired network
You need to connect the rs bridge with modems and wrap it with the network name so that it can access other network peripherals

**Comment by ahm23** [comment]
Ok so this was never an issue. It's intended behavior.

Thank you for the clarification.

**Comment by SirEndii** [comment]
> Ok so this was never an issue. It's intended behavior.

Yep, I also noticed this very late
