### ISSUE TITLE
[Issue] Environment Detector getLightLevel()

### ISSUE THREAD

**Issue by Jason-c-o** [Seniorendi/AdvancedPeripherals#30]
**Describe**
The Environment Detector's getLightLevel() method returns the [sky light level](https://minecraft.gamepedia.com/Light#Sky_light), which is always what the level would be at noon. Is this supposed to return the [block light level](https://minecraft.gamepedia.com/Light#Block_light) or [internal light levels](https://minecraft.gamepedia.com/Light#Internal_light_level), perhaps?

**Reproduce**
1. Attach a detector to a computer
2. Run the method at midnight in-game time
3. Get a light level of 15

**Versions:**
 - Forge version: 35.1.28
 - AdvancedPeripherals version: 0.3.3b

**Comment by Seniorendi** [comment]
getLightLevel() is used to do anything like a daylight sensor.
I will add the function getBlockLight()
