### ISSUE TITLE
fix discord link :(

### ISSUE THREAD

**Issue by Meowlan** [Seniorendi/AdvancedPeripherals#301]
### Descripe

The discord link is broken :(

### Steps to reproduce

1. Press on discord link
2. cry because it didnt work :(

### Multiplayer?

No

### Version

1.18.2-0.7.14b (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

discord :(

**Comment by SirEndii** [comment]
What discord link?
I don't remember that I linked the discord in the mod
But here is the link https://discord.srendi.de/

**Comment by Meowlan** [comment]
this exact link is broken https://discord.srendi.de/

**Comment by Meowlan** [comment]
![image](https://user-images.githubusercontent.com/69299012/168641285-71f8fab3-1c8b-449b-97f9-ef77c72eb4f2.png)

**Comment by SirEndii** [comment]
oh
Give me a minute

**Comment by SirEndii** [comment]
Fixed (:
