### ISSUE TITLE
[1.18.2] RS Bridge reports duplicate entries if craftable & in storage

### ISSUE THREAD

**Issue by Mx772** [Seniorendi/AdvancedPeripherals#304]
### Descripe

If any item is both in storage, and craftable, the RS bridge reports both as separate tables while doing listItems()
![image](https://user-images.githubusercontent.com/9059161/170576068-3291e600-0243-4889-90ea-17444c9779c7.png)
![image](https://user-images.githubusercontent.com/9059161/170576078-61562e2d-2f1d-4948-ab78-937dd55026c2.png)

Doing getItem() will report just 1 of the values, but _can_ report the 'craftable' value. 

I see that in #270 you note that you are adding a 'isCraftable' value, however, will this then appear on both?
If so, it's impossible to differentiate between the two. (Without adding logic for each crafting recipe/item)
(The Qty of the craftable item is the Recipe's output - So if you had 16xSand makes 16xGlass, the qty is 16)

Currently an issue on `advancedperipherals-1.18.2-0.7.15b`

### Steps to reproduce

Store an item that is also craftable via RS
run listItems()
Multiple Entries for the same 'name' will appear.

### Multiplayer?

Yes

### Version

1.18.2-0.7.14b (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.19 Minecraft 1.18.2

**Comment by SirEndii** [comment]
These entries are duplicates because I read the craftable and normal items and add these to the table.
It's a bit hard to fix this without destroying the performance, which is already bad

> I see that in https://github.com/Seniorendi/AdvancedPeripherals/issues/270 you note that you are adding a 'isCraftable' value, however, will this then appear on both?

Yeah it would. You would have with amount 1 and craftable true and one with amount xxx and craftable true

**Comment by SirEndii** [comment]
Fixed in 1.18.2-0.7.16b
