### ISSUE TITLE
Immersive Engineering Capacitor functions not working

### ISSUE THREAD

**Issue by Drater69** [Seniorendi/AdvancedPeripherals#306]
### Descripe

Hello, i tried to call a functions from Advanced Perihperals for capacitors from Immersive Engineering, but every time i try to call them it gives me attempt to call a field nil value . I running 1.16.5 version of Minecraft.

### Steps to reproduce

I try to use example from wiki:

capacitor = peripheral.wrap("right") --Wrap the capacitor

print("Stored energy: "capacitor.getStoredEnergy() "FE")
print("Energy Capacity: " capacitor.getMaxEnergy() "FE")

### Multiplayer?

No

### Version

1.16.5-0.7.8r (Latest 1.16)

### Minecraft, Forge and maybe other related mods versions

Forge 36.2.34 Minecraft 1.16.5

**Comment by SirEndii** [comment]
My fault

The default script does not work.

```
capacitor = peripheral.wrap("right") --Wrap the capacitor

print("Stored energy: "capacitor.getStoredEnergy() "FE")
print("Energy Capacity: " capacitor.getMaxEnergy() "FE")
```
If you want to connect a text with values, you need to connect them with two dots.
Like "Energy Capacity: "**..** capacitor.getMaxEnergy() **..**"FE"
