### ISSUE TITLE
Error due to a Null value

### ISSUE THREAD

**Issue by IceFoxyy** [Seniorendi/AdvancedPeripherals#309]
### Descripe

Hey,

i am running a Multiplayer Server, i dont know what caused the error or if it even is from Advanced Peripherals, but it kinda spamms my log dramaticly. 

How to get rid of the error?

### Steps to reproduce

I dont know it was just there

### Multiplayer?

Yes

### Version

1.18.2-0.7.14b (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.27

### Crashlog/log

https://pastebin.com/aqaWKZmY

**Comment by SirEndii** [comment]
> A BlockEntity type dan200.computercraft.shared.peripheral.printer.TilePrinter has thrown an exception trying to write state. It will not persist, Report this to the mod author

This is not thrown by Advanced Peripherals. This is an issue caused by CC-Tweaked. Please report it to https://github.com/cc-tweaked/CC-Tweaked
