### ISSUE TITLE
[1.18.2] [SMP] Mekanism multiblock get data issue

### ISSUE THREAD

**Issue by ptk2003** [Seniorendi/AdvancedPeripherals#312]
### Descripe

Hi. 
When i try get information from fission reactor (method like as 1.16.5) i get 'nil' error, when i request available methods i get list as screenshot below.

Other multiblock (matrix, turbine, boiler) return all listed method (like as getSteamFilledPercentage(), getCooledCoolantFilledPercentage(), getProductionRate(), etc).
But if i get energy it returned increased by 2.5 times (like as MJ, not FE).

### Steps to reproduce

build multiblocks, craft computer, connect they by wired modem

### Multiplayer?

Yes

### Version

1.18.2-0.7.15b (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

1.18.2-forge-40.1.51, cc-tweaked-1.18.2-1.100.8, Mekanism-1.18.2-10.2.4

### Screenshots or Videos

https://imgur.com/a/C4YPXDS

**Comment by SirEndii** [comment]
AP does not have a mekanism integration anymore
I removed it in the latest 1.16 version since mek does now have its own.

Here is a quote from the mek FAQ
> Q: Does Mekanism V10 have CC: Tweaked or OC2 support?
> A: Yes! As of Mekanism 10.1 we once again have integration with CC: Tweaked, and as of 1.18.2 we have support for OC2. See > https://docs.google.com/spreadsheets/d/1sheh1BIeP_vSto881H6UtgXvxdbyJEfILM_uUW_UD7Q/edit#gid=1674588729 for a > list of exposed methods and restrictions on calling them.
