### ISSUE TITLE
`RefinedStorage.isItemCraftable` is kinda tps heavy

### ISSUE THREAD

**Issue by Quezler** [Seniorendi/AdvancedPeripherals#315]
### Descripe

![Screen Shot 2022-07-11 at 20 52 51](https://user-images.githubusercontent.com/3179271/178337377-d03a9945-8aac-4ddb-b88a-73831851f24d.png)

### Steps to reproduce

Have lots of items stored (~4k unique slots in rs, and that was after the removal of damaged armor which sat at ~28k slots)

### Multiplayer?

Yes

### Version

1.16.5-0.7.8r (Latest 1.16)

### Minecraft, Forge and maybe other related mods versions

Enigmatica 6 v1.3.0

**Comment by SirEndii** [comment]
Hey,
can you send me that spark profiling result?

**Comment by Quezler** [comment]
https://spark.lucko.me/8qsCGvWduq

**Comment by SirEndii** [comment]
Fixed for 1.18
I'll see when I do this for 1.16
