### ISSUE TITLE
Energy Detector not working

### ISSUE THREAD

**Issue by bsixel** [Seniorendi/AdvancedPeripherals#316]
### Description

The energy detector doesn't seem to actually transfer power - cables and other energy transfer options form multiple mods will connect to two of the faces, but no energy will move through. Admittedly I'm unsure if this is broken functionality or just a lack of documentation on how to use them.

### Steps to reproduce

1. Place something with energy output (tested a couple generator types, a mek induction matrix and mek universal cables since they hold energy)
2. Place energy detector with energy connecting side next to energy output
3. Place computer next to energy detector on non-energy face
4. Place something that extracts energy on other energy face of energy detector (tried mek universal, pipez, laserio, integrated dynamics) with something it'll put energy into like a battery
5. It should at this point be transferring, but just for fun, wrap the peripheral and set the energy transfer rate limit on the energy detector
6. Nothing moves into the battery

### Multiplayer?

Yes

### Version

1.18.2-0.7.15b (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 39.0.55 Minecraft 1.18.1

**Comment by SirEndii** [comment]
![image](https://user-images.githubusercontent.com/67484093/179221670-219836d4-bb3e-42af-a206-16d0c7b86eab.png)

![image](https://user-images.githubusercontent.com/67484093/179221708-e4ab67e9-cff8-49b1-b5b2-c5689c45b570.png)

![image](https://user-images.githubusercontent.com/67484093/179221755-12b239d6-2165-49b4-89c6-d897ae921b78.png)


The energy detector seems to work just fine
But your forge version is very old. The newest would be 40.1.60

**Comment by bsixel** [comment]
Oh, I totally put the wrong forge version. Hmm... Ok I'll fiddle with it more, maybe it's an issue with our server.

**Comment by bsixel** [comment]
I created a new testing environment, and switched to single player:
It cuts off but AP is @ 1.18.2 0.7.15.b
![image](https://user-images.githubusercontent.com/8727026/179281247-75c7b601-161f-4e6a-8c8b-958e48ba8cca.png)


![image](https://user-images.githubusercontent.com/8727026/179280077-7242995e-9830-4ba6-8de0-d4545801ee64.png)
![image](https://user-images.githubusercontent.com/8727026/179280505-60ed6ef9-aa6d-4e60-ab90-281365ce295e.png)
![image](https://user-images.githubusercontent.com/8727026/179280666-eedd8a8d-28b1-4613-997f-2faf7a063e7b.png)

Do I need to hit the energy detector with a wrench or anything? The `getConfiguration` returns an empty table but I'm pretty sure that's true of every peripheral I've tried.

**Comment by SirEndii** [comment]
You sure that the universal cable with the creative cube is on the right side? The side with the arrows facing into the middle?

**Comment by bsixel** [comment]
Gosh. So sorry to have wasted your time, I didn't even notice that the two sides had the arrows pointing in different directions... That may be worth adding to the wiki.

**Comment by bsixel** [comment]
Also maybe some way to rotate them? Maybe right clicking? First use of the computer tool?

**Comment by SirEndii** [comment]
> Gosh. So sorry to have wasted your time, I didn't even notice that the two sides had the arrows pointing in different directions... That may be worth adding to the wiki.

No problem. I'll add this to the wiki 😄 

> Also maybe some way to rotate them? Maybe right clicking? First use of the computer tool?

Good idea
