### ISSUE TITLE
Colony Integrator getRequests Error

### ISSUE THREAD

**Issue by Gobgob30** [Seniorendi/AdvancedPeripherals#319]
### Descripe

When using the colony integrator it throws a cast java cast error.
because of the way I'm error correcting it seems to still be running after it is thrown but it takes a lot longer it seems like or dead locks.
minecolony version is the latest:
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3879870
had the issue in the alpha for this release as well, which I previously linked to:
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3876507
the code I am using that the exception is thrown. It throws when I call my requestDrop.
https://pastebin.com/QKgiwUb7
![image](https://user-images.githubusercontent.com/97519613/180303318-34ecb5fc-3c9d-4320-8812-2258231e6688.png)
this is a .json (not in json of course just suitable) just the serialized data of all my buildings plus a string of each blocks /data get info just incase it shows something important or helpful
[Building JSON.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/9162494/Building.JSON.zip)

### Steps to reproduce

Seems like it's just place the block.
Wrap the peripheral then call colonyIntegrator.getRequests()
Seems to work every now and then... idk what causes it.

### Multiplayer?

No

### Version

1.18.2-0.7.16b (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

forge 40.1.54 minecraft.18.2

### Crashlog/log

[latest.log](https://github.com/Seniorendi/AdvancedPeripherals/files/9162524/latest.log)

**Comment by Gobgob30** [comment]
Something to do with armor and swords. I just gave a bunch of armor and weapons to my guards and the error seemed to have stopped. Maybe the guard tower or barracks were doing something???

**Comment by wafebreaker** [comment]
Only happens when stuff inside the warehouse is requested to deliver. In my game

Example:
Builder needs 64 cobble, nothing in warehouse -> works like a charm.
Builder needs 64 Cobble, 64 Cobble is in warehouse -> crash with error

**Comment by Gobgob30** [comment]
Sorry. Confused what that was. I just pcall the function that used as a temporary means. It seems to clear out after a bit of erroring out. Every 30 times it errors on my command computer, it send a say message. I rarely get a message but I'm spawning exactly what they request too and with these versions of mine colonies and advperipherals.
advancedperipherals-1.18.2-0.7.16b
minecolonies-1.18.2-1.0.904-ALPHA

**Comment by SirEndii** [comment]
I tested some cases but it's hard to test something like this without a proper colony
I can test this when I get back home,. If anyone want to test it, here is the current dev filebuild:

[AdvancedPeripherals-0.7.16b.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/9468111/AdvancedPeripherals-0.7.16b.zip)

Unzip the file before using
