### ISSUE TITLE
[Feature] Valkyrien Skies + Advanced Rocketry compatibility features (once they update to 1.16)

### ISSUE THREAD

**Issue by Corvus20** [Seniorendi/AdvancedPeripherals#32]
**Describe your feature idea**
Methods of automating the movement of Valkyrien Airships/Advanced Rocketry Spaceships (and hybrids of both once the compatibility mod between them is updated, too.). Reading out the location of the vehicle in the world/galaxy, scanning for certain planet types, etc. Would all be amazing features to implement for this mod. 

**Describe alternatives you've considered if you've any**
The only thing that had similar features were the OpenComputers compatibility addons for Valkyrien Skies and Advanced Rocketry back in 1.12.2. Apparently they are broken at the moment, and OpenComputers is of course still in 1.12.2.

**Additional context**

**Comment by Seniorendi** [comment]
You say it, the two mods are not available for the 1.16. Since it is not certain whether they will ever get an update, I close this request first to keep the number of issues low.

But thanks for using Advanced Peripherals.
