### ISSUE TITLE
Block Reader can not display long arrays

### ISSUE THREAD

**Issue by JohnDog3112** [Seniorendi/AdvancedPeripherals#322]
### Descripe

When experimenting around with Hex Casting and reading the foci from it with the block reader, I found that it would display nothing for foci with coordinates inscribed. I later found that this was due to the fact that it stores the information in a long array which isn't displayed with the block reader. This also works with any items given a long array in their nbt data.

### Steps to reproduce

1. Place down a block read facing into a chest.
2. Place a computer next to the block reader.
3. Run /give @s stick{data:[L;1L,2L,3L]}
4. Put the stick in the chest
5. Read the block data with the computer

### Multiplayer?

No

### Version

1.18.2-0.7.16b (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.68 1.18.2

### Screenshots or Videos

https://imgur.com/a/LkoXgoA

**Comment by SirEndii** [comment]
Hey
[advancedperipherals-1.18.2-0.7.16b.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/9331544/advancedperipherals-1.18.2-0.7.16b.zip)

Could you try using this version? Should fix the issue
Unpack the file before using it.
