### ISSUE TITLE
Website - Wiki and Discord link - seems to be down

### ISSUE THREAD

**Issue by m-doescode** [Seniorendi/AdvancedPeripherals#326]
### Descripe

Excuse me if I've missed a message, but it seems like the website srendi.de is down

I cannot access it and I get a DOMAIN_PROBE_FINISHED_NXDOMAIN and it seems to have been down since at least yester day

https://www.whois.com/whois/srendi.de says that the status of the domain is in redemption period

### Steps to reproduce

1. Go to wiki.srendi.de or discord.srendi.de
2. Get an error DOMAIN_PROBE_FINISHED_NXDOMAIN

### Multiplayer?

N/A

### Version

N/A

### Minecraft, Forge and maybe other related mods versions

N/A

**Comment by SirEndii** [comment]
Yeah the site is down
Please use https://peaceful-nobel-03befe.netlify.app/ for the next days instead

**Comment by m-doescode** [comment]
Thank you!
