### ISSUE TITLE
AR Goggles should be a Bauble

### ISSUE THREAD

**Issue by StathisKap** [Seniorendi/AdvancedPeripherals#327]
### Describe your idea

same way you can wear rings, and have belts, and do all sorts of stuff in modpacks such as direwolf20 1.18, it'd be nice if we could equip the AR Goggles on the head slot. Cuz, honestly I find them nice to use, but not enough to sacrifice my mage armor

**Comment by SirEndii** [comment]
Bauble? Is that mod even ported to 1.16+?
We have integration for curio(Bauble fork for 1.16+)

**Comment by StathisKap** [comment]
Ah yeah curios. Well I'm playing Direwolf20 1.18 and the AR google can't go into the head slot. Is that specific to the modpack or is it the mod?

**Comment by SirEndii** [comment]
There is a specific ar goggles slot

**Comment by StathisKap** [comment]
oh damn. Thank you for letting me know. It's not near the head so I missed it haha. 
Sorry for any inconvinience
