### ISSUE TITLE
RS bridge exportItemToPeripheral Error

### ISSUE THREAD

**Issue by b0unt9** [Seniorendi/AdvancedPeripherals#329]
### Descripe

If you look at the peripheral device command, you can see that there is inventory in "left".
When trying to extract an item from RS to inventory of left through exportItemToPeripherial, an error occurs saying that there is no inventory in left.

### Steps to reproduce

I installed a computer on the right side of minecolony warehouse and proceeded.
<img width="997" alt="image" src="https://user-images.githubusercontent.com/40918958/184796720-8f9ee667-74c7-4ede-9fa6-0d726a7332d8.png">

```
rs = peripheral.find("rsBridge")
rs.exportItemToPeripheral({name="minecraft:stone", count=1}, "left")
```

<img width="825" alt="image" src="https://user-images.githubusercontent.com/40918958/184796005-67251f59-4731-411f-a980-e84af2a1f07c.png">

### Multiplayer?

LAN

### Version

1.18.2-0.7.16b (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.69 Minecraft 1.18.2

**Comment by SirEndii** [comment]
Following
You wrap the RS Bridge so you need to connect the warehouse also with an modem
You could place it at the modem or connect the bridge and the warehouse with modems & cables
