### ISSUE TITLE
[Issue] Player Detector missing particles

### ISSUE THREAD

**Issue by jajajafeti** [Seniorendi/AdvancedPeripherals#33]
**Describe**
The Player Detector has no particles when punched or destroyed

**Screenshots/Videos**

https://user-images.githubusercontent.com/61298096/105524204-9b6ce700-5cdf-11eb-87c4-6d22a56ae4c7.mp4

**Comment by Seniorendi** [comment]
Dors that happen with more blocks?

**Comment by jajajafeti** [comment]
No every other is fine.
