### ISSUE TITLE
Documentation link not working

### ISSUE THREAD

**Issue by donoya** [Seniorendi/AdvancedPeripherals#336]
### Descripe

The documentation link leads to a page that says the following:
This site can’t be reached
docs.srendi.de’s DNS address could not be found. Diagnosing the problem.
DNS_PROBE_POSSIBLE

I'm using the brave browser.

### Steps to reproduce

Download and install brave browser (may not be necessary if this is happening on other browsers)
click on the link in the wiki page of the github that says "Official Docs Here"

### Multiplayer?

No

### Version

1.18.2-0.7.18r

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.74, Minecraft 1.18.2

**Comment by SirEndii** [comment]
Hey, please read #328
