### ISSUE TITLE
Wrong Documentation

### ISSUE THREAD

**Issue by jajajafeti** [Seniorendi/AdvancedPeripherals#34]
In the Documentation of the Player Detector the event which fires when a player clicks the block is not "chatEvent" it is "playerClick".

![image](https://user-images.githubusercontent.com/61298096/105528045-c443ab00-5ce4-11eb-8881-89e2ec932037.png)

https://user-images.githubusercontent.com/61298096/105528535-61064880-5ce5-11eb-8270-35365f58c77c.mp4

**Comment by jajajafeti** [comment]
I want to add, that the real "chatEvent" only has the name "chat" as an event, I would suggest to also document it as such.
![image](https://user-images.githubusercontent.com/61298096/105533489-7f237700-5cec-11eb-8d0c-141b9b59e64c.png)

**Comment by Seniorendi** [comment]
Fixed, thank you for the report.
