### ISSUE TITLE
[Issue] Error while modloading with AE2

### ISSUE THREAD

**Issue by jajajafeti** [Seniorendi/AdvancedPeripherals#35]
**Describe**
So I wanted to test out AE2 with the features of this mod. But it crashed on loading the game.
AE2 works without AP and AP ofc without AE2.

**Reproduce**
1. Put AdvancedPeripherals and AE2 into your mod folder
2. Load Minecraft
3. Crash

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Versions:**
 - Forge version: 35.1.37
 - AdvancedPeripherals version: 0.3.5b
 - AE2 version: 8.2.0 beta.3; 8.1.0 (not working too)

**Crashlog/log (Use hasteb.in hasteb.in to upload your crashlog/log)**

https://paste.gg/p/anonymous/940737e0167d4e40bb315f6c8449ca8f

**Comment by Seniorendi** [comment]
Cause i worked on an RS Bridge for refined storage, i forget to remove the block for the newest version. I will fix this today, if you want, you can install refinef storage and it wouldn' crash.
