### ISSUE TITLE
[0.7.19r] Can't Place Modem on Back of Sideways Motor

### ISSUE THREAD

**Issue by Peekofwar** [Seniorendi/AdvancedPeripherals#351]
### Describe

I've noticed that I cannot place (non-block) modems on the back of motors when they are sideways... Simillarly, I cannot place modems on the sides of vertical motors. 

![image](https://user-images.githubusercontent.com/10189526/194783491-069424f4-8d79-4ea7-9d61-04da49885259.png)
![image](https://user-images.githubusercontent.com/10189526/194783675-bc956906-0f92-448e-88f4-aafc3408011c.png)

### Steps to reproduce

Place a motor sideways and attempt to place a non-block modem from Computercraft on its rear.

### Multiplayer?

Yes

### Version

1.18.2-0.7.19r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.60

**Comment by SirEndii** [comment]
Can you place a full block modem on the side of the motor?
I also don't think that this is an issue with AP since we don't manage the placements of the blocks. We just add peripherals to these blocks.

**Comment by Peekofwar** [comment]
Oh, heck... Don't know why I thought this was an AP thing... This belongs in Create Crafts & Additions issue tracker...
