### ISSUE TITLE
Crash when connecting cable to RS Bridge from AdvancedPeripherals-0.7.21b.jar

### ISSUE THREAD

**Issue by xp0colipse** [Seniorendi/AdvancedPeripherals#352]
### Describe

When trying to connect a cable to an RS Bridge from Advanced Peripherals, the game crashes.

### Steps to reproduce

1. Place an RS Bridge from advanced peripherals (AdvancedPeripherals-0.7.21b.jar)
2. Place a cable from refinedstorage-1.11.0.jar next to an RS Bridge.
3. Game crashes.

### Multiplayer?

No

### Version

AdvancedPeripherals-0.7.21b.jar

### Minecraft, Forge and maybe other related mods versions

Minecraft version 1.19.2, Forge 43.1.47

### Screenshots or Videos

https://medal.tv/games/minecraft/clips/GukYfY_tkC079/d1337TSzpbEf?invite=cr-MSxVWWYsNjIxMTkxMDYs

### Crashlog/log

https://pastebin.com/iaHjdbF0

**Comment by Creepdasheep** [comment]
What version of minecraft is Advanced Peripherals installed on?

**Comment by xp0colipse** [comment]
Its on 1.19.2

**Comment by SirEndii** [comment]
![image](https://user-images.githubusercontent.com/67484093/199800716-4ea29e6f-fb7c-4954-a280-81edd0d5d565.png)

**Comment by Quezler** [comment]
any chance you could publish a release or share a jarfile with this patched? i just ran into this issue as well 😅
