### ISSUE TITLE
Energy Detector bug allows infinite RF

### ISSUE THREAD

**Issue by GalacticArc** [Seniorendi/AdvancedPeripherals#355]
### Describe

Version 0.7.19
MC: 1.18.2
Forge: 40.1.80

Having 2 thermal expansion cells, and setting transfer rate to a negative number causes cells to instantly fill up and be buggy in general.

Video for demonstration

https://user-images.githubusercontent.com/5256221/199384030-0cdfe0db-bb29-41b5-aff3-91a1dfec489b.mp4

### Steps to reproduce

1. Setup a computer, 2 energy cells, and a energy detector in between
2. Add a power source from input side cell
3. Set TransferRateLimit to a negative number

### Multiplayer?

Yes

### Version

1.18.2-0.7.19r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.80 Minecraft 1.18.2

**Comment by SirEndii** [comment]
This is a very weird behavior, but it's fixed now in dev <:
I'll update AP this week with some juicy fixes
