### ISSUE TITLE
Environmental Sensor getMoon() method inconsistent?

### ISSUE THREAD

**Issue by Jason-c-o** [Seniorendi/AdvancedPeripherals#36]
**Describe**
The output for the getMoon() method is a little strange and inconsistent. (see image)
Some phases output just a name inside a table {" NAME "}, and others output {[NUM] = "NAME"}

**Reproduce**
Use the getMoon() method during different moon phases and check the output.

**Screenshots/Videos**
![Moon](https://user-images.githubusercontent.com/12125728/105620600-91b4b380-5db3-11eb-9c4c-6b4849358773.png)

**Versions:**
 - Forge version: 35.1.28
 - AdvancedPeripherals version: 0.3.3b

**Comment by Jason-c-o** [comment]
I don't mean to presume your intent should match my suggestion. There's still the issue of the output being inconsistent, though.

**Comment by Seniorendi** [comment]
![image](https://user-images.githubusercontent.com/67484093/105625112-33c1b380-5e27-11eb-8cd2-18d84d869d5b.png)

I see, only "Waning gibbous" returns no number.

**Comment by Jason-c-o** [comment]
Ah yes, I hadn't checked all of them before posting. I didn't realise it was only the one.

Though,
Is the output supposed to be { [NUM] = "NAME" } though? This makes it a bit awkward to handle

```
local phase = env.getMoon()
print(phase)
```
gives
```
table: 51f6e7cb --(or whatever id)
```
To actually access the info, you need to use
```
print(phase[1])
```
to output
```
Full Moon
```

Or am I just too new at LUA to know how to use both the number and the name? Shouldn't the output be
```
{0, "Full Moon"}
```
So you could do
```
print(phase[1])
print(phase[2])
```
to get
```
0
Full Moon
```

**Comment by Jason-c-o** [comment]
Nevermind.

I figured out  you can simple do

```
local phase = getMoon()

if phase[0] then
 do.Stuff()
elseif phase[1] then
 do.SomethingElse()
end
```

So _that's_ how you access it directly. Cool!

**Comment by Seniorendi** [comment]
Sweet, i will try to fix the issue with the "Waning gibbous" moon phase.

**Comment by Jason-c-o** [comment]
Except now I've also found out it makes it harder to access the name. You can't simply
```
print(phase)
```
You have to include the number. So in order to print the name, you have to revert to a large _if_ once more:
```
if phase[8] then
   print(phase[8])
elseif phase[1] then
   print(phase[1])
elseif ... -- All other conditions
end
```
It would definitely be much easier if the output was {NUM, "STRING"} rather than { [NUM] = "STRING" }. As it is, you already have to know which phase it is to print the name of the phase. Workable, but awkward.

**Comment by Seniorendi** [comment]
You can now use "getMoonName()" for the name and "getMoonId()". If you have any suggestions, just tell me.
