### ISSUE TITLE
Create integration overrides existings functions of Basin

### ISSUE THREAD

**Issue by cyb0124** [Seniorendi/AdvancedPeripherals#365]
### Describe

The Basin block from Crate originally has functions such as `pushItems` and `pullItems` from CC:T's generic peripheral APIs.  AdvancedPeripherals' integration removed those functions.

Implementing the `GenericSource` interface instead of `IPeripheral` should fix this, but I'm not sure if it's easy to make the change under the mod's architecture. [Here](https://github.com/cc-tweaked/CC-Tweaked/issues/1124#issuecomment-1172856669) is a similar issue & solution for a different mod.

### Steps to reproduce

1. Place a computer next to a Create Basin
2. List the functions of the Basin wrapped as peripheral.
3. Functions such as `pushItems` no longer exists if AdvancedPeripherals is installed.

### Multiplayer?

Yes

### Version

1.18.2-0.7.19r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.84

**Comment by SirEndii** [comment]
I reached out to the cc maintainer and this is sadly currently not possible.
https://github.com/cc-tweaked/CC-Tweaked/discussions/1242
