### ISSUE TITLE
The mod seems to not find a mod, it doesn't say what it is

### ISSUE THREAD

**Issue by cyberlong** [Seniorendi/AdvancedPeripherals#366]
### Describe

![image](https://user-images.githubusercontent.com/53883240/201543454-d5aab793-0c68-4378-86c7-e161a4f04d2f.png)
as you can see, cc:tweaked is installed and curios is there too, but MC says that there are mods that are not found. 

### Steps to reproduce

just install the mods and run the game

### Multiplayer?

No

### Version

1.19.2-0.7.21b (Latest 1.19)

### Minecraft, Forge and maybe other related mods versions

Forge 43.1.52 Version1.19.2

**Comment by SirEndii** [comment]
This message usually tells you, that the jar should contain a mod which does not exist.
Like "The jar should contain a mod called `advancedpeipherals` but there isn't any"

Could you try to install the mod again? I can't reproduce this with the curseforge version nor with the dev version
