### ISSUE TITLE
`rsBridge.importItemFromPeripheral(` dupe glitch

### ISSUE THREAD

**Issue by Quezler** [Seniorendi/AdvancedPeripherals#371]
### Describe

I was trying to write a script that can determine if an item had EMC (by trying to place it into an energy condenser, if it fails it has no emc)

Inserting it works fine, but if you try to take it back out you'll run into the dupe without even trying.

Apparently while it is not "locked" to an item all automated extraction fails (save for player gui or breaking), even the generic inventory interface can't.

However, importItemFromPeripheral will still happily import the item, but it doesn't lower/remove the stack from the chest.

### Steps to reproduce

computer, controller, grid, disk drive with a drive, bridge, modem(s) & condenser:

```
local bridge = peripheral.find('rsBridge')
local condenser = peripheral.find('projecte:condenser_mk1')

for slot, item in pairs(condenser.list()) do
  print(textutils.serialize(item))
  print(secondary.importItemFromPeripheral(item, peripheral.getName(condenser))) -- doesn't return 0
end
```

### Multiplayer?

Yes

### Version

1.18.2-0.7.20r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

FTB Stoneblock 3 1.3.0

**Comment by SirEndii** [comment]
Currently working on refining that!
Every item transferring related block now uses the same system.
Adding new filters and eliminating bugs.

This is the video I posted on discord

https://user-images.githubusercontent.com/67484093/216741802-0bac4d98-131b-419b-9093-44c4d45fe80a.mp4
