### ISSUE TITLE
creative mode idea / command block idea

### ISSUE THREAD

**Issue by awesomebossdj7** [Seniorendi/AdvancedPeripherals#372]
### Describe your idea

You should be able to attach a command block on the back of a pocket computer if command block peripheral is turned on in the cc tweaked config

### Describe alternatives you've considered if you've any

command block pocket computer 😳

**Comment by awesomebossdj7** [comment]
also turtles should be able to have a command block attach to them

**Comment by walksanatora** [comment]
Idea: suggest to CC: Tweaked not a addon

**Comment by SirEndii** [comment]
I recommend submitting this directly to CC:Tweaked

**Comment by awesomebossdj7** [comment]
the cc:tweaked dev, said not really any use, command pocket computer is useful, but they are too lazy to implement, would like if someone did it
