### ISSUE TITLE
Latest 1.19.2 Beta cause Crash on Launch with my Custom Modpack

### ISSUE THREAD

**Issue by ModernGamingWorld** [Seniorendi/AdvancedPeripherals#373]
### Describe

Update Advanced Peripherals to the latest 1.19.2 in my Custom Modpack, and boom instant crash to desktop

### Steps to reproduce

1. Updated Mod in my Custom Modpack
2. Launch
3. Crash to Desk after launch

### Multiplayer?

No

### Version

1.19.2-0.7.21b (Latest 1.19)

### Minecraft, Forge and maybe other related mods versions

43.1.57

### Crashlog/log

https://gist.github.com/ModernGamingWorld/fc8a823e278297a7e2cbaadab1e011d1

**Comment by SirEndii** [comment]
Could you try to remove `tipthescales`?
This does not seem to be a specific AP issue
