### ISSUE TITLE
Looking for non-existent version of Create

### ISSUE THREAD

**Issue by LaPerpo** [Seniorendi/AdvancedPeripherals#374]
### Describe

Advanced Peripherals won't allow Minecraft to run due to having an out of date version of Create. However, Create is at version 0.5.0f, but AP wants 0.5.0f-15, which does not exist.

### Steps to reproduce

1. Install most up to date version of Create and Advanced Peripherals.
2. Run Game.
3. Get the following message: "Mod advancedperipherals only supports create 0.5.0.f-15 or above
		Currently, create is 0.5.0.f"

![image](https://user-images.githubusercontent.com/47060071/205444229-01d5bf41-03b8-471c-949e-1fa74eedd447.png)

### Multiplayer?

No

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Forge 43.1.57, Minecraft 1.19.2, Advanced Peripherals 0.7.22b

### Crashlog/log

https://gist.github.com/LaPerpo/e9934d2e0465189e8e253d80ea6c940b

**Comment by SirEndii** [comment]
Heyo, I just uploaded(5 minutes ago) a fix for this issue (:
Do you want to test it with the now latest version from curseforge or modrinth?

https://www.curseforge.com/minecraft/mc-mods/advanced-peripherals/files/4131803
https://modrinth.com/mod/advancedperipherals/version/1.19.2-0.7.22b

**Comment by LaPerpo** [comment]
Success! All good now.
