### ISSUE TITLE
`inventoryManager.removeItemFromPlayer()` into a full storage results in duplication

### ISSUE THREAD

**Issue by illucc** [Seniorendi/AdvancedPeripherals#375]
### Describe

Trying to input items into a storage that is full results in a item duplication while in creative mode.

### Steps to reproduce

1. Use a Advanced Computer with a inventory manager that has a filled storage on top.
2.  Use this code
```
local manager = peripheral.find("inventoryManager")
if manager == nil then error("inventoryManager not found") end
while true do
    os.sleep(1)
    manager.removeItemFromPlayer("top", 64, 17)
end
```
3. Try repeatedly putting a singe item on the top right slot of your inventory.

### Multiplayer?

No

### Version

1.19.2-0.7.21b (Latest 1.19)

### Minecraft, Forge and maybe other related mods versions

Forge 43.1.1 Minecraft 1.19.2

### Screenshots or Videos

https://user-images.githubusercontent.com/70791404/205446727-bff1f4a4-8984-4844-a436-8755c8f995c4.mp4

**Comment by SirEndii** [comment]
Currently working on refining that!
Every item transferring related block now uses the same system.
Adding new filters and eliminating bugs.

This is the video I posted on discord

https://user-images.githubusercontent.com/67484093/216741802-0bac4d98-131b-419b-9093-44c4d45fe80a.mp4
