### ISSUE TITLE
[Feature] Tweak ME and RS Bridge retrieve command to deposit on wired network instead of directionaly.

### ISSUE THREAD

**Issue by Wojbie** [Seniorendi/AdvancedPeripherals#38]
I have noticed that ME and RS Bridges `retrive()` command is using cardinal directions for chest/target to retrieve items into.

I would like suggesting changing this logic from cardinal direction to one used by CC:T inventory system where one can target any chest/inventory on same wired network as ME Bridge is. 

Basically CC:T implementation allows to move items along the wired network between valid inventories as long as they are on same wired network. See: https://tweaked.cc/generic_peripheral/inventory.html for how it is implemented.

Example: `chest.pushItems("minecraft_chest_5", 4)` moves items from one chest to another.
With suggested change `retrieve("minecraft:stone", 64, "minecraft_chest_5")` would pull items from ME/RS system into the `"minecraft_chest_5"` on the wired network ME/RS Bridge is on.

**Reasoning**
In my opinion it would make it more consistent with CC:T way of transmitting items and extend it.
Additionally it would allow to simplify depositing items directly into target point on wired network instead of retrieving to sidechest and then pushing from that chest along wired network to target.

**Comment by Seniorendi** [comment]
Added in commit https://github.com/Seniorendi/AdvancedPeripherals/commit/9628591f693fc96ae4cc755e3b686ddbadec1e88
