### ISSUE TITLE
Crash at game start

### ISSUE THREAD

**Issue by vladislemon** [Seniorendi/AdvancedPeripherals#388]
### Describe

After I did update mods and forge in modpack, Advanced Peripherals start causing game crash at launch.
I do not have Refined Storage in pack.
Advanced Peripherals version = 1.18.2-0.7.21r

### Steps to reproduce

1. Run game with Advanced Peripherals on forge 40.1.86 without Refined Storage
2. See crash log

### Multiplayer?

No

### Version

1.18.2-0.7.21r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.86 Minecraft 1.18.2

### Crashlog/log

https://mclo.gs/Opj42qe

**Comment by SirEndii** [comment]
I re-uploaded the 0.7.21r file with the fix https://github.com/SirEndii/AdvancedPeripherals/commit/77e993fd5720401cc8e7d75de0d1fa90c755f297
 
 Should be available in some minutes: https://www.curseforge.com/minecraft/mc-mods/advanced-peripherals/files/4192726
