### ISSUE TITLE
Item clone with Create mechanical crafter and AE2 or RF

### ISSUE THREAD

**Issue by zyxkad** [Seniorendi/AdvancedPeripherals#393]
### Describe

You can clone items (without NBT data) use [Create mod](https://github.com/Creators-of-Create/Create/) and [AE2](https://appliedenergistics.github.io/) or [Refined Storage](https://www.curseforge.com/minecraft/mc-mods/refined-storage)

### Steps to reproduce

1. make a create mechanical crafter, a AE2 (or RS) system with a specific bridge, a computer and a wired modem

2. make a structure like this image
    <img width="1624" alt="Screen Shot 2023-01-05 at 1 17 46 AM" src="https://user-images.githubusercontent.com/91082411/210733365-3008b565-200a-4950-a889-91e08a548fc7.png">

4. put the item you want clone into the mechanical crafter

5. run the program <https://pastebin.com/6J5CDL7B>

6. you will receive an item in your storage, but the item in the mechanical craft will still be keep.

### Multiplayer?

Yes

### Version

1.19.2-0.7.22b (Latest 1.19)

### Minecraft, Forge and maybe other related mods versions

1.19.2

### Screenshots or Videos

https://drive.google.com/file/d/1EIgbUC9_BrsymK8B-hYY0BluYOU8phnC/view?usp=share_link

### Crashlog/log

N/A

**Comment by SirEndii** [comment]
Re-Open until release
