### ISSUE TITLE
support ignoring nbt data for `rsStorage.exportItem` and `rsStorage.exportItemToPeripheral`

### ISSUE THREAD

**Issue by Frefreak** [Seniorendi/AdvancedPeripherals#397]
### Describe your idea

Sometimes user may want to extract an item as long as it satisfy the name without considering its nbt data (so do not need to get a hash or find its json/tag string).

`INetwork.extractItem` has a `flag` field, but I see now we are calling it just with flag = 1 which is not configurable.

https://github.com/SirEndii/AdvancedPeripherals/blob/f1b44b0933cce3a333adedc93e137a1b1c5901ef/src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/peripheral/RsBridgePeripheral.java#L159

https://github.com/refinedmods/refinedstorage/blob/99a671223de8791ff81d334e8b142bba5a702789/src/main/java/com/refinedmods/refinedstorage/api/network/INetwork.java#L127-L137

https://github.com/refinedmods/refinedstorage/blob/99a671223de8791ff81d334e8b142bba5a702789/src/main/java/com/refinedmods/refinedstorage/api/util/IComparer.java#L11-L13

(embedded snippet from other repo doesn't work?)

Better yet, support only get item through tag without even need to specify the name (it seems currently it uses the name to get an item, then an ItemStack so I'm not sure if this is possible though. Support ignoring nbt is enough for my use case)

### Describe alternatives you've considered if you've any

How about supporting field like `ignoreNBT` in passed in table, then handle it in `getItemStackRS` (so no need to set nbt using tag/json/nbt) and `INetwork.extractItem`

### Additional context

I'm automating the extreme crafting whose recipes are converted from kubejs files. In lua script during crafting I need to export the item from rs network to the mechanical crafter. A few armor/weapon recipes seems to have item with nbt data as ingredients. (using `listItems` to filter the item first is a possible way, but this should still be a useful feature)

**Comment by SirEndii** [comment]
Currently working on refining that!
Every item transferring related block now uses the same system.
Adding new filters and eliminating bugs.

This is the video I posted on discord

https://user-images.githubusercontent.com/67484093/216741802-0bac4d98-131b-419b-9093-44c4d45fe80a.mp4
