### ISSUE TITLE
Create basin integration `getInventory()` returns multiple values instead of a table of items

### ISSUE THREAD

**Issue by l3dotdev** [Seniorendi/AdvancedPeripherals#398]
### Describe

The getInventory() method in the basin integration for Create returns list of items in the basin as a lua multi return: 1, 2, 3, ... etc instead of a table/list form {1, 2, 3, 4, ...}.

### Steps to reproduce

1. Connect a basin to a computer network
2. Get basin with peripheral.*
3. Call `getInventory()` and print out the result
4. See that it returns multiple values

### Multiplayer?

No

### Version

1.18.2-0.7.19r

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.76
Create 0.5.0.e

**Comment by SirEndii** [comment]
Re-Open until release
