### ISSUE TITLE
US lozalization issue on 1.18.2 (mod version 0.7.22)

### ISSUE THREAD

**Issue by Ithko** [Seniorendi/AdvancedPeripherals#399]
### Describe

Everything is missing their names and displays translation key instead of localized name in English (US)

I think the issue may be caused by uppercase spelling of US in name of en_US.json file (previous versions had it spelled lowercase).
Other languages including English (UK) work fine.

### Steps to reproduce

Set the English (US) language

### Multiplayer?

No

### Version

1.18.2-0.7.21r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.2.0 Minecraft 1.18.2

**Comment by SirEndii** [comment]
Fixed in 0.7.23r
