### ISSUE TITLE
[Feature] Get item details from an ME system

### ISSUE THREAD

**Issue by sselbach** [Seniorendi/AdvancedPeripherals#40]
**Describe your feature idea**
Extend the functionality of the ME Bridge such that it is possible to

1.  get a list of all available items in a network
2. get details for a specific item type (like number of stored items, damage values etc.)

**Additional context**
This used to be possible in OpenPeripherals and gave rise to some very useful ME related scripts like this defragmentation setup:
[setup description](https://imgur.com/gallery/bIAE9), [script](https://pastebin.com/cb9HTEXM).

Relevant OpenPeriperhals API documentation: [here](http://www.admalledd.com/mc/mod/openperipheral_docs.xhtml#adapt.openperipheral.integration.appeng.AdapterNetwork)

**Comment by Seniorendi** [comment]
There is already a listItems() function(see [docs](https://docs.srendi.de/Peripherals/mebridge/)). But sure, I will add a function to get more details about one Item.

**Comment by Seniorendi** [comment]
Added in 0.4.5b
