### ISSUE TITLE
Unable to right click blocks to open their interface in version 0.7.22r

### ISSUE THREAD

**Issue by Sh1mz** [Seniorendi/AdvancedPeripherals#400]
### Describe

In version 0.7.22r, I'm unable to right click blocks such as the Inventory Manager to open their interface.

### Steps to reproduce

Attempt to open a block's interface by right clicking it

### Multiplayer?

No

### Version

1.18.2-0.7.22r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.2.0

**Comment by SirEndii** [comment]
Fixed in 0.7.23r
