### ISSUE TITLE
Chat Box only sends 1 message at a time

### ISSUE THREAD

**Issue by l3dotdev** [Seniorendi/AdvancedPeripherals#403]
### Describe

Running multiple `sendMessage` calls one after another only results in the first message being sent into the chat.

### Steps to reproduce

1. Place computer with a chat box peripheral
2. Run code like below:
```lua
local chatBox = peripheral.find("chatBox")

chatbox.sendMessage("Hello world!")
chatbox.sendMessage("I am dave", "Dave")
```
3. See that only "Hello world!" appears in chat

### Multiplayer?

No

### Version

1.18.2-0.7.22r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.1.76 Minecraft 1.18.2

**Comment by SirEndii** [comment]
If you want to send a message to a player, you need to use `sendMessageToPlayer`

**Comment by l3dotdev** [comment]
I know that, the issue is that 2 or more `sendMessage` one after another (like above) doesn't work. Only the first message is sent to chat, the second is ignored.

Expected:
```
[AP] Hello world!
[Dave] I am dave
```

Reality:
```
[AP] Hello world!
```

**Comment by SirEndii** [comment]
Oh sorry, my fault. I thought Dave is a player, I forgot that the prefix argument exists

**Comment by SirEndii** [comment]
Does the second attempt return anything? The method returns either true or false with a error message

**Comment by SirEdvin** [comment]
It should return cooldown notification, because AP have cooldowns for sending chat messages.

**Comment by SirEndii** [comment]
Thank you edvin
I completely forget that

**Comment by l3dotdev** [comment]
Ah awesome! I'm actually in the middle of overhauling the AP docs for you so I'll make sure to add this to them.

**Comment by SirEndii** [comment]
That sounds interesting
