### ISSUE TITLE
Inventory Manager removeItemFromPlayer ignoring item string

### ISSUE THREAD

**Issue by IvoLeal72** [Seniorendi/AdvancedPeripherals#406]
### Describe

When the removeItemFromPlayer is called with (dir, qtt, -1, 'minecraft:stick') it sucks items from player inventory that are not sticks 

### Steps to reproduce

put sticks in inventory
run command
check inventroy

### Multiplayer?

Yes

### Version

1.19.2-0.7.21b

### Minecraft, Forge and maybe other related mods versions

Forge 43.1.47 Minecraft 1.19.2 CCTweaked 1.101.1

**Comment by SirEndii** [comment]
Currently working on refining that!
Every item transferring related block now uses the same system.
Adding new filters and eliminating bugs.

This is the video I posted on discord

https://user-images.githubusercontent.com/67484093/216741802-0bac4d98-131b-419b-9093-44c4d45fe80a.mp4
