### ISSUE TITLE
[Issue] Environment Detector causes game crash when placed by turtle.

### ISSUE THREAD

**Issue by OneTwoMint** [Seniorendi/AdvancedPeripherals#41]
**Describe**
When an environment detector is placed by a turtle, the whole game crashes.

**Reproduce**
1.Enter world.
2.Place turtle.
3.Give environment detector to turtle.
4.Enter the lua prompt.
5.Have turtle place the environment detector.

**Versions:**

- Forge version: 36.0.22
- AdvancedPeripherals version: 0.3.9b

**Crashlog/log (Use hasteb.in hasteb.in to upload your crashlog/log)**
https://paste.gg/p/anonymous/b32627c0af154ceab55cac65994f5307

**Comment by Seniorendi** [comment]
Fixed in 0.3.10b
