### ISSUE TITLE
Botania flower integration completely non functional

### ISSUE THREAD

**Issue by l3dotdev** [Seniorendi/AdvancedPeripherals#410]
### Describe

Botania flowers when placed next to a computer or a modem do not get detected as valid peripherals.

### Steps to reproduce

1. Place a computer and botania flower adjacent to each other.
2. Go into computer and run `peripheral.getNames()` or try to `wrap` the flower
3. See that nil or an empty table is returned

---

1. Place a modem and botania flower adjacent to each other.
2. Click on the modem to connect neighbours to the network
3. See that the modem connects nothing

### Multiplayer?

No

### Version

1.18.2-0.7.22r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge 40.2.0 Botania 1.18.2-435

**Comment by SirEndii** [comment]
![image](https://user-images.githubusercontent.com/67484093/217845393-35bf4ff7-828d-4b05-b26f-7889a47e8990.png)

Can't reproduce that with 1.18.2-0.7.22r and botania 435
