### ISSUE TITLE
[v0.7.25r] RS Bridge Method `craftItem` Not Crafting Lava Bucket

### ISSUE THREAD

**Issue by Peekofwar** [Seniorendi/AdvancedPeripherals#412]
### Describe

In the previous version, my RS stock manager was able to queue items to be crafted (although the `getItem` method was bugged in that version so it would actually endlessly queue items), however in this version, while I'm able to fetch information about the items, I'm unable to craft items through the peripheral. 

Despite being able to manually queue `minecraft:lava_bucket` in the RS system directly, I am unable to do so from the RS bridge peripheral. The function simply returns `false` every time I try to queue one. Furthermore, the `getItem` function indicates that the item is not craftable. 

![image](https://user-images.githubusercontent.com/10189526/218333833-773cde1e-ede1-4342-8236-8bc90b004cf2.png)
![image](https://user-images.githubusercontent.com/10189526/218333857-72181215-31ca-42a0-b08a-05e58441580b.png)
![image](https://user-images.githubusercontent.com/10189526/218333871-a26a6e86-6785-4adc-a4af-9f204d60319c.png)

Strangely, I was able to craft `mekanism:basic_universal_cable` for some reason... as well as `minecraft:stone`
![image](https://user-images.githubusercontent.com/10189526/218333984-a025a409-66a4-4904-b975-27980cb14131.png)

Strangely, other items are also not considered craftable for some reason... 
![image](https://user-images.githubusercontent.com/10189526/218334119-7a5cb2f3-d935-47e0-8a33-6c4a876ad565.png)

I'm failing to pick up a pattern here. Strangely, after changing literally nothing, the program suddenly queued `mekanism:enriched_redstone` 
![image](https://user-images.githubusercontent.com/10189526/218334179-d15b609f-1216-42cc-8203-3291de9d047f.png)

I'm wondering if it's related to the pattern being in a crafter that's attached to a `mekanism:advanced_fluid_tank`

### Steps to reproduce

1. Attach a crafter to a `mekanism:advanced_fluid_tank`
2. Insert a recipe that calls for an `minecraft:iron_bucket` and 1 B of lava
3. Attempt to craft through the RS bridge
4. Attempt to craft directly in the system if it's not working in the bridge

### Multiplayer?

Yes

### Version

1.18.2-0.7.25r (Latest 1.18)

### Minecraft, Forge and maybe other related mods versions

Forge v40.1.92
Computercraft: Tweaked v1.101.0
Mekanism v10.2.5.465

**Comment by SirEndii** [comment]
![image](https://user-images.githubusercontent.com/67484093/218334642-576b250a-ad9c-40d9-92aa-206eaf3e170a.png)

You forgot the `minecraft:` at the name
`minecraft:lava_bucket`
Does it return `isCraftable true` if you fix that?

**Comment by Peekofwar** [comment]
No, I don't believe the `minecraft:` was missing at any point. Neither in the program or in my testing. I did run a test without the `minecraft:` to see what it did.

This is from my program's config file (which I have not modified since December 12th of last year):
![image](https://user-images.githubusercontent.com/10189526/218335663-95296e4e-7ed2-4996-bd23-9af89ad42063.png)

Re-ran that Lua command with `minecraft:` and it returns the same thing:
![image](https://user-images.githubusercontent.com/10189526/218335759-f46c9d0e-1933-4b62-a257-bf7edffd96ad.png)

If your curious about my program:
```lua
local item_list_path = "/.program_data/rs_stock_manager/stocklist.lua"

local rs_device = "right" -- todo: make this a config option

local version = "1.0.2"

local item_list = {}
local load_item_list; function load_item_list(forceedit,forcenew)
	if fs.exists(item_list_path) and not forcenew then
		local file = fs.open(item_list_path,"r")
		item_list = textutils.unserialise(file.readAll())
		file.close()
		if type(item_list) == "nil" then
			load_item_list(false,true)
		end
		--require("cc.pretty").pretty_print(item_list)
	else
		print("Generating new list...")
		sleep(2)
		local file = fs.open(item_list_path,"w")
		file.writeLine("--[[")
		file.writeLine("  RS Stock Manager Item List")
		file.writeLine("")
		file.writeLine("  format:")
		file.writeLine("  {name = \"mod_name:item_name\", quantity = number},")
		file.writeLine("  example:")
		file.writeLine("  {name = \"mekanism:enriched_redstone\", quantity = 16,},")
		file.writeLine("]]")
		file.writeLine("")
		file.writeLine("{")
		file.writeLine("  ")
		file.writeLine("}")
		file.close()
		shell.run("edit "..item_list_path)
		load_item_list()
	end
end
load_item_list()
local function main()
	local isError = false
	local isPWRError = false
	local rs = peripheral.wrap(rs_device)
	print("RS Stock Manager running...")
	print("Version: "..version)
	while true do
		if peripheral.isPresent(rs_device) then
			if rs.getEnergyStorage() > 0 then
				if isPWRError then isPWRError = false print("RS system power restored.") end
				if isError then print("RS Bridge online!") isError = false end
				if #item_list < 1 then error("Item list is empty!",0) end
				for i=1, #item_list do
					if item_list[i] then
						local item = item_list[i].name
						local minimal = item_list[i].quantity
						local data = rs.getItem({name=item})
						local quantity = data and data.amount or 0
						local required = minimal - quantity
						--print(item,minimal,quantity)
						if not rs.isItemCrafting(item) then
							if rs.isItemCraftable({name=item}) then
								if quantity < minimal then
									local result = rs.craftItem({name=item,count=required})
									if result then
										item_list[i].isError = false
										print("Queueing "..required.." "..item)
									elseif not item_list[i].isError then
										item_list[i].isError = true
										printError("Cannot queue "..required.." "..item)
									end
								elseif item_list[i].isError == true then
									item_list[i].isError = false
								end
							else
								printError("Pattern missing for "..item)
								table.remove(item_list,i)
							end
						end
					end
				end
			else
				if not isPWRError then printError("/// RS SYSTEM POWER FAILURE! ///") end
				isPWRError = true
			end
		elseif not isError then
			isError = true
			printError("RS Bridge device is offline!")
		end
		sleep(2.5)
	end
end
main()
```

Also, this returns true... 
![image](https://user-images.githubusercontent.com/10189526/218336138-23f836fe-6683-4bb1-9f36-f16afa28ac06.png)

**Comment by Peekofwar** [comment]
https://user-images.githubusercontent.com/10189526/218336631-159c7179-0d3c-48f9-ac96-8d800b10f9cb.mp4

To clarify, as far as I know, this was working properly in 19r before I updated.

**Comment by SirEndii** [comment]
This is weird
Maybe some issue with comparing the stacks on the rs side

I'll work on that today!

**Comment by SirEndii** [comment]
[AdvancedPeripherals-0.7.26r.zip](https://github.com/SirEndii/AdvancedPeripherals/files/10720229/AdvancedPeripherals-0.7.26r.zip)

Could you install this version and enable debug mode in the config file `config/Advancedperipherals/general.toml`?
This should print some information about the craft state into the console when you run `craftItem`

Unzip the file before using it

**Comment by Peekofwar** [comment]
This is it trying to queue lava buckets:
```
[12:55:16] [Server thread/WARN] [Advanced Peripherals/]: [DEBUG] Schedule chunk manager cleanup
[12:55:18] [Server thread/INFO] [Advanced Peripherals/]: [DEBUG] Crafting Result of 'minecraft:air':NO_PATTERN
[12:55:21] [Server thread/INFO] [Advanced Peripherals/]: [DEBUG] Crafting Result of 'mekanism:enriched_carbon':OK
[12:55:22] [Server thread/INFO] [Advanced Peripherals/]: [DEBUG] Crafting Result of 'minecraft:air':NO_PATTERN
```
I'm recording as well... Ran across an anomaly where it temporarily stopped being able to queue carbon...

[latest.log.txt](https://github.com/SirEndii/AdvancedPeripherals/files/10724949/latest.log.txt)

https://youtu.be/PApgLx95doI (video processing...)

**Comment by SirEndii** [comment]
```
[12:55:18] [Server thread/INFO] [Advanced Peripherals/]: [DEBUG] Crafting Result of 'minecraft:air':NO_PATTERN
[12:55:21] [Server thread/INFO] [Advanced Peripherals/]: [DEBUG] Crafting Result of 'mekanism:enriched_carbon':OK
[12:55:22] [Server thread/INFO] [Advanced Peripherals/]: [DEBUG] Crafting Result of 'minecraft:air':NO_PATTERN```

I guess the first and the third are lava buckets?

**Comment by Peekofwar** [comment]
Correct.
However. during my testing, I encountered a temporary anomaly where enriched carbon stopped queueing despite having sufficient resources.

**Comment by Peekofwar** [comment]
It stopped queueing `mekanism:enriched_carbon` again... 
![image](https://user-images.githubusercontent.com/10189526/218538186-d79ce5ec-372c-437e-ad27-f3841161ebda.png)

**Comment by Peekofwar** [comment]
https://youtu.be/PApgLx95doI Video has finished processing and can now be viewed properly

**Comment by SirEndii** [comment]
Found the issue.
If the item is not in the system, it can't be crafted

**Comment by Peekofwar** [comment]
I noticed it started crafting enriched carbon after I manually queued up a bunch... Then after a while it stopped. That does line up with what I'm seeing.

**Comment by SirEndii** [comment]
[AdvancedPeripherals-0.7.26r.zip](https://github.com/SirEndii/AdvancedPeripherals/files/10730673/AdvancedPeripherals-0.7.26r.zip)


This file contains the fix if you want to test it
I'll update today or tomorrow

Unzip the file before using it
