### ISSUE TITLE
ColonyIntegrator getWorkOrderResources() missing value in output

### ISSUE THREAD

**Issue by DreadedEntity** [Seniorendi/AdvancedPeripherals#414]
### Describe

Documentation says that the table returned is a list of tables with the following properties:
- item
- displayName
- status
- needed
- available
- delivering

However .item does not exist in the tables and always returns nil, the other properties do exist for each item

### Steps to reproduce

1. Create a MineColony colony
2. Start a builder's hut
3. Set down a CC computer and colony integrator next to it
4. Run the following code and observe the output:
`colony = peripheral.find("colonyIntegrator")
for workOrderIndex, workOrder in pairs(colony.getWorkOrders()) do
    resources = colony.getWorkOrderResources(workOrder.id)
    if resources ~= nil then
        for resourceIndex, resource in pairs(resources) do
            for key, value in pairs(resource) do
                print(key, value)
            end
            sleep (2)
        end
    end
end`

### Multiplayer?

Yes

### Version

1.19.2-0.7.22b

### Minecraft, Forge and maybe other related mods versions

Forge 43.2.3 Minecraft 1.19.2

**Comment by SirEndii** [comment]
This got fixed in 0.7.23b
