### ISSUE TITLE
[Issue] Exporting items with nbt data not possible with me-bridge

### ISSUE THREAD

**Issue by LuckyTeran** [Seniorendi/AdvancedPeripherals#42]
Minecraft version: 1.16.5
Forge version: 36.0.42
AdvancedPeripherals version: 0.3.10b

I tried to export a enchanted book with a me-bridge into a chest.
'listItems()' shows:
`{
    {
        amount = 1,
        displayName = "Enchanted Book",
        name = "minecraft:enchanted_book",
        nbt = "{StoredEnchantments:[{lvl:1s,id:\"minecraft:mending\"}]}"
    }
}`

exporting with 'exportItem("minecraft:enchanted_book",1,"down")' gives the following error:
`Item minecraft:enchanted_book does not exist in the ME system or the system is offline`

I can export other items with the same setup no problem. I also have problems with other items and they all have in common that they have nbt data and AE2 lists them as different items with the same name.

Other mods use some kind of hash over the nbt data do differentiate between those items and sometimes give the option to ignore nbt data completely. For example [here](https://github.com/uecasm/rs4cc/wiki/Applied-Energistics-2#ae2extractitemitem-count-direction), [here](https://github.com/uecasm/rs4cc/wiki/Applied-Energistics-2#ae2getitemitem-comparenbt-evenifzero). One solution would be to use the normal name like now to extract items while ignoring the nbt data so already written programs don't break but use something like [this](https://github.com/uecasm/rs4cc/wiki/Applied-Energistics-2#item-descriptions) to extract specific items. To use this 'listItems()' needs an entry with the hash for every item in the system.

**Comment by Seniorendi** [comment]
Added in https://github.com/Seniorendi/AdvancedPeripherals/commit/eaaeb28c69f57808cfe647610804261c4fd824c1 . I will upload 0.4b tomorrow, I need to create the documentation.

**Comment by iammael** [comment]
It seems to still not be working for me on version 0.4.3.1b.

I made a quick script to sort items for my RS system. It works with cables for examples but won't work for any armor piece or tools.

Haven't tested with an AE system.

**Comment by Seniorendi** [comment]
Could you show me your script?

**Comment by iammael** [comment]
Sure thing: https://pastebin.com/KW13d76n

It's a bit dirty atm but the call to exportItem is made line 21. I also tested exportItemToChest with the same results.
