### ISSUE TITLE
meBridge.exportItem(item: table, direction: string) returns 0 NO_VALID_NBT

### ISSUE THREAD

**Issue by TrickShotMLG02** [Seniorendi/AdvancedPeripherals#424]
### Describe

I am using v0.7.24b of OpenPeripherals on Forge 1.19.2-43.2.6. In addition i have ae2 v12.9.2 installed.
with the older version of OP (v0.7.22b) the script below worked fine, but now i get some weird errors when i try to export an item from the me system into a chest above the me bridge. I am able to see get the item name ect, but i cant export it. I have never seen the error `0 NO_VALID_NBT` before. Also note, that no items are added to the me while running the code.

There is also no error on the server console.

```
local ae2 = peripheral.find("meBridge")
local items = ae2.listItems()
print(#items)
for _, item in ipairs(items) do
  print(item.name)
  print(ae2.exportItem(item, "up"))
  os.sleep(0.5)
end
```

![image](https://user-images.githubusercontent.com/43967908/225382376-ac92a8f9-736f-49f5-b226-2ead8d0ca283.png)

![image](https://user-images.githubusercontent.com/43967908/225382917-b3aa89a1-065b-4aa9-84ea-22c809d99358.png)

![image](https://user-images.githubusercontent.com/43967908/225383033-41108fff-d8d4-4e7f-a7d0-1270d92de9af.png)

Anybody got an idea how to fix that?

### Steps to reproduce

Try exporting all items from a me-system by grabbing all items from meBridge and exporting them in a loop.

### Multiplayer?

Yes

### Version

1.19.2-0.7.24b (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

43.2.6

**Comment by SirEndii** [comment]
Similar issue to this → https://github.com/SirEndii/AdvancedPeripherals/issues/416

> So the thing is, the stacks returned from `listCraftableItems` can't be parsed by the filter. The `nbt` tag is not formerly formatted for that
> 
> ![image](https://user-images.githubusercontent.com/67484093/222529730-d5fe3ae0-bed9-43e6-86ee-6122bf8e495e.png)
> 
> What you could do is setting the `nbt` value to nil like stated here →
> 
> ![image](https://user-images.githubusercontent.com/67484093/222529799-7015add3-394d-41cc-a06a-d8c3f062de4f.png)
> 
> I was able to fix that by trying to parse a table if parsing a string does not work. However, I would still recommend setting the nbt value to nil in case something is off with the nbt values.
> 
> ![image](https://user-images.githubusercontent.com/67484093/222532248-e4b16128-c287-427c-8474-310e5a631aec.png)

**Comment by TrickShotMLG02** [comment]
I dont think it is the same problem, since i can‘t  specify any nbt data in the export Item method.

exportItem(item: table, direction: string) -> number, err: string

or am i wrong about this?

**Comment by SirEndii** [comment]
The `table` argument is a filter. The filter tries to parse the NBT value as a string (a value surrounded by ") 
But the `item` which is returned by `listItems` returns items with a nbt key as a table, not a string. The new update fixed that.

You can read about the new filter system here → https://docs.intelligence-modding.de/guides/filters/
And here → https://docs.intelligence-modding.de/changelogs/0.7.24r/#itemfluid-filter

**Comment by TrickShotMLG02** [comment]
where can i get the new update? i am unable to find a newer version of Advanced Peripherals for 1.19.2

**Comment by SirEndii** [comment]
This update isn't published yet
