### ISSUE TITLE
Outdated Patchouli book wiki links

### ISSUE THREAD

**Issue by volenko** [Seniorendi/AdvancedPeripherals#425]
### Describe

Outdated links to wiki
Links lead to [doc.srendi.de](url) instead of [docs.intelligence-modding.de](url)

### Steps to reproduce

Pre-req: patchouli mod installed
1. Open patchouli book in-game
2. Go to any page
3. Click on a wiki link
![image](https://user-images.githubusercontent.com/77839476/226147197-5a1a0db4-b52f-4904-bf2f-edfa5b8b7e3b.png)

### Multiplayer?

No

### Version

1.19.2-0.7.24b (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

Forge 43.2.7 Minecraft 1.19.2

**Comment by zyxkad** [comment]
@SirEndii 
0eee1b0 forgot <https://github.com/SirEndii/AdvancedPeripherals/tree/master/src/main/resources/data/advancedperipherals/patchouli_books/manual/book.json>
and
<https://github.com/SirEndii/AdvancedPeripherals/tree/master/src/main/resources/META-INF/mods.toml>
