### ISSUE TITLE
removeItemFromPlayer seems to ignore slots parameter

### ISSUE THREAD

**Issue by toastonrye** [Seniorendi/AdvancedPeripherals#428]
### Describe

Direwolf20 1.19.2 1v.7.0 modpack
AdvancedPeripherals-0.7.2.24b
cc-tweaked-1.19.2-1.101.2

https://pastebin.com/SHkMH2Gt
Lines 34 to 36 print correctly the right item name, count, slot

But when I use removeItemFromPlayer("back", item.count, item.slot) it seems to ignore the last parameter item.slot and starts at slot 0?

From the documentation page, removeItemFromPlayer(direction: string, count: number[, slot: number, item: string]) -> number
I think I am using it correctly? 

### Steps to reproduce

See code snippet from pastebin, above.

### Multiplayer?

Yes

### Version

1.19.2-0.7.24b

### Minecraft, Forge and maybe other related mods versions

Forge 1.19.2-43.2.6

**Comment by SirEndii** [comment]
Note that the slot in this method is the "toSlot" not the "fromSlot"
Could you try using the methods which are using the filters?
Should be `removeItemFromPlayerNBT("back", item.count, -1, {fromSlot=item.slot, count=item.count})`

**Comment by toastonrye** [comment]
Alright, that works perfect. Thank you so much!

**Comment by SirEndii** [comment]
> Alright, that works perfect. Thank you so much!

No problem, glad that it works
