### ISSUE TITLE
(ME Bridge) Cherry-Pick AE2 Things DISK Drive Support from 1.18 to 1.19.2/1.19.3

### ISSUE THREAD

**Issue by mpab1410** [Seniorendi/AdvancedPeripherals#429]
### Describe your idea

A few friends and I are currently doing a playthrough of ATM 8 with AE2 Things. We ultimately decided to use DISK Drives. We're wanting to write a script to essentially show live the percentage space used in our system. Unfortunately, we're not able to due to the DISK Drives not being detected.

After a glance, it looks like support got added in [1.18](https://github.com/SirEndii/AdvancedPeripherals/blob/d3da019161296308ef829bf31a0e844b8d629369/src/main/java/de/srendi/advancedperipherals/common/addons/appliedenergistics/AppEngApi.java#L407) but it didn't get cherry-picked into the 1.19.x versions. Is there a way this could be cherry-picked in?

**Comment by SirEndii** [comment]
AE2 Things does not seem to have a 1.19.2 version? https://www.curseforge.com/minecraft/mc-mods/ae2things/files/all
Is there another mod with these DISK drives?

**Comment by mpab1410** [comment]
The main mod is a Fabric mod though there is a Forge port which is in use and is updated to 1.19.2

https://beta.curseforge.com/minecraft/mc-mods/ae2-things-forge/files/4367610

**Comment by SirEndii** [comment]
I did not catch that, thanks

**Comment by SirEndii** [comment]
[AdvancedPeripherals-0.7.25r.zip](https://github.com/SirEndii/AdvancedPeripherals/files/11184397/AdvancedPeripherals-0.7.25r.zip)

If you want to test it, you're free to go.
Uploading it on the server only would be sufficient.
Unzip the file before using.

**Comment by mpab1410** [comment]
Looks like it's working now with that test jar, thanks for the quick response, appreciate it!

![image](https://user-images.githubusercontent.com/22943068/230748791-c85e91bd-5b98-40f4-9b23-5314011fa2a4.png)

**Comment by mpab1410** [comment]
@SirEndii Apologies for the ping/reopen, though I found another part that wasn't cherry-picked in: https://github.com/SirEndii/AdvancedPeripherals/blob/327960be1a064a6b1e0074e49f485334db4889c6/src/main/java/de/srendi/advancedperipherals/common/addons/appliedenergistics/AppEngApi.java#L337

Could you take a look and cherry-pick whenever you get a chance? Thank you!
