### ISSUE TITLE
[Feature] Listing tags of items 

### ISSUE THREAD

**Issue by LuckyTeran** [Seniorendi/AdvancedPeripherals#43]
Is it possible to add item tags to 'listItems()'? I'm writing an inventory system and would like to filter items with their tags. For example:
`{ { amount = 1, displayName = "Dirt", name = "minecraft:dirt", nbt = "{}", tags = { [1] = "minecraft:sometag" } } }`

I think that would be a nice feature to quickly gather information about an item.

**Comment by Seniorendi** [comment]
Sure, i will add this in the near future.

**Comment by Seniorendi** [comment]
Added in 0.4a
