### ISSUE TITLE
Add meBridge.craftFluid

### ISSUE THREAD

**Issue by abesto** [Seniorendi/AdvancedPeripherals#430]
`meBridge.listCraftableFluid()` (side-note: note the missing plural) correctly returns craftable fluids in AE2/ME, but there's no way to actually queue them for crafting. `craftItem` returns `"ITEM_NOT_FOUND"`, which is probably correct. AFAICT from a skim of the code, the RS bridge has a `craftFluid` method; I hope adding that for the ME bridge would be easy-ish?

**Comment by SirEndii** [comment]
To be honest, I thought I added something like that
But thanks for the report
Probably the last Feature I'll add to 0.7

**Comment by abesto** [comment]
Confirmed this works on `1.19.3-0.7.27r`. Thank you!
