### ISSUE TITLE
[Feature Request] Let turtle can directly drop/export items into ME Bridge/RS Bridge

### ISSUE THREAD

**Issue by zyxkad** [Seniorendi/AdvancedPeripherals#431]
### Describe your idea

Now we should use `bridge.importItem(itemInfo, bridgeSide)` to let turtle import/export items, use `turtle.drop` will just create item entities. I want when turtle are using `turtle.drop` in front of a bridge, the items will be transform into the bridge

### Describe alternatives you've considered if you've any

I can use `bridge.importItem`, but it must know where is the bridge facing
Or I can build a chest, but it will use more space and an extra channel for ME

**Comment by SirEndii** [comment]
I would recommend putting the items into a chest connected to the bridge or drop the item into a hopper which could also be connected to the bridge
