### ISSUE TITLE
ME Bridge voids items if container will not accept them

### ISSUE THREAD

**Issue by estafeit** [Seniorendi/AdvancedPeripherals#433]
### Describe

Exporting to a limited container not accepting given item type reports success and **voids** items in the network.

I could reproduce this with a sophisticated storage limited barrel, locked or filled with other type of items, and with mekanism chemical injection chamber. Storage drawers will probably react the same way.

exportItem() and exportItemToPeripheral() reports no error, and removes given count of items from the network, but they obviously won't appear in the container.

```
local exported, error
exported, error = bridge.exportItemToPeripheral({name="minecraft:dirt", count=1}, "right")
if (not exported) or (exported == 0) then
	print(error)
else
	print("Successfully exported " .. exported .. " items")
end
```

### Steps to reproduce

1. Use a computer, ME Bridge and limited storage
2. Lock the storage on some random type of item, or fill it with it (let's say, stone)
3. use exportItem() or exportItemToPeripheral() to export dirt to that container
4. dirt disapears form ME network, but won't appear in container

### Multiplayer?

No

### Version

1.19.2-0.7.25r (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

Forge 43.2.6, Minecraft 1.19.2, modpack All The Mods 8

**Comment by SirEndii** [comment]
Could you test that with the latest 1.19.2 version?
https://www.curseforge.com/minecraft/mc-mods/advanced-peripherals/files/4490348

**Comment by estafeit** [comment]
Sadly, still the same behaviour with 0.7.26r

**Comment by estafeit** [comment]
As a sidenote, i checked with cc:tweaked inventory.pushItems().
It also has weird behaviour : it triggers no error, but do not destroys nor moves nothing.

**Comment by SirEndii** [comment]
[AdvancedPeripherals-0.7.26r.zip](https://github.com/SirEndii/AdvancedPeripherals/files/11237730/AdvancedPeripherals-0.7.26r.zip)
If you want, you can test the fix.
Unzip the file before using it.

**Comment by estafeit** [comment]
Works like a charm. Great job, fast too ! Thank you.

I stumbled upon this bug only by doing some tests. Meanwhile I discovered Chemical Injection Chamber doesn't expose a computercraft inventory, and the whole plan was to export directly to it. So much for my project.

Speaking of that. Don't you want to trigger an error when trying to push on a a block that is not a container ?

Anyways, issue is solved, thank you again !

**Comment by SirEndii** [comment]
> Speaking of that. Don't you want to trigger an error when trying to push on a a block that is not a container ?

I thought this is the case, oops
But that isn't something high priority now and will be improved in the next update

Speaking of next update - the version with the fix got released
