### ISSUE TITLE
Add `meBridge.isFluidCrafting`

### ISSUE THREAD

**Issue by abesto** [Seniorendi/AdvancedPeripherals#435]
### Describe your idea

Follow-up on #430, to the tune of `isItemCrafting`.

It's now possible to queue fluids for crafting - thank you! My use-case is (unsurprisingly) auto-crafting. The missing `isFluidCrafting` method means we can't skip submitting the crafting job if there's already a job in progress.

### Linked Issues

#430

**Comment by SirEndii** [comment]
[AdvancedPeripherals-1.19.2-0.7.29r.zip](https://github.com/SirEndii/AdvancedPeripherals/files/11984286/AdvancedPeripherals-1.19.2-0.7.29r.zip)


A bit late, but if you want, you can test them here. I Added a `isFluidCraftable` and `isFluidCrafting` function
unzip the file before using it
