### ISSUE TITLE
`InventoryManager.removeItemFromPlayer[NBT]` will return `nil` anyway.

### ISSUE THREAD

**Issue by zyxkad** [Seniorendi/AdvancedPeripherals#437]
### Describe

`removeItemFromPlayer` will always return nil for either action done or not
`removeItemFromPlayerNBT` will return always return `nil` when `item` is empty, and if `item` is not empty but not a exists id, it will return `0, "ITEM_NOT_FOUND"`

### Steps to reproduce

```lua
local iv = peripheral.find("inventoryManager")
assert(iv, "inventoryManager is not exists")

iv.removeItemFromPlayerNBT("left", 1, nil, {name="minecraft:dirt"}) -- will return nil
iv.removeItemFromPlayerNBT("left", 1, nil, {name="notexists:item"}) -- will return 0, "ITEM_NOT_FOUND"

iv.removeItemFromPlayer("left", 1, -1) -- will return nil
iv.removeItemFromPlayer("left", 1, 100) -- will return nil
```

### Multiplayer?

Yes

### Version

1.19.3-0.7.26r (Latest 1.19.3)

### Minecraft, Forge and maybe other related mods versions

Forge 43.2.8 Minecraft 1.19.2

**Comment by SirEndii** [comment]
That got fixed in the latest version

```
1.18.2-0.7.29r - 1.19.2-0.7.27r - 1.19.3-0.7.28r
```
