### ISSUE TITLE
[Feature] Function getName() for all peripherals to get anvil assigned name

### ISSUE THREAD

**Issue by LuckyTeran** [Seniorendi/AdvancedPeripherals#44]
Since it is possible to name blocks with the anvil it would be nice to have a function 'getName()' to get back the assigned name of a block.

This would make identifying different storage networks much easier if there are more then one connected to a computer/network without relying on the computercraft given names or other hacks to identify connected blocks.

**Comment by Seniorendi** [comment]
I will add getName() to my blocks, if you want to get the anvilname of chests,  create a Feature request at the [CC:T github page](https://github.com/SquidDev-CC/CC-Tweaked).

**Comment by Wojbie** [comment]
Related: https://github.com/SquidDev-CC/CC-Tweaked/issues/78
Related: https://github.com/SquidDev-CC/CC-Tweaked/issues/703

**Comment by Wojbie** [comment]
Also worth to note that for blocks to remember their anvil-name after placing they need to have special code added to them to handle it. In case of chests they gain additional nbt tag `CustomName`. Only blocks listed to have special interactions here: https://minecraft.gamepedia.com/Anvil#Renaming will remember they have anvil-name added. All other blocks forget it when they are placed. So while Seniorendi can add that functionality of remembering anvil-names to peripherals added by this mod it would be way more annoying (not impossible but really annoying) to add it to ones added by CC:T itself. If you want that or ability to get anvil-name of chest/hopper/others from generic inventory peripheral CC:T adds you need to ask for that on CC:T itself.

**Comment by LuckyTeran** [comment]
Only blocks of this mod are totally ok, never expected more than that when i asked for that feature.

**Comment by Seniorendi** [comment]
[advancedperipherals-0.3.10-DEVb.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/6056196/advancedperipherals-0.3.10-DEVb.zip)

I added the function getName() to every block, but you need to replace the blocks. You can test it, if you want.

**Comment by LuckyTeran** [comment]
Works great! But the name (and nbt tag) is lost when you pick up the block again.

**Comment by Seniorendi** [comment]
Added in 0.4a
