### ISSUE TITLE
[Feature Request] Wireless peripheral upgrade tool and/or wireless cable access point

### ISSUE THREAD

**Issue by zyxkad** [Seniorendi/AdvancedPeripherals#440]
### Describe your idea

Wireless peripheral upgrade tool: A tool that can connect peripheral to wireless modem, allow computer to control peripheral wirelessly.

Wireless cable access point: a block like wired modem block, but needn't cable to connect it. It's different from wireless modem since it can connect to the cable and peripheral, but wireless modem not.

**Comment by SirEndii** [comment]
That would involve too much work and wouldn't be possible with the api cc offers
I'm sorry but I'm closing this
