### ISSUE TITLE
ME Bridge causes java exception exportItemToPeripheral when item doesn't exist

### ISSUE THREAD

**Issue by mrlamb** [Seniorendi/AdvancedPeripherals#443]
### Describe

I have a simple setup: controller, terminal, chest, storage bus. Computer sits next to bridge with another chest to it's right.
Request to move an item that's not in the chest and I get the following:
![image](https://user-images.githubusercontent.com/11540846/234564500-4500fc35-d16e-4f71-b1c7-65b279e65e5a.png)

I also tried wrapping the target using a modem in another test and got a different java exception:
![image](https://user-images.githubusercontent.com/11540846/234567287-c8fd737b-754c-4a41-a3d2-8ec6213e8821.png)

A side effect of the first java exception is that my ME terminal no longer shows any items, though I can insert into it with no trouble. Subsequent calls to listItems returns an empty table. So realistically this could be a problem on AE2's side and not AP but I thought I'd start here.

### Steps to reproduce

Setup basic ME system as described above
use lua console to wrap the ME bridge and call the exportItemToPeripheral method on an item that doesn't exist in your storage.

For the second test I used wired modems to add an entangled block to a warehouse from minecolonies.
I apologize if this has been fixed as I appear to be on version 1.19.2 0.27.24b because that's what the direwolf20 1.19.2 pack is using atm (at least in their release version). I did try to look through the closed issues, but didn't see anything related to this exactly.

### Multiplayer?

Yes

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Forge 43.2.6

### Crashlog/log

https://pastebin.com/VJcKJbYt

**Comment by SirEndii** [comment]
I need to look into your first issue a bit deeper.
But the second thing is an issue on your end. If you want that the bridge can access peripherals in the network, you need to wrap the bridge via an modem so the bridge has a connection to the network where the target chest is also connected to

**Comment by mrlamb** [comment]
I forgot to capture the stack trace for the first exception so here it is:
https://pastebin.com/GnJ0EZLu

**Comment by mrlamb** [comment]
> I need to look into your first issue a bit deeper. But the second thing is an issue on your end. If you want that the bridge can access peripherals in the network, you need to wrap the bridge via an modem so the bridge has a connection to the network where the target chest is also connected to

Got it, think! The peripheral needs network access to the rest of the network, the computer doesn't act as a go between on those. I merely thought to try that setup because of another reported issue regarding the RS bridge and a warehouse block.

**Comment by mrlamb** [comment]
Interestingly this setup caused that same second error, but I'm not convinced I'm *not* just doing something wrong XD

![image](https://user-images.githubusercontent.com/11540846/234570514-f3811932-82a7-4783-ae28-9bf2671d5ce5.png)

**Comment by SirEndii** [comment]
Have you changed the way how you wrap it?
Should be something like `peripheral.wrap("rsBridge_1")` or `peripheral.find("rsBridge")`

**Comment by mrlamb** [comment]
Ah no I'll give that a try after work.

edit: I had a few minutes between meetings to get the peripherals wrapped like you suggested and this time I got the first exception as above, so got past the second issue altogether! Thanks for the help on that.

**Comment by mrlamb** [comment]
I tested the same concept with the RS bridge and a refined storage controller and external storage and everything worked fine so it does seem to be an AE2 only issue.

**Comment by SirEndii** [comment]
The first issue could be my fault. I'll check that next week.
I'll also add some better erro messages to prevent these exceptions

**Comment by SirEndii** [comment]
Forgot to close this
Fixed in the last versions of 1.18.2, 1.19.2 and 1.19.3
