### ISSUE TITLE
cardinal directions aren't working, contrary to the docs.

### ISSUE THREAD

**Issue by jebjordan** [Seniorendi/AdvancedPeripherals#444]
### Describe

Mods: ONLY CC:Tweaked and Advanced Peripherals.

The inventory manager does not currently allow cardinal directions. (even though supposedly it should? according to the docs at least)

Please fix.

example script:
`manager = peripheral.find("inventoryManager")
manager.addItemToPlayer("UP", 50, -1)`

Do correct me if I am doing something wrong here, but yeah it appears to not work.
This also means that the example script on the docs won't work. 
ALSO unrelated but the docs have the NBT version of the example in the non-nbt area and the non-nbt version in the nbt area.

### Steps to reproduce

1. get your CC setup. (put an inventory manager and such.)
2. Put a chest on top of the inventory manager,
3. put something in it
4. call `manager.addItemToPlayer("UP", 4, -1)`
5. It won't work because apparently the cardinal directions aren't enabled contrary to the docs.

### Multiplayer?

No

### Version

1.19.2-0.7.27r (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

Forge 43.2.8, Minecraft 1.19.2

**Comment by Einhornyordle** [comment]
While the documentation is indeed wrong, you can use the regular CC directions as stated in [the CC: Tweaked Docs](https://tweaked.cc/module/peripheral.html), they should work fine.

**Comment by jebjordan** [comment]
> While the documentation is indeed wrong, you can use the regular CC directions as stated in [the CC: Tweaked Docs](https://tweaked.cc/module/peripheral.html), they should work fine.

I know that the relative directions work. I was just reporting that the cardinal directions do not work when they supposedly should.

**Comment by zyxkad** [comment]
I fixed this in #452, hope SirEndii will merge it
