### ISSUE TITLE
[Feature] Energy meter

### ISSUE THREAD

**Issue by LuckyTeran** [Seniorendi/AdvancedPeripherals#45]
Since [this](https://www.curseforge.com/minecraft/mc-mods/energy-meters) pretty dead and no 1.16.x version in sight, a energy meter in this style would be a nice addition to AdvancedPheripherals. Just a simple block that gives you current throughput values and maybe separate input and output values.
I know about [the generic energy peripheral](https://tweaked.cc/generic_peripheral/energy_storage.html) and that the forge energy api is limited somehow. But maybe it is still possible? Just an idea.

**Comment by Seniorendi** [comment]
I already planned a block like this. I will add this after 0.4b.

**Comment by Seniorendi** [comment]
Added in 0.4.1b
