### ISSUE TITLE
Create tanks API that implement by CC:T is override by AdvancedPeripherals.

### ISSUE THREAD

**Issue by zyxkad** [Seniorendi/AdvancedPeripherals#455]
### Describe

The create fluid storage API that impl by CC:T is override by this mod <https://tweaked.cc/generic_peripheral/fluid_storage.html>

Rel Issue: <https://github.com/cc-tweaked/CC-Tweaked/issues/1435>

### Steps to reproduce

1. install CC:T and AdvancePeripherals with forge
2. place a computer and a create tank next to it
3. wrap the tank, there are no methods such as `pushFluid`.

### Multiplayer?

No

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Forge 43.2.8 Minecraft 1.19.2

### Screenshots or Videos

<img width="1168" alt="Screenshot 2023-05-09 at 12 51 11 PM" src="https://github.com/cc-tweaked/CC-Tweaked/assets/91082411/b3fb7a35-e164-4cb4-b49b-e338cb80062a">

**Comment by SirEndii** [comment]
There isn't something I can't do to fix this
I just add a peripheral provider and then add the peripheral to the block
I'll close this until there are some news in https://github.com/cc-tweaked/CC-Tweaked/issues/1435
