### ISSUE TITLE
Add more infos available for Me bridge

### ISSUE THREAD

**Issue by 1Euro7Cent** [Seniorendi/AdvancedPeripherals#458]
### Describe your idea

I thought of getting detailed infos for each CPU.
For example of how many are already crafted from requested. And how long it is already crafting it etc

### Additional context

Here is a screenshot to show that this already exists
![image](https://github.com/SirEndii/AdvancedPeripherals/assets/67194495/1408765c-317b-4da7-978e-7c3a2eb9b26f)

**Comment by SirEndii** [comment]
The bridge has a `craftingJob` field in the given table which contains the information you want

If you have another question, feel free to reopen
