### ISSUE TITLE
Distinction between Knight Archer and Druid

### ISSUE THREAD

**Issue by Zonk1987** [Seniorendi/AdvancedPeripherals#459]
### Describe your idea

It would be really nice if i can differentiate between the different military classes like in the Title.

At the moment there is only "guardtower" as a military class but there are Knight , Archer and Druid.

**Comment by SirEndii** [comment]
After some testing, I noticed that this already works

A citizen table has a key called `work`
In this table are two keys which are important for your request

First we have `type` which is the name of the building. Can be `guardtower`, `barrackstower` or any other name
And the `job` key which is the actual name of the job. Can be `knight`, `druid`, `archer` or something else for another job
