### ISSUE TITLE
[Issue] Config generates .bak copy every time the game starts up.

### ISSUE THREAD

**Issue by Gbergz** [Seniorendi/AdvancedPeripherals#46]
**Describe**
In newer versions of Forge the config file for Advanced Peripherals generates a new config with the file extension .bak each time the game starts.

**Reproduce**

1. Start the game.
2. A .bak config file generates.
3. Profit.

**Screenshot**
![image](https://user-images.githubusercontent.com/26634554/110474696-45fa6700-80e0-11eb-9a53-0dff884a3423.png)

**Versions:**
- Minecraft: ``1.16.5``
- Forge version: ``36.0.46``
- AdvancedPeripherals version: ``0.3.10b``

**-** Gbergz

**Comment by Seniorendi** [comment]
Hey, could you try this with the following Dev version: 
[advancedperipherals-0.4-DEVb.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/6109077/advancedperipherals-0.4-DEVb.zip)
(Unzip the file)

**Comment by Gbergz** [comment]
Hey just tried it. Seems to still generate a ``.bak`` file

![image](https://user-images.githubusercontent.com/26634554/110514800-f4fe6900-8107-11eb-949c-66e6e73df8d1.png)

**Comment by Seniorendi** [comment]
Tahnks, i will fix this in 0.4b

**Comment by Seniorendi** [comment]
Forge fixed some issues with configurations in 1.16.5-36.0.54. The version fixes the bug with the config.
