### ISSUE TITLE
The Patchouli guide book API documention links to an invalid domain

### ISSUE THREAD

**Issue by toastonrye** [Seniorendi/AdvancedPeripherals#461]
### Describe

The domain is for sale, link should be updated.
https://docs.srendi.de/metaphysics/weak_automata/

### Steps to reproduce

v0.7.27r
forge 43.2.11
MC 1.19.2

### Multiplayer?

No

### Version

1.19.2-0.7.27r (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

1.19.2-0.7.27r

**Comment by zyxkad** [comment]
Duplicated with #425
