### ISSUE TITLE
Error message after start game : "Advanced Peripheral has failed to load correctly" with Create mod

### ISSUE THREAD

**Issue by Axelouuu-dev** [Seniorendi/AdvancedPeripherals#463]
### Describe

Hi ! 

I report a crash who appears with the last version of Create mod. 
The crash message says : **Advanced Peripheral has failed to load correctly**

Create mod version :  0.5.1a

### Steps to reproduce

1) Install Advanced peripheral 0.7.29r and Create (0.5.1a) in 1.18.2 
2) Launch game

### Multiplayer?

No

### Version

1.18.2-0.7.29r (Latest 1.18.2)

### Minecraft, Forge and maybe other related mods versions

Forge 40.2.4 Minecraft 1.18.2

### Crashlog/log

https://gist.github.com/Axelouuu-dev/5690038c440407c289bfa59864b9af47

**Comment by SirEndii** [comment]
AP is not compatible with the new create version
You could downgrade create or wait until I fix this

**Comment by Axelouuu-dev** [comment]
Yes, it was why I report the crash, thanks :)

**Comment by SirEndii** [comment]
You can use this version until I release a fix to curseforge/modrinth
Unzip the file before using it

[AdvancedPeripherals-1.18.2-0.7.30r-Dev.zip](https://github.com/SirEndii/AdvancedPeripherals/files/11541516/AdvancedPeripherals-1.18.2-0.7.30r-Dev.zip)

**Comment by Axelouuu-dev** [comment]
> You can use this version until I release a fix to curseforge/modrinth
> Unzip the file before using it
> 
> [AdvancedPeripherals-1.18.2-0.7.30r-Dev.zip](https://github.com/SirEndii/AdvancedPeripherals/files/11541516/AdvancedPeripherals-1.18.2-0.7.30r-Dev.zip)
> 

Oh nice !

**Comment by falOn-Dev** [comment]
That jar still seems to not load with the same error on my end

**Comment by SirEndii** [comment]
Could you provide a log and which create version you are using

**Comment by RedStoner** [comment]
Same here with dev version. 
[crash-2023-05-25_23.03.00-fml.txt](https://github.com/SirEndii/AdvancedPeripherals/files/11571203/crash-2023-05-25_23.03.00-fml.txt)
Create version: 1.19.2-0.5.1.a

**Comment by SirEndii** [comment]
> Same here with dev version. [crash-2023-05-25_23.03.00-fml.txt](https://github.com/SirEndii/AdvancedPeripherals/files/11571203/crash-2023-05-25_23.03.00-fml.txt) Create version: 1.19.2-0.5.1.a

uhm you know that the version I provided is for 1.18?
Your pack runs on 1.19, but the jar you've installed is for 1.18

**Comment by SirEndii** [comment]
For 1.19
Unzip before using it
@Tatiman-Dev Maybe this helps you too

[AdvancedPeripherals-1.19.2-0.7.28r-Dev.zip](https://github.com/SirEndii/AdvancedPeripherals/files/11572523/AdvancedPeripherals-1.19.2-0.7.28r-Dev.zip)

**Comment by RedStoner** [comment]
Yeah, i overlooked that... Can confirm though, it did fix the issue. Mod loaded successfully. Thank you.

**Comment by DJj123dj** [comment]
@SirEndii When do you plan to publish a release with this bug fix? Because I'm using the mod on an Aternos server with my friends and it doesn't allow custom mod uploading, only mods on curseforge can be used.
