### ISSUE TITLE
Inventory manager causes items to stop stacking

### ISSUE THREAD

**Issue by 1Euro7Cent** [Seniorendi/AdvancedPeripherals#464]
### Describe

I have a computer that is supplying me constantly with items. One of witch are apples. Then I noticed that apples in my inventory and apples in the me system don't stack anymore. I looked into the item data and the mod appends "tag:{}" to the data

### Steps to reproduce

1. have an apple in the inventory.
2. have a cc computer and the inventory manager attached and linked
3. put apple in main hand and run this: `/data get entity @s SelectedItem` . See that no `tag:{}` is there 
4. call `manager.getItems()`
5. put apple in main hand and run this: `/data get entity @s SelectedItem`  see that `tag:{}` appeared.
6. after the `tag:{}` got added see that the apple doesn't stack anymore with fresh items from creative inventory

### Multiplayer?

Yes

### Version

1.19.2-0.7.27r (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

Forge 43.2.0; Minecraft 1.19.2

### Screenshots or Videos

![image](https://github.com/SirEndii/AdvancedPeripherals/assets/67194495/9b0bf574-7336-41e0-bee7-c7a43ab1929f)

**Comment by zyxkad** [comment]
Epic
