### ISSUE TITLE
Running with Create Mod (Create 1.18.2 v0.5.1b) causes a crash on launch

### ISSUE THREAD

**Issue by ajsnarr98** [Seniorendi/AdvancedPeripherals#465]
### Describe

Running forge with the newest version of the Create Mod (Create 1.18.2 v0.5.1b) and Advanced Peripherals installed causes Advanced Peripherals to crash when loading the minecraft instance.

This appears to be because of a reference to "com/simibubi/create/content/contraptions/processing/burner/BlazeBurnerTileEntity" which _seems_ to have been moved to "com/simibubi/create/content/processing/burner/..."

### Steps to reproduce

1. Create a forge instance with the most recent version of the Create Mod (Create 1.18.2 v0.5.1b) and most recent version of Advanced Peripherals
2. Launch the instance
3. See crash

### Multiplayer?

No

### Version

1.18.2-0.7.29r (Latest 1.18.2)

### Minecraft, Forge and maybe other related mods versions

Forge 20.2.4 Minecraft 1.18.2

### Crashlog/log

https://pastebin.com/xT1mDMfF

**Comment by zyxkad** [comment]
Dup of #463
