### ISSUE TITLE
incorrect 'Create' version requirements in mods.toml

### ISSUE THREAD

**Issue by nanonestor** [Seniorendi/AdvancedPeripherals#469]
### Describe

Mod file is AdvancedPeripherals-1.18.2-0.7.30r.jar

`Mod ID: 'create', Requested by: 'advancedperipherals', Expected range: '[0.5.1a,)', Actual version: '0.5.1.b'`

### Steps to reproduce

The above should be sufficient

### Multiplayer?

No

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Forge 40.2.8 - 1.18.2

**Comment by ModernGamingWorld** [comment]
O is this why my game wont load cause the mod was updated to a new create version I can't update to do to its latest update breaking things

**Comment by Einhornyordle** [comment]
Looks like the dev f-ed that up, I've already submitted a pull request to fix the issue, for now you'd have to downgrade AP to play with Create.

**Comment by SirEndii** [comment]
Heyo
Fixed and re-uploaded -> https://legacy.curseforge.com/minecraft/mc-mods/advanced-peripherals/files/4562223

**Comment by nanonestor** [comment]
Thank you!

**Comment by pythongirl325** [comment]
> Heyo Fixed and re-uploaded -> https://legacy.curseforge.com/minecraft/mc-mods/advanced-peripherals/files/4562223

Will this fixed version be uploaded on modrinth too?

**Comment by SirEndii** [comment]
Sure... sure *how did I forget this?!*

**Comment by Faeranne** [comment]
Wanted to check in on this, is the modrinth version still in progress?  (haven't personally released a mod there yet, so I'm curious if something is holding it up)

**Comment by SirEndii** [comment]
Should be uploaded now. *oops*
