### ISSUE TITLE
Inventory Manager - relative or cardinal directions don't seem to work

### ISSUE THREAD

**Issue by toastonrye** [Seniorendi/AdvancedPeripherals#473]
### Describe

pastebin of code: https://pastebin.com/yrMbyY2Y

I'm having issues with the directions, the documentation says I can use relative or  cardinal directions, however when I use UP it says not a valid side.

When I use TOP, it doesn't seem to move the items. This script was originally written for 1.18 and I was trying to get it working in 1.19.2 again. Oddly enough, I had fixed this issue with a previous version of AP for 1.19.2 https://github.com/SirEndii/AdvancedPeripherals/issues/428 but I'm not sure if I'm missing something obvious...

I have also tried using WEST or LEFT, which has the same results as TOP or UP.

I made a 50 second video to demonstrate my problem, https://youtu.be/ostdsq1V6NQ

### Steps to reproduce

See pastebin, plus 50 second video

### Multiplayer?

Yes

### Version

1.19.2-0.7.27r (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

43.2.10 and 1.19.2

### Screenshots or Videos

https://youtu.be/ostdsq1V6NQ

**Comment by SirEndii** [comment]
Hi, this issue got fixed(#444) in 1.19.2-0.7.28r
Could you test this?

**Comment by toastonrye** [comment]
Oh, I should have looked at the newer versions for posting. I'm sure it's fixed, just playing a modpack using an older  version. Sorry about that,

**Comment by SirEndii** [comment]
Np!
