### ISSUE TITLE
Config to restrict the use of the Chat Box

### ISSUE THREAD

**Issue by main1108** [Seniorendi/AdvancedPeripherals#477]
### Describe your idea

Today, Chatbox’s chat send feature is used for trolling and The server that I'm currently on has decided to ban Chatbox from the server. So I thought if there’s a config that disables/restricts(like range limit) the send chat feature from the chatbox, it would be very nice.

**Comment by SirEndii** [comment]
[AdvancedPeripherals-1.19.2-0.7.29r.zip](https://github.com/SirEndii/AdvancedPeripherals/files/11985548/AdvancedPeripherals-1.19.2-0.7.29r.zip)

I've implemented your request, you can test it if you want
I've added two new configuration values, one for the max range and one to disallow multidimensional message sending

Unzip the file before using it
