### ISSUE TITLE
[Issue] craftItem expects two parameters.

### ISSUE THREAD

**Issue by 5cript** [Seniorendi/AdvancedPeripherals#48]
**Describe**

me bridge craftItem expects two parameters

**Reproduce**

`meBridge.craftItem({name="minecraft:stick"}, "minecraft:stick")`
The second parameter seems to be the item name still.
Also passing a nonsense string to the second parameter crashes the game.
(I think an exception is not caught)

...

**Versions:**

- Forge version: forge-1.16.5-36.1.4
- AdvancedPeripherals version: advancedperipherals-0.4b

**Crashlog/log**
https://pastebin.com/cHNCYit4

**Comment by Seniorendi** [comment]
[advancedperipherals-0.4b.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/6255118/advancedperipherals-0.4b.zip)
Hey, i fixed that. If you want, you can try that again with this version.(Unzip the file before)

**Comment by Seniorendi** [comment]
Fixed in 0.4.1b
