### ISSUE TITLE
Exception on digBlock()

### ISSUE THREAD

**Issue by riggyz** [Seniorendi/AdvancedPeripherals#482]
### Describe

Seemingly at random digBlock() will error out when called. I haven't been able to reproduce it consistently.

### Steps to reproduce

`
local auto = peripheral.wrap("right")
auto.digBlock()
`

### Multiplayer?

Yes

### Version

1.19.2-0.7.27r

### Minecraft, Forge and maybe other related mods versions

Forge 43.2.11 Minecraft 1.19.2

### Screenshots or Videos

![image](https://github.com/SirEndii/AdvancedPeripherals/assets/29961406/f4efd4dc-e221-4803-b8cd-3a7f8eccc79a)

**Comment by SirEndii** [comment]
I thought I fixed that, oops

There's a workaround
Running that a second time would fix that issue

**Comment by riggyz** [comment]
I noticed that if I run it a second time it fixes that, but how would I do that without it terminating the script the first time around? I plan on putting this turtle on a never ending mining mission so making sure that there are no terminating errors is big.

EDIT: I forgot about pcall() whoops
