### ISSUE TITLE
crash with cc in 1.20.1

### ISSUE THREAD

**Issue by awesomebossdj7** [Seniorendi/AdvancedPeripherals#484]
### Describe

game crashes when chatbox connects to a computer, something to do with server tick

### Steps to reproduce

place a chat box on top of basic computer, game crashes

### Multiplayer?

No

### Version

1.20.1-0.7.31a (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Forge 47.1.0 Minecraft 1.20.1

### Crashlog/log

main crash issue: https://pastebin.com/3teN0642

**Comment by awesomebossdj7** [comment]
full crash log: https://pastebin.com/K7HgkTj3

**Comment by SirEndii** [comment]
It's an incompatibility with the newest CC version, you could downgrade CC: Tweaked in the meantime
