### ISSUE TITLE
Problem with reading AE2 additions cells

### ISSUE THREAD

**Issue by Campelo10** [Seniorendi/AdvancedPeripherals#485]
### Describe

The ME bridge doesn't recognize the cells from AE2 additions, I tried to make a program to get total space available on the system and I noticed that it just showed the cells from AE2 things I had in my system

### Steps to reproduce

1. run listCells()
2. It won't return AE2 additions cells

### Multiplayer?

Yes

### Version

1.19.2-0.7.29r (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

forge 43.2.14, MC 1.19.2

**Comment by SirEndii** [comment]
Which AP Version do you use? You've selected 1.19.3 but use minecraft and forge for 1.19.2
