### ISSUE TITLE
Player detector not detecting on different dimensions

### ISSUE THREAD

**Issue by Campelo10** [Seniorendi/AdvancedPeripherals#486]
### Describe

It's kinda in the title, the detector won't get the position of players that are in different dims

### Steps to reproduce

1. run 
```lua
local playerTable = detector.getOnlinePlayers()
local function tableConstructor()
  local list = {}
  for i = 1, #playerTable, 1 do
    list[i] = {name = playerTable[i], pos = detector.getPlayerPos(playerTable[i]), index = i, is_afk = false, newPos = {}, afk_count = 0, startCursorX = 0,endCursorX = 0}
  end
  return list
end
local players = tableConstructor()
```
2. it'll only get the position of players that are in overworld (didn't get to test in other dims)

### Multiplayer?

Yes

### Version

1.19.2-0.7.29r (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

forge 43.2.14, MC 1.19.2

**Comment by zyxkad** [comment]
It makes sense, just place the detector in multiple dims

**Comment by SirEndii** [comment]
Yes it does
However, I'm gonna add a config option to enable this
