### ISSUE TITLE
ME Bridge Crashes Server

### ISSUE THREAD

**Issue by caldavsta** [Seniorendi/AdvancedPeripherals#487]
### Describe

I had one ME Bridge. It was working very well for 2 weeks, querying for amount of items in AE System, then initiating auto-crafting orders when under threshold. 

Now, recently I added a second ME Bridge to the system. It **seems** that after I did that, the first one started crashing the server. It will work fine for a few minutes after server restart, then it will crash again after some time. Also, when it is in this bad state, it will not start new crafting orders, but craftItem(name, count) and craftItem(fingerprint, count) will still return true.

**Repros on AllTheMods versions:**
1.0.16
1.0.22

**Repros on Advanced Peripherals versions:**
1.19.2-0.7.29r
0.7.27r

**Repros on Forge Versions:**
43.2.14
43.2.8

**Crashlogs 1.19.2-0.7.29r:**
https://pastebin.com/9R97pmj0
https://pastebin.com/kAbhZtbY

**Crashlog 0.7.27r**
https://pastebin.com/Fpe4mpX7

### Steps to reproduce

Add 2 ME Bridges to the network(?).

### Multiplayer?

Yes

### Version

1.19.3-0.7.29r (Latest 1.19.3)

### Minecraft, Forge and maybe other related mods versions

See Description for Versions

### Crashlog/log

https://pastebin.com/9R97pmj0

**Comment by SirEndii** [comment]
That's an issue with the crafting system

Both bridges try to  manage the craft jobs for the system, that leads to a ConcurrentModificationException exception
I would recommend to use only one bridge until I fix this

**Comment by SirEndii** [comment]
If you want to test the fix, here you go
https://mvn.intelligence-modding.de/intelligence/de/srendi/advancedperipherals/advancedperipherals/1.19.2-0.7.29r-DEV_45/advancedperipherals-1.19.2-0.7.29r-DEV_45.jar
