### ISSUE TITLE
[1.20.1] Server crash after interacting with a computer and every time the chunk is loaded again

### ISSUE THREAD

**Issue by FlashHUN** [Seniorendi/AdvancedPeripherals#489]
### Describe

According to one of my players, all they did was click on a computer in a randomly generated village once and it crashed the server, and it keeps crashing every time the chunk is loaded again. Crash report provided below.

### Steps to reproduce

1. Interact with a computer (did not test if it must be one generated in a village or not)
2. Server crashes
3. Every time the chunk is loaded again, server crashes with the exact same exception thrown

### Multiplayer?

Yes

### Version

1.20.1-0.7.31a (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Minecraft 1.20.1, Forge 47.1.1, CC: Tweaked 1.106.1

### Crashlog/log

https://pastebin.com/Wvqmtuim

**Comment by SirEndii** [comment]
[AdvancedPeripherals-1.20.1-0.7.31a.zip](https://github.com/SirEndii/AdvancedPeripherals/files/12062498/AdvancedPeripherals-1.20.1-0.7.31a.zip)

AP is currently not compatible with the newest CC:T Version
You can use this build instead, this fixes the incompatibility
Unzip the file before using it
