### ISSUE TITLE
[Issue]Rs bridge listCraftableItems() make my lastest.log 3.1G

### ISSUE THREAD

**Issue by Death-123** [Seniorendi/AdvancedPeripherals#49]
**Describe**

when i use Rs bridge listCraftableItems() in server, i saw this
![image](https://user-images.githubusercontent.com/50763371/113989767-5b9bb180-9883-11eb-87c0-b10198c56755.png)

**Reproduce**

1.use rs.listCraftableItems()
2.see log

**Screenshots/Videos**

If applicable, add screenshots or videos to help explain your problem.

**Versions:**

- Forge version:forge-1.16.5-36.1.2
- AdvancedPeripherals version:0.4.2b

**Crashlog/log (Use https://paste.gg or https://pastebin.com to upload your crashlog/log)**
log : https://paste.gg/p/anonymous/a999bfc221b04133a71349cf6aea1fe8
startup.lua : https://paste.gg/p/anonymous/9cebb1e2bc3e4a1795aa0ec977efe5f1

**Comment by Seniorendi** [comment]
Fixed in 0.4.2.1b
