### ISSUE TITLE
Refined System Overflow problem

### ISSUE THREAD

**Issue by LunaLorea** [Seniorendi/AdvancedPeripherals#497]
### Describe

When Refined storage is used in combination with drawers from Functional Storage the external storage can get so big that the number overflows.

### Steps to reproduce

Playing FTB Stoneblock 3 1.7.1 Downloaded with the FTB App (I couldn't figure out what version of your mod is used :/ )

Place RS controller and connect a drawer with 4 netherite upgrades as external Storage
Place Computer with rsBridge inbetween next to the controller

![2023-08-01_20 07 27](https://github.com/SirEndii/AdvancedPeripherals/assets/69536618/6402b3eb-94d5-4157-a6ef-4fabe5209a91)

read the max external storage as such:
```Lua
local rsb = peripheral.find("rsBridge")
amount = rsb.getMaxItemExternalStorage()
print(amount)
```
![2023-08-01_20 03 55](https://github.com/SirEndii/AdvancedPeripherals/assets/69536618/b4c20719-5242-4b55-8bba-72f8f054e1ad)

output: 2,147,483,647

![2023-08-01_20 08 23](https://github.com/SirEndii/AdvancedPeripherals/assets/69536618/528e05e2-15a3-4221-9f1e-36f8e42c929b)

now add a second drawer without any upgrades

![2023-08-01_20 05 40](https://github.com/SirEndii/AdvancedPeripherals/assets/69536618/ce7306c9-3f1e-4c55-8b7d-e7e35a3f7db9)

when i execute the script again the number overflows and becomes negative

![2023-08-01_20 09 36](https://github.com/SirEndii/AdvancedPeripherals/assets/69536618/4ad080a5-492d-4ff2-8991-f88780d44e0f)

Let me know if you need more information or if i need to create a bug report somewhere else 
~Luna <3

### Multiplayer?

Yes

### Version

1.18.2-0.7.30r (Latest 1.18.2)

### Minecraft, Forge and maybe other related mods versions

FTB StoneBlock 3 1.7.1

**Comment by SirEndii** [comment]
Interesting issue, a shame that I never thought about this

Thanks for reporting

**Comment by LunaLorea** [comment]
[src\main\java\de\srendi\advancedperipherals\common\addons\refinedstorage\RefinedStorage.java](https://github.com/SirEndii/AdvancedPeripherals/blob/1.20.1/src/main/java/de/srendi/advancedperipherals/common/addons/refinedstorage/RefinedStorage.java)

```java
public static int getMaxItemExternalStorage(INetwork network) {
    int total = 0;
    for (IStorage<ItemStack> store : network.getItemStorageCache().getStorages()) {
        if (store instanceof IExternalStorage<ItemStack> externalStorage) {
            total += externalStorage.getCapacity();
        }
    }
    return total;
}
```

In the RS api
[src/main/java/com/refinedmods/refinedstorage/api/storage/externalstorage/IExternalStorage.java](https://github.com/refinedmods/refinedstorage/blob/develop/src/main/java/com/refinedmods/refinedstorage/api/storage/externalstorage/IExternalStorage.java)

```java
    /**
     * @return the capacity of the connected storage
     */
    long getCapacity();
}
```

the method getCapacity() returns a long type integer. I think the bug appears when the return of getCapacity() gets added to the total. ( I havent looked deeper into the getCapacity method so maybe theres an error somewhere deeper down the line but I would suggest changing it here and see if it solves the problem)


So to fix the bug I think we just need to keep using the long type. maybe like this?
```java
public static int getMaxItemExternalStorage(INetwork network) {
    long total = 0L;
    for (IStorage<ItemStack> store : network.getItemStorageCache().getStorages()) {
        if (store instanceof IExternalStorage<ItemStack> externalStorage) {
            total += externalStorage.getCapacity();
        }
    }
    return total;
}
```

What do you think?

**Comment by zyxkad** [comment]
Isn't drawer have infinity storage?
So just compare the capacities with `Integer.MAX_VALUE` may help.

**Comment by SirEndii** [comment]
Not infinite, it's a signed 64-bit integer 

> What do you think?

That's right, but you would also need to set the return type of the method to `long`

**Comment by zyxkad** [comment]
```java
public static long getMaxItemExternalStorage(INetwork network) {
    long total = 0;
    for (IStorage<ItemStack> store : network.getItemStorageCache().getStorages()) {
        if (store instanceof IExternalStorage<ItemStack> externalStorage) {
            long cap = externalStorage.getCapacity();
            if(total >= Long.MAX_VALUE - cap){ // total + cap >= long.max
              total = Long.MAX_VALUE
           }else{
              total += cap
           }
        }
    }
    return total;
}
```

**Comment by LunaLorea** [comment]
> Isn't drawer have infinity storage?

no, drawers with 4 netherite upgrades can store 31^2-1 or 2147483647 items. So as soon as you have more storage than 1 fully upgraded drawer the 32bit int isn't enough to count the entire storage.

**Comment by zyxkad** [comment]
I see, so my solution just completely avoid the overflow issue with whatever or how many storages you have

**Comment by LunaLorea** [comment]
The same may be true for fluid storage when using fluid drawers.

**Comment by SirEndii** [comment]
> ```java
> public static int getMaxItemExternalStorage(INetwork network) {
>     int total = 0;
>     for (IStorage<ItemStack> store : network.getItemStorageCache().getStorages()) {
>         if (store instanceof IExternalStorage<ItemStack> externalStorage) {
>             int cap = externalStorage.getCapacity();
>             if(total >= Integer.MAX_VALUE - cap){ // total + cap >= intmax
>               total = Integer.MAX_VALUE
>            }else{
>               total += cap
>            }
>         }
>     }
>     return total;
> }
> ```

Tbh that's quite unecessary and still wouldn't work if the whole system has a higher storage capacity than a 32-bit signed integer. So just switching to long would be sufficient.

This also needs to be adapted to the fluid system and the ME Bridge

**Comment by LunaLorea** [comment]
```
public static long getMaxItemExternalStorage(INetwork network) {
    long total = 0L;
    for (IStorage<ItemStack> store : network.getItemStorageCache().getStorages()) {
        if (store instanceof IExternalStorage<ItemStack> externalStorage) {
            total += externalStorage.getCapacity();
        }
    }
    return total;
}
```

this would solve the issue for external item storage with the RS system
same would have to be done to disk storage ( with 64k storage cells this probably isn't necessary but there are mods that offer bigger cells like [Extra Disks](https://www.curseforge.com/minecraft/mc-mods/extra-disks)

also as you said for the fluid system and the ME Bridge

> This also needs to be adapted to the fluid system and the ME Bridge

**Comment by SirEndii** [comment]
Yep, that should work just fine

**Comment by LunaLorea** [comment]
[src/main/java/de/srendi/advancedperipherals/common/addons/appliedenergistics/AppEngApi.java](https://github.com/SirEndii/AdvancedPeripherals/blob/1.20.1/src/main/java/de/srendi/advancedperipherals/common/addons/appliedenergistics/AppEngApi.java)
```
public static long getTotalItemStorage(IGridNode node) {
        long total = 0;
```

The ME Bridge already uses the long type, so it only fluid and item, internal and external storage of the rs bridge

**Comment by SirEndii** [comment]
This issue got fixed, if someone wants to try it, they can download it from [here](https://mvn.intelligence-modding.de/#/Intelligence/de/srendi/advancedperipherals/advancedperipherals-snapshots/1.18.2-0.7.30r-SNAPSHOT-89)
