### ISSUE TITLE
[1.16.5] Turtles show nothing on-hover in JEI recipes

### ISSUE THREAD

**Issue by NillerMedDild** [Seniorendi/AdvancedPeripherals#51]
**Describe**

When holding the mouse over a Turtle in JEI, in the output of it's recipe, nothing is shown.

**Reproduce**

1. Install the mod and JEI
2. Click on any Advanced Peripherals Turtle in JEI
3. Hover over the Turtle in the output window
4. Observe bug

**Screenshots/Videos**

Bugged behaviour:
![billede](https://user-images.githubusercontent.com/21295394/114282644-643be580-9a45-11eb-90b8-20e37db8a82c.png)

Normal behaviour:
![billede](https://user-images.githubusercontent.com/21295394/114282649-6aca5d00-9a45-11eb-8022-14f006393f59.png)

**Versions:**

- Forge version: 1.16.5-36.1.0
- AdvancedPeripherals version: 0.4.3.1b

**Comment by Seniorendi** [comment]
Hey,
CC have the same issue with turtle upgrades(not the normal turtle crafting recipe).
Here is an example of the Advanced Wireless turtle.
![Pic](https://user-images.githubusercontent.com/67484093/114287440-0f10cb80-9a67-11eb-8542-4e0b407d2d77.png)

**Comment by Seniorendi** [comment]
https://github.com/SquidDev-CC/CC-Tweaked/issues/719
CC-Tweaked fixed that issue. 👍🏻
