### ISSUE TITLE
"attempt to call field 'drawStringWithId' (a nil value)"

### ISSUE THREAD

**Issue by I3O5** [Seniorendi/AdvancedPeripherals#518]
### Describe

I can't draw anything with an id on the screen using the AR goggles. drawString(), horizontalLine(), etc. work fine, but anytime I try to draw something with an id it produces an error, for example: "attempt to call field 'drawStringWithId' (a nil value)".

### Steps to reproduce

1. write a script that should draw "Hello world!" as a string with id
2. run your code

### Multiplayer?

Yes

### Version

older (probably unsupported)

### Minecraft, Forge and maybe other related mods versions

Forge 36.2.39, minecraft 1.16.5, cc-tweaked-1.16.5-1.101.3

**Comment by SirEndii** [comment]
The functions including an Id do not exist in 1.16, they were created for 1.18.2 and newer
