### ISSUE TITLE
The index of argument `range` on the methods `sendMessageToPlayer` and `sendFormattedMessageToPlayer` in chatbox is incorrect

### ISSUE THREAD

**Issue by zyxkad** [Seniorendi/AdvancedPeripherals#522]
### Describe

As the title said, should be simple copy & paste issue (modder is lazy ah)

<https://github.com/SirEndii/AdvancedPeripherals/commit/134cdffac2399454c35141088a10dab028feeaa5#diff-169e726cb0aaf509df0e51437a363b33fb140f8627cc69c7bdb06ab6c04c2ac4R185>

### Steps to reproduce

1. call method `sendMessageToPlayer` or `sendFormattedMessageToPlayer` on a chatbox peripheral, and pass the fifth argument
2. The invoke will always failed

### Multiplayer?

No

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Minecraft 1.19.2

**Comment by SirEndii** [comment]
Reopen until released
