### ISSUE TITLE
[BUG] You could never change the brackets' colors with chatBox

### ISSUE THREAD

**Issue by zyxkad** [Seniorendi/AdvancedPeripherals#524]
### Describe

The forth argument of `sendMessage` method is `bracketColor`
<https://docs.advanced-peripherals.de/peripherals/chat_box/#sendmessage>
In the example at the given link before, we should use the color code `§c` for the color.
However, CC could never accept non ascii char code `§`, which means we could never change the bracket's color

### Steps to reproduce

1. connect to a chatBox
2. Call method `sendMessage`, try pass the color code
3. You will found you can never type `§` or paste it.

### Multiplayer?

No

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Minecraft 1.19.2

**Comment by SirEndii** [comment]
Reopen until released
