### ISSUE TITLE
$[text] get shown in chat of other players

### ISSUE THREAD

**Issue by ghost** [Seniorendi/AdvancedPeripherals#528]
### Describe

if i write $[textmessage] in the public chat it is only hidden for me and other players can still read it 

### Steps to reproduce

1. write a message with $ in chat
2. read as other player

### Multiplayer?

Yes

### Version

1.20.1-0.7.32b (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Forge-47.1.3, All the mods9- 0.2.5

**Comment by ghost** [comment]
I tested it in a local lan world with forge and only cc and AdvancedPeripherals and it works there maybe its a problem with atm

**Comment by zyxkad** [comment]
It maybe a problem of the server, are you using the pure forge server or mixed?

**Comment by ghost** [comment]
I tested it again but on the Server apperently it worked most of the time and there Was only one specific  player who could see it. I play on the moddedmc Server where the atm9 Pack has 3 conected Server with merged Chat

**Comment by SirEndii** [comment]
I will mark this as closed, I am unable to reproduce this and it seems from the chat history here, that it isn't APs fault anyways

If someone has questions or notices the bug again, feel free to ask or reopen the thread again
