### ISSUE TITLE
Stray pixel in inventory_manager_gui.png

### ISSUE THREAD

**Issue by VoidedMirror** [Seniorendi/AdvancedPeripherals#530]
### Describe

There is a random gray pixel in the inventory manager gui screen
![image](https://github.com/SirEndii/AdvancedPeripherals/assets/101021633/7d8cce09-0327-47d4-84c8-8549c3a3dc55)

### Steps to reproduce

1. Open GUI screen for the Inventory Manager
2. Stray pixel is on the right side of the memory card slot

### Multiplayer?

Yes

### Version

1.20.1-0.7.32b (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Forge 47.1.3

**Comment by zyxkad** [comment]
~~How dare are you???~~
