### ISSUE TITLE
No Recipe for RS Bridge and Colony Integrator at ATM9 in 1.20.1

### ISSUE THREAD

**Issue by itsBenni007** [Seniorendi/AdvancedPeripherals#534]
### Describe

Heyho i cant find any recipe (the blocks are shown in JEI) for the Colony Integrator and the RS Bridge in my JEI in 1.20.1, For the ME Bridge i can see a recipe but not for the 2 others. what can i do to fix that? I also tried the recipes like they are hardcoded in your sourcecode but nothing happens.

### Steps to reproduce

![image](https://github.com/SirEndii/AdvancedPeripherals/assets/118443349/3882a8ff-7c85-47fe-80da-60b5c8215107)

### Multiplayer?

Yes

### Version

1.20.1-0.7.32b (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Forge 47.1.3, minecolonies 1.1.314-BETA, refinedstorage 1.12.4

**Comment by SirEndii** [comment]
This got fixed in 0.7.33b
