### ISSUE TITLE
addItemToPlayer always fails and remoteItemFromPlayer always throws INVENTORY_TO_INVALID

### ISSUE THREAD

**Issue by CalebJohnHunt** [Seniorendi/AdvancedPeripherals#537]
### Describe

Every time I try to use `addItemToPlayer` I always see `0` and `nil` (meaning it didn't move anything).
Every time I try to use `removeItemFromPlayer` I always see `0` and `"INVENTORY_TO_INVALID"`. If I put a bad direction (`"botton"`) it tells me `botton is not a valid side`, so clearly it's recognizing the direction.

### Steps to reproduce

Version: 0.7.35b

1. Chest above with 1 cobblestone in first slot.
2. Advanced computer
3. Inventory manger with a memory card tied to me to the right
4. Code:
```lua
manager = peripherals.find("inventoryManager")
manager.addItemToPlayer("top", {name="minecraft:cobblestone", toSlot=36, count=1})
-- 0
-- nil
manager.removeItemFromPlayer("top", {})
-- 0
-- "INVENTORY_TO_INVALID"
```

### Multiplayer?

No

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Forge 47.2.0, CC: Tweaked 1.109.0

**Comment by SirEndii** [comment]
Just to be sure, is your chest on top of the inventory manager?

**Comment by CalebJohnHunt** [comment]
This also seems to happen to the RS bridge using `exportItem`. It gives me `"INVALID_TARGET"` every time.

**Comment by SirEndii** [comment]
> This also seems to happen to the RS bridge using `exportItem`. It gives me `"INVALID_TARGET"` every time.

It is important that you place the chest next to the Bridge or the Inventory Manager and not next to the computer

**Comment by CalebJohnHunt** [comment]
Oh my gosh. oh my gosh. I'm so dumb; I'm pretty sure I learned this some months ago and totally forgot. Thanks for being patient with me.
Closed.

**Comment by SirEndii** [comment]
Tbf, I should document this
