### ISSUE TITLE
[Issue] Environment Detector "isSlimeChunk" on turtles

### ISSUE THREAD

**Issue by Joao-Tome** [Seniorendi/AdvancedPeripherals#54]
I don't know why, but the function "isSlimeChunk" on turtle don't work, is always false

Pocket:
![imagem_2021-04-17_162523](https://user-images.githubusercontent.com/73352040/115124627-84195f00-9f99-11eb-9059-6ef563f1f7c5.png)

Turtle:
![image](https://user-images.githubusercontent.com/73352040/115124649-a01d0080-9f99-11eb-9dba-02aedb63e2ee.png)

computer:
![image](https://user-images.githubusercontent.com/73352040/115124712-02760100-9f9a-11eb-855d-01af0354a0a5.png)

i'm on the same chunk. just 1 block off

**Comment by Seniorendi** [comment]
It's possible that you are not in the same chunk as the turtle?
You can see the chunk boarders with F3+G

**Comment by Joao-Tome** [comment]
no, the turtle is on the same chunk

**Comment by Seniorendi** [comment]
Because this is a more complicated issue than I thought, i will fix that in a few days.

**Comment by Seniorendi** [comment]
A little bit late, sorry for that. But fixed in 0.6.2b
