### ISSUE TITLE
Descriptions aren't working

### ISSUE THREAD

**Issue by lonevox** [Seniorendi/AdvancedPeripherals#542]
### Describe

All items that have a tooltip that includes `[Left Control] For Description` don't show their tooltip when left control is pressed. Descriptions also aren't shown when a non-conflicting keybind is used.

### Steps to reproduce

Press `Left Control` on an item with a `[Left Control] For Description` tooltip.

### Multiplayer?

No

### Version

1.20.1-0.7.32b (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Forge 47.2.19

**Comment by zyxkad** [comment]
If you are using MacOS, you should press the command ⌘ key

**Comment by lonevox** [comment]
I'm on Windows

**Comment by zyxkad** [comment]
Are you trying to show the description in JEI or such stuff? That maybe only works in inventory I remember

**Comment by lonevox** [comment]
It doesn't work in JEI or the inventory
