### ISSUE TITLE
Inventory Manager is not doing anyting

### ISSUE THREAD

**Issue by IRonguy127** [Seniorendi/AdvancedPeripherals#543]
### Describe

Copied an example program from official documentation 
local manager = peripheral.find("inventoryManager")
-- Add 32 cobblestone to the players offhand slot from the block above
manager.addItemToPlayer("up", {name="minecraft:cobblestone", toSlot=36, count=32})

and it's not doing anything, i have the chest and the items, all slots are empty, removeItemFromPlayer is not working too.

No errors or lags seen, just nothing happens

### Steps to reproduce

use any function of Inventory Manager

### Multiplayer?

No

### Version

1.20.1-0.7.32b (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

forge-1.20.1-47.2.19

**Comment by zyxkad** [comment]
what's the result of `addItemToPlayer`? do `print(manager.addItemToPlayer ...`

**Comment by zyxkad** [comment]
And did you put the chest on top of the inventory manager?

**Comment by IRonguy127** [comment]
@zyxkad  yeah, i was putting the chest above the computer, not inventory manager. Thanks for helping out
