### ISSUE TITLE
The automata charge function not working 1.20.1

### ISSUE THREAD

**Issue by VenerableTimeWanderer** [Seniorendi/AdvancedPeripherals#552]
### Describe

The chargeTurtle function is not working as it says "Fuel consumption is disabled...". Checked and it should be enabled. I then followed to jump throw the rabbit hole of looking through the code on github of both AP and CC:tweaked and still haven't norrowed it down. If you compare where the InfinitePocketFuelAbility.java to what the TurtleFuelAbility.java does I could easily see how the InfinitePocketFuelAbility.java works. I saw that [Use ITurtleAccess.isFuelNeeded over probing config] and I checked and there is no reference in the ITurtleAccess.java for isFuelNeeded for a true or false. I also looked at ITurtleAccess.java which ultimately goes back to the TurtleBrain.java in dan200 github but not cc:Tweaked's one. So unless it is refenced some where else which is possible becasue cc:Tweaked's github is a mess compared to the dan200's one. Also saw [Use ITurtleAccess.isFuelNeeded over probing config] message on TurtleFuelAbility.java which leads me to believe that to be the problem.

### Steps to reproduce

All the Mods 9, Have an end automata equipped in turtle. 
1. go into lua on turtle
2. auto = peripheral.find("endAutomata")
3. auto.chargeTurtle() 
4. And it errors saying that fuel isnt enabled or something. (Check and it is is)

### Multiplayer?

No

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Forge 47.2.19 1.20.1

**Comment by VenerableTimeWanderer** [comment]
I did some more testing and it might be cc:tweaked, cause the need_fuel in the config doesn't work. edit: this isnt the cause for it, as the config is in the world folder.

**Comment by SirEndii** [comment]
Could you test this again with the latest version? 1.20.1-0.7.37r
I wasn't really able to reproduce the issue you have

**Comment by VenerableTimeWanderer** [comment]
Im still getting the same problem, can you please tell me if you are editing any config, cause I was doing a clean install, and still getting the problem. I am at 1.20.1-0.7.37r

**Comment by VenerableTimeWanderer** [comment]
![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/57559691/03d1e684-9de4-4db7-befd-c88b4e0f915a)
![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/57559691/620beaf5-455d-4a6d-b8b3-cffc6d40a9e6)

**Comment by SirEndii** [comment]
Some stuff I noticed

Tile entities check if the AP config option is enabled for powered tile entities
Our turtles check if the config option for `need_fuel` is enabled in the CC configuration

That is fine at all
But `isFuelConsumptionDisable` is currently wrong configured 
https://github.com/IntelligenceModding/AdvancedPeripherals/blob/c4e06eeb1730c5f20498b05a61db9965e9ace407/src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/owner/TurtleFuelAbility.java#L24-L26

So fuel consumption is disabled when the turtle needs fuel. That's wrong and needs a fix
