### ISSUE TITLE
Crash on 1.20.1

### ISSUE THREAD

**Issue by FrozenGalaxy** [Seniorendi/AdvancedPeripherals#556]
### Describe

"ClassDefFoundError: net/minecraft/client/gui/components/toasts/Toast"

### Steps to reproduce

Start the server

### Multiplayer?

Yes

### Version

1.20.1-0.7.37r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

neo 1.20.1

### Crashlog/log

https://gist.github.com/FrozenGalaxy/def15c115685c1971ca199336ae55ceb

**Comment by louino2478** [comment]
I have the same issue.

neoforge-1.20.1-47.1.99 on a server

[2024-02-09-2.log](https://github.com/IntelligenceModding/AdvancedPeripherals/files/14226812/2024-02-09-2.log)

**Comment by Aquaxoc** [comment]
I have the same issue on server forge-1.20.1-47.2.1 and forge-1.20.1-47.2.20 with CC:Tweaked and AdvancedPeripherals as the only two mods.
[crash-2024-02-10_01.18.50-fml.txt](https://github.com/IntelligenceModding/AdvancedPeripherals/files/14227215/crash-2024-02-10_01.18.50-fml.txt)

Client runs fine and I can send toasts with the chat box.

**Comment by SirEndii** [comment]
Downgrading to 1.20.1-0.7.36r will fix the issue

I will mark the versions as archived on curseforge and upload a fix today or tomorrow

**Comment by SirEndii** [comment]
I will publish a release in the course of the day

Feel free to test the artifacts in the meantime
- [1.19.2-0.7.34r Snapshot](https://mvn.intelligence-modding.de/Intelligence/de/srendi/advancedperipherals/advancedperipherals-snapshots/1.19.2-0.7.34r-SNAPSHOT-207/advancedperipherals-snapshots-1.19.2-0.7.34r-SNAPSHOT-207.jar)
- [1.20.1-0.7.38r Snapshot](https://mvn.intelligence-modding.de/Intelligence/de/srendi/advancedperipherals/advancedperipherals-snapshots/1.20.1-0.7.38r-SNAPSHOT-208/advancedperipherals-snapshots-1.20.1-0.7.38r-SNAPSHOT-208.jar)
