### ISSUE TITLE
Items not stacking properly when getItem() is run

### ISSUE THREAD

**Issue by Creeperdan1** [Seniorendi/AdvancedPeripherals#560]
### Describe

Everytime getItems() is run any blocks picked up from mining will become a new stack in the inventory. When the blocks are manually stacked in the inventory and the getItems() is run in a slower loop the newest block stack wont combine with the others even though the seem identical with no tag difference.

### Steps to reproduce

1. Use peripheral inventoryManager
2. Run manager.getItems()
3. Pickup Blocks

Fast Loop:
![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/95147511/eb809a5e-55d4-4c2c-90d7-f9974ceed4f3)
![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/95147511/d6426b2b-f555-4dc7-90c1-ef4f469431b7)
(Keeps making a new stack of dirt everytime it is mined

Slow Loop:
![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/95147511/0b449819-f855-45d1-bf74-d33b8140898d)
![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/95147511/295e3b8a-4f85-44e9-ba98-2890c79402d4)
(The dirt wont stack with eachother until the next getItems() cycle)

### Multiplayer?

Yes

### Version

1.20.1-0.7.38r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Forge 47.2.20 Minecraft 1.20.1

**Comment by alexandeers** [comment]
An empty NBT array "{}" is added to all items in the player's inventory when calling the getItem() function, which is apparently enough to distinguish items from regular items (even though the array is empty). The empty NBT array will disappear if you place a affected block and then break it, making it stackable (with normal stacks) again.
