### ISSUE TITLE
Massive item spawning glitch 

### ISSUE THREAD

**Issue by awesomebossdj7** [Seniorendi/AdvancedPeripherals#565]
### Describe

There is a bug where you can use a book and quill, plus nbt block and reader and shulker box to spawn in literally any item, I'm not exactly sure on how to do it, because I only saw this from players on a server I'm playing on

### Steps to reproduce

Put nbt in a book, put book in chest, point nbt reader to chest, use some program (probably just writing the data to the nbt block) then break the nbt storage block and then open the shulker then you have any item 

### Multiplayer?

Yes

### Version

1.18.2-0.7.31r (Latest 1.18.2)

### Minecraft, Forge and maybe other related mods versions

40.2.17 Minecraft 1.18.2

### Screenshots or Videos

https://cdn.discordapp.com/attachments/1115249875559395389/1216079988474908733/2024-03-09_20-36-13.mp4?ex=65ff15be&is=65eca0be&hm=8af942a740a32e7f014ce7397f55079a679d811c80ee442f0b54a0e4850b9032&

**Comment by awesomebossdj7** [comment]
okay you don't need the shulker box, the nbt storage block just turns into it

**Comment by SirEndii** [comment]
Would it be possible for you to get that script he used?
It's a bit hard to guess how it works

**Comment by awesomebossdj7** [comment]
Well the admin who discovered it, deleted the script, the server admins and I are gonna try to recreate it, it looks simple enough, but could also be pretty complex, I'll get back to you

**Comment by SirEndii** [comment]
Alright
And would it be possible to see the content of that book?

**Comment by AdamProGamingTR** [comment]
> Alright And would it be possible to see the content of that book?

![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/128465594/cf90fdad-b002-444a-8899-87e354e88820)

![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/128465594/a1c1b8ed-73f7-4972-b6b9-4001483ea9ff)

**Comment by SirEndii** [comment]
One workaround for now is that you can disable the nbt storage in the config until I find a solution

**Comment by UnhappyCodings** [comment]
Hey! Could you check the pickaxe's enchantments and send them to us?

**Comment by SirEndii** [comment]
Greetings again

The rat texted me per discord 
![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/67484093/9ca09d0b-cdfa-4664-ae6d-5240b9be42bf)

>  but I can assure you that it's not caused by your mod alone

My thought is now, that the NBT data from the NBT storage gets injected into the shulker he collects when he breaks the nbt storage.  So I would need to know what the pickaxe does/the enchantments from it, so find a potential fix 

But my guess is that I can't fix it but the author of the mod of the enchantment/pickaxe needs to fix this. The NBT Storage seems to be just a medium for the NBT data to move to the shulker box.

**Comment by SirEndii** [comment]
Would it be possible to get the modlist?

**Comment by AdamProGamingTR** [comment]
[Kotlin for Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Controlling](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Caelus API](https://www.curseforge.com/minecraft/mc-mods/caelus)
[MmmMmmMmmMmm](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm)
[CC:C Bridge](https://www.curseforge.com/minecraft/mc-mods/cccbridge)
[Max Health Fix](https://www.curseforge.com/minecraft/mc-mods/max-health-fix)
[Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Refined Storage](https://www.curseforge.com/minecraft/mc-mods/refined-storage)
[Sound Physics Remastered](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[Mod Name Tooltip](https://www.curseforge.com/minecraft/mc-mods/mod-name-tooltip)
[Thermal Integration](https://www.curseforge.com/minecraft/mc-mods/thermal-integration)
[Clockwork: Create x Valkyrien Skies](https://www.curseforge.com/minecraft/mc-mods/create-clockwork)
[AlchemyLib](https://www.curseforge.com/minecraft/mc-mods/alchemylib)
[Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Balm (Forge Edition)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Advanced Peripherals](https://www.curseforge.com/minecraft/mc-mods/advanced-peripherals)
[Brandon's Core](https://www.curseforge.com/minecraft/mc-mods/brandons-core)
[KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs)
[Create: Broken Bad](https://www.curseforge.com/minecraft/mc-mods/create-broken-bad)
[FTB Chunks (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge)
[Mekanism](https://www.curseforge.com/minecraft/mc-mods/mekanism)
[AmbientSounds](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)
[Architectury API](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[AEInfinityBooster](https://www.curseforge.com/minecraft/mc-mods/aeinfinitybooster)
[Moonlight Lib](https://www.curseforge.com/minecraft/mc-mods/selene)
[Create: Design n' Decor](https://www.curseforge.com/minecraft/mc-mods/create-design-n-decor)
[Xaero's Minimap](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[fix GPU memory leak[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak)
[Create Big Cannons](https://www.curseforge.com/minecraft/mc-mods/create-big-cannons)
[Towns and Towers](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[Hex Casting](https://www.curseforge.com/minecraft/mc-mods/hexcasting)
[Iceberg](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[FTB Library (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[Structory](https://www.curseforge.com/minecraft/mc-mods/structory)
[Thermal Locomotion](https://www.curseforge.com/minecraft/mc-mods/thermal-locomotion)
[Mantle](https://www.curseforge.com/minecraft/mc-mods/mantle)
[AE2 Things [Forge]](https://www.curseforge.com/minecraft/mc-mods/ae2-things-forge)
[Curios API (Forge/NeoForge)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Nether's Delight](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
[Alchemistry](https://www.curseforge.com/minecraft/mc-mods/alchemistry)
[Fast Async World Save[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/fast-async-world-save-forge-fabric)
[Macaw's Furniture](https://www.curseforge.com/minecraft/mc-mods/macaws-furniture)
[Mekanism Tools](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools)
[Connectivity[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Waystones](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Legendary Tooltips](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips)
[Sophisticated Core](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[Model Gap Fix](https://www.curseforge.com/minecraft/mc-mods/model-gap-fix)
[Create Enchantment Industry](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
[Falling Leaves (Forge)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge)
[ESSENTIAL Mod](https://www.curseforge.com/minecraft/mc-mods/essential-mod)
[Advancement Plaques](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques)
[Create Deco](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Roughly Enough Resources](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-resources)
[CC: VS](https://www.curseforge.com/minecraft/mc-mods/cc-vs)
[Psi](https://www.curseforge.com/minecraft/mc-mods/psi)
[Lootr](https://www.curseforge.com/minecraft/mc-mods/lootr)
[ModernFix](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[Hostile Neural Networks](https://www.curseforge.com/minecraft/mc-mods/hostile-neural-networks)
[MEGA Cells](https://www.curseforge.com/minecraft/mc-mods/mega-cells)
[Dank Storage](https://www.curseforge.com/minecraft/mc-mods/dank-storage)
[Thermal Foundation](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation)
[Configured](https://www.curseforge.com/minecraft/mc-mods/configured)
[CodeChicken Lib](https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8)
[FramedBlocks](https://www.curseforge.com/minecraft/mc-mods/framedblocks)
[More Mekanism Processing](https://www.curseforge.com/minecraft/mc-mods/more-mekanism-processing)
[Chunk Sending[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric)
[Bookshelf](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Chipped](https://www.curseforge.com/minecraft/mc-mods/chipped)
[Builder's Delight (Forge)](https://www.curseforge.com/minecraft/mc-mods/builders-delight-forge)
[Cloth Config API (Fabric/Forge/NeoForge)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[REI Plugin Compatibilities](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-hacks)
[Entity Culling Fabric/Forge](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Valkyrien Storage - Sophisticated Compatibility](https://www.curseforge.com/minecraft/mc-mods/valkyrienskiessophisticatedstoragecompat)
[Macaw's Fences and Walls](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Simple Voice Chat](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Spartan Weaponry](https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry)
[Building Gadgets](https://www.curseforge.com/minecraft/mc-mods/building-gadgets)
[Better Fps - Render Distance[Forge]](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[Roughly Enough Loot Tables](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-loot-tables)
[Create: Connected](https://www.curseforge.com/minecraft/mc-mods/create-connected)
[Applied Energistics 2](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[ExtraStorage](https://www.curseforge.com/minecraft/mc-mods/extrastorage)
[Thermal Dynamics](https://www.curseforge.com/minecraft/mc-mods/thermal-dynamics)
[Create Crafts & Additions](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Tom's Simple Storage Mod](https://www.curseforge.com/minecraft/mc-mods/toms-storage)
[Immersive Engineering](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering)
[KubeJS Create](https://www.curseforge.com/minecraft/mc-mods/kubejs-create)
[Create Encased](https://www.curseforge.com/minecraft/mc-mods/create-encased)
[Charm of Undying](https://www.curseforge.com/minecraft/mc-mods/charm-of-undying)
[Placebo](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Colorful Hearts](https://www.curseforge.com/minecraft/mc-mods/health-overlay)
[ChemLib](https://www.curseforge.com/minecraft/mc-mods/chemlib)
[Item Highlighter](https://www.curseforge.com/minecraft/mc-mods/item-highlighter)
[Thermal Cultivation](https://www.curseforge.com/minecraft/mc-mods/thermal-cultivation)
[Prism](https://www.curseforge.com/minecraft/mc-mods/prism-lib)
[Elytra Slot](https://www.curseforge.com/minecraft/mc-mods/elytra-slot)
[Patchouli](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Sophisticated Storage](https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage)
[Create: Copycats+](https://www.curseforge.com/minecraft/mc-mods/copycats)
[CreativeCore](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Construction Wand](https://www.curseforge.com/minecraft/mc-mods/construction-wand)
[RSInfinityBooster](https://www.curseforge.com/minecraft/mc-mods/rsinfinitybooster)
[Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
[Jade 🔍](https://www.curseforge.com/minecraft/mc-mods/jade)
[Farmer's Delight](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Mouse Tweaks](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Compact Machines](https://www.curseforge.com/minecraft/mc-mods/compact-machines)
[Spartan Shields](https://www.curseforge.com/minecraft/mc-mods/spartan-shields)
[Thermal Innovation](https://www.curseforge.com/minecraft/mc-mods/thermal-innovation)
[Refined Cooking](https://www.curseforge.com/minecraft/mc-mods/refined-cooking)
[Twigs](https://www.curseforge.com/minecraft/mc-mods/twigs)
[PAUCAL](https://www.curseforge.com/minecraft/mc-mods/paucal)
[Valkyrien Skies](https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies)
[More Peripherals](https://www.curseforge.com/minecraft/mc-mods/more-peripherals)
[Ding](https://www.curseforge.com/minecraft/mc-mods/ding)
[Eureka! Ships! for Valkyrien Skies (Forge/Fabric)](https://www.curseforge.com/minecraft/mc-mods/eureka-ships)
[FTB Teams (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[Server Performance - Smooth Chunk Save[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Storage Drawers](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[CC: Tweaked](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked)
[Comforts](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Fast Leaf Decay](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[Draconic Evolution](https://www.curseforge.com/minecraft/mc-mods/draconic-evolution)
[Xaero's World Map](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Macaw's Windows](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[FerriteCore](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Roughly Enough Items (REI)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
[ChoiceTheorem's Overhauled Village](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village)
[KubeJS Mekanism](https://www.curseforge.com/minecraft/mc-mods/kubejs-mekanism)
[Create: Diesel Generators](https://www.curseforge.com/minecraft/mc-mods/create-diesel-generators)
[AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Goblin Traders](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[AutoRegLib](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
[Artifacts](https://www.curseforge.com/minecraft/mc-mods/artifacts)
[Create](https://www.curseforge.com/minecraft/mc-mods/create)
[ExpandAbility](https://www.curseforge.com/minecraft/mc-mods/expandability)
[Decorative Blocks](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[Applied Energistics 2 Wireless Terminals](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals)
[Thermal Expansion](https://www.curseforge.com/minecraft/mc-mods/thermal-expansion)
[Structure Essentials[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric)
[AE2 Extras](https://www.curseforge.com/minecraft/mc-mods/ae2-extras)
[Rhino](https://www.curseforge.com/minecraft/mc-mods/rhino)
[Refined Storage Addons](https://www.curseforge.com/minecraft/mc-mods/refined-storage-addons)
[CoFH Core](https://www.curseforge.com/minecraft/mc-mods/cofh-core)
[FTB Ultimine (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge)
[Overloaded Armor Bar](https://www.curseforge.com/minecraft/mc-mods/overloaded-armor-bar)
[Mekanism Generators](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)
[Applied Mekanistics](https://www.curseforge.com/minecraft/mc-mods/applied-mekanistics)
[PneumaticCraft: Repressurized](https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized)
[Tom's Peripherals](https://www.curseforge.com/minecraft/mc-mods/toms-peripherals)
[Macaw's Trapdoors](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Clumps](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Tinkers' Construct](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct)
[Cooking for Blockheads](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads)
[Create: Tweaked Controllers](https://www.curseforge.com/minecraft/mc-mods/create-tweaked-controllers)
[Cristel Lib](https://www.curseforge.com/minecraft/mc-mods/cristel-lib)
[Carry On](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[SebastrnLib](https://www.curseforge.com/minecraft/mc-mods/sebastrnlib)
[Fastload](https://www.curseforge.com/minecraft/mc-mods/fastload)
[MrCrayfish's Furniture Mod](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[Cosmetic Armor Reworked](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[Create: Interactive](https://www.curseforge.com/minecraft/mc-mods/create-interactive)
[Lazy DataFixerUpper(LazyDFU) [FORGE]](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
[ConnectedTexturesMod](https://www.curseforge.com/minecraft/mc-mods/ctm)
[Enchantment Descriptions](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Macaw's Doors](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Quark](https://www.curseforge.com/minecraft/mc-mods/quark)
[Cupboard](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Corpse](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Create: Alloyed](https://www.curseforge.com/minecraft/mc-mods/create-alloyed)
[Terralith](https://www.curseforge.com/minecraft/mc-mods/terralith)
[Embeddium (Rubidium) Extra](https://www.curseforge.com/minecraft/mc-mods/rubidium-extra)
[Embeddium/Rubidium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
[Embeddium/Rubidium Dynamic Lights](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)
[TexTrue's Rubidium Options](https://www.curseforge.com/minecraft/mc-mods/textrues-rubidium-options)
[Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[AttributeFix](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[Attribute Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/attribute-tooltip-fix)
[Vanishmod](https://www.curseforge.com/minecraft/mc-mods/vanishmod)
[Create Stuff & Additions](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)
[Figura](https://www.curseforge.com/minecraft/mc-mods/figura)

> Would it be possible to get the modlist?

**Comment by SirEndii** [comment]
Thank you

**Comment by AdamProGamingTR** [comment]
You should probably not listen to t8rt0t by the way. He doesn't want us (the admins of that server) knowing how the bug exactly works.

**Comment by awesomebossdj7** [comment]
also the block turns INTO a shulker box, im 99% sure its not caused by any other mod

**Comment by SirEndii** [comment]
> also the block turns INTO a shulker box, im 99% sure its not caused by any other mod

We think it's some kind of NBT injection. We don't modify the loot table at all, it's just a basic static loot table
So our theory is, that some kind of enchantment, belt, ring or whatever turns the block into the shulker box and puts the dropped block into the shulker itself while injecting the NBT data of the NBT storage into the shulker which creates the item

**Comment by SirEndii** [comment]
> You should probably not listen to t8rt0t by the way. He doesn't want us (the admins of that server) knowing how the bug exactly works.

Yes, I take this with a grain of salt

**Comment by Einhornyordle** [comment]
It must either be something on the pickaxe (an enchantment maybe) or some other mod that modifies the block breaking.. Also, about the book, the screenshots only show page 2 and 3, what's up with page 1? Is it empty? And are you sure it is empty and there are no invisible characters hidden in it?

**Comment by AdamProGamingTR** [comment]
> It must either be something on the pickaxe (an enchantment maybe) or some other mod that modifies the block breaking.. Also, about the book, the screenshots only show page 2 and 3, what's up with page 1? Is it empty? And are you sure it is empty and there are no invisible characters hidden in it?

Pickaxe from what i know is a normal pickaxe and as for the book the first page is empty yes. Just checked it myself and there's no invisible characters.

**Comment by Einhornyordle** [comment]
Would you mind placing the book in a chest and give us the output of `/data get block` with the coordinates of said chest?

**Comment by AdamProGamingTR** [comment]
> Would you mind placing the book in a chest and give us the output of `/data get block` with the coordinates of said chest?

![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/128465594/1696af02-40d3-45f7-9435-895ce63cd03a)

**Comment by SirEdvin** [comment]
Wild guess, but because of apotheosis mentioned, can it be, that it is a small bug inside apotheosis special item spawn system?

**Comment by AdamProGamingTR** [comment]
> Wild guess, but because of apotheosis mentioned, can it be, that it is a small bug inside apotheosis special item spawn system?

Doubt it honestly

**Comment by UnhappyCodings** [comment]
But honestly, there are 2 villagers in the dirt house, together with a lectern and his pickaxe is shiny. There must be an enchantment on it.

**Comment by SirEndii** [comment]
> Pickaxe from what i know is a normal pickaxe and as for the book the first page is empty yes. Just checked it myself and there's no invisible characters.

I can see in the video that the pickaxe is shiny 
![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/67484093/f8e91567-f3bf-4035-bfde-a3cb2bd62f7b)

**Comment by SirEndii** [comment]
But I guess the pickaxe does not exist anymore?

**Comment by AdamProGamingTR** [comment]
> But I guess the pickaxe does not exist anymore?

Sadly no. A different admin acted too fast and just /clear'd them but yes the pickaxe is enchanted I just misworded my sentence but even then theres no enchantments in the pack that could cause this.

**Comment by UnhappyCodings** [comment]
Would you be able to send a zip of the pack or a curseforge profile file to me, would like to do some testing in your pack.

**Comment by AdamProGamingTR** [comment]
> Would you be able to send a zip of the pack or a curseforge profile file to me, would like to do some testing in your pack.

[ReHavoc S2 FIGURA EDITION 0.0.7.zip](https://github.com/IntelligenceModding/AdvancedPeripherals/files/14547757/ReHavoc.S2.FIGURA.EDITION.0.0.7.zip)

**Comment by awesomebossdj7** [comment]
okay so obviously we all know they made the nbt storage think it's a shulker somehow

what I think they did is somehow add shulker box nbt to the nbt storage block, and the nbt reader is just a extra thing so they don't need to type it in all the time

probably pretty obvious too, but I can't really test that theory right now

**Comment by Einhornyordle** [comment]
I tried a few things now but I can't manage to reproduce it. As far as I can see it must either be the script or some cross mod interaction. The latter would make more sense since the player also mentioned that "he can assure you that it's not caused by your mod alone".

If you want to cross out the script part entirely, assuming that he really used a script saved on the pc and didn't just type it into the lua console, you could check the server files for the script. It should be in `world/computercraft/computer/` but you'd have to guess the id, which could be pretty difficult if a lot of people on the server use CC:Tweaked.

**Comment by Einhornyordle** [comment]
If  the pc still exists in the world, you could also just CTRL+Middle Mouse Button it in Creative or just break it in survival and check the tooltip for the id.

**Comment by AdamProGamingTR** [comment]
> If the pc still exists in the world, you could also just CTRL+Middle Mouse Button it in Creative or just break it in survival and check the tooltip for the id.

The PC was destroyed by the Admin I mentioned before I could peek inside sadly.

**Comment by Einhornyordle** [comment]
The files might still be inside the world folder, but as I said, it might be difficult to guess the ID of the pc

**Comment by AdamProGamingTR** [comment]
> The files might still be inside the world folder, but as I said, it might be difficult to guess the ID of the pc

Checked all the PCs in the world folder and found nothing.

**Comment by UnhappyCodings** [comment]
And I guess you dont have any backups by any chance?

**Comment by AdamProGamingTR** [comment]
> And I guess you dont have any backups by any chance?

No backups.

**Comment by zyxkad** [comment]
Then it must be a easy copy-pasta commands, people can compress any Lua code to a single line

**Comment by UnhappyCodings** [comment]
Depends on if the admin/s deleted the code manually or just broke the computer, if second, its a copy paste command

**Comment by AdamProGamingTR** [comment]
> Depends on if the admin/s deleted the code manually or just broke the computer, if second, its a copy paste command

Computer was exploded so yes It's the second one.

**Comment by UnhappyCodings** [comment]
Was the end discovered and entered before this happened?

**Comment by awesomebossdj7** [comment]
yes

**Comment by UnhappyCodings** [comment]
Can you check if he or his friend has the end entered achievement?

**Comment by awesomebossdj7** [comment]
Well they 100% did because another group in the server trapped them in the end

**Comment by awesomebossdj7** [comment]
nevermind we figured it out, he snuck a data pack into the server disguised as recipes for another mod

**Comment by AdamProGamingTR** [comment]
Sorry for taking your guys' time.

**Comment by awesomebossdj7** [comment]
He really replaced the data with stored data

**Comment by UnhappyCodings** [comment]
Could you provide us that datapack?

**Comment by AdamProGamingTR** [comment]
[some_peripherals_recipes (1).zip](https://github.com/IntelligenceModding/AdvancedPeripherals/files/14547909/some_peripherals_recipes.1.zip)


> Could you provide us that datapack?

**Comment by SirEndii** [comment]
Thank you both for your feedback
> Sorry for taking your guys' time.

Don't worry, happens to the best

For the next time, I would recommend to look through a datapack before installing it (;
