### ISSUE TITLE
`maxHealth` parameter is mispelled

### ISSUE THREAD

**Issue by GStefanowich** [Seniorendi/AdvancedPeripherals#588]
### Describe

https://github.com/IntelligenceModding/AdvancedPeripherals/blob/eb35cd20b7238d78c9d1bfc95cfa50cca3aca64b/src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/peripheral/PlayerDetectorPeripheral.java#L262

In the PlayerDetector the `maxHealth` parameter is mispelled as `maxHeatlh`

### Steps to reproduce

```lua
local players = peripheral.wrap("playerDetector_0")
local max = players.getPlayerPos(players.getOnlinePlayers()[1]).maxHeatlh
```

### Multiplayer?

Yes

### Version

1.20.1-0.7.38r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

NeoForge 47.1.101

**Comment by zyxkad** [comment]
That's amazing

**Comment by SirEndii** [comment]
Reopen until release
