### ISSUE TITLE
Crash while looking uses/recipes through JEI

### ISSUE THREAD

**Issue by sugan-reden** [Seniorendi/AdvancedPeripherals#591]
### Describe

Crashed while looking up uses with "U" for an Ars Nouveau wood log with JEI. Was looking through the different recipes/pages when I stumbled upon the "Colony Integrator", at which point the game crashed.

The issue has also been reported in the JEI repo for good measure.

Versions:
MC 1.20.1
Forge 47.2.23
Mods: JEI 15.3.0.4; Advanced Peripherals 0.7.39r

P.S. Just a wild guess but could it potentially be related to this issue #438?
I'm saying this because of this line 'getRegistryName() returned null for: 1 air BlockItem(advancedperipherals:colony_integrator)'.
Also, I recently updated all the Minecolonies mods to the latest release version that just came out. Not sure if that's of relevance.

P.P.S. The "Version" section down below seems wrong (maybe it's just me), but I can't seem to find the version I was currently on. It says 0.7.38r is the latest for 1.20.1, maybe it needs an update?

Cheers, keep up the good work!

### Steps to reproduce

1. Open Inventory
2. Press U while hovering over wood log.
3. Look through recipes until you find the Colony Integrator
4. Crash

### Multiplayer?

No

### Version

1.20.1-0.7.38r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Minecraft 1.20.1; Forge 47.2.23; JEI 15.3.0.4

### Crashlog/log

https://gist.github.com/sugan-reden/ae54deda8ac001a65a5a25fb45d9ca41

**Comment by SirEndii** [comment]
I've now tried to replicate this with the latest AP version, some different JEI and minecolonies versions but without luck
Not sure what the issue was/is, maybe it's the sinytra connector or something else
I will mark this as closed. In case anyone else stumbles across the problem with the latest AP version, feel free to re-open the issue

**Comment by sugan-reden** [comment]
I'm sorry it took me so long to respond! I've been away from Minecraft for a while. 🫠 

> I've now tried to replicate this with the latest AP version, some different JEI and minecolonies versions but without luck
Not sure what the issue was/is, maybe it's the sinytra connector or something else

Still, thanks for the work 👍. It really might have simply been a mod interaction on my side. I don't seem to get this issue anymore.
I'll definitely keep you updated if I find anything else! :)

Cheers 🍺
