### ISSUE TITLE
Mentioned wrong person as release contributor

### ISSUE THREAD

**Issue by zyxkad** [Seniorendi/AdvancedPeripherals#594]
### Describe

The release page has some typo.

### Steps to reproduce

1. Open [1.19.2-0.7.35r](https://github.com/IntelligenceModding/AdvancedPeripherals/releases/tag/1.19.2-0.7.35r) and [1.20.1-0.7.39r](https://github.com/IntelligenceModding/AdvancedPeripherals/releases/tag/1.20.1-0.7.39r)
2. You will see
   ```
   2. [#559] Fixed the creation of empty nbt tags when inserting items into the ME System - @thanks to michele-grifa!
   ```

### Multiplayer?

Yes

### Version

1.20.1-0.7.39r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Chrome/124.0.6367.62

### Screenshots or Videos

https://github.com/IntelligenceModding/AdvancedPeripherals/assets/91082411/f0c8c8d0-4817-4925-aea8-5c90ab901947

**Comment by SirEndii** [comment]
I knew there was something I forgot
