### ISSUE TITLE
RS Bridge: getItem returns the output amount of the pattern when no item is in the storage

### ISSUE THREAD

**Issue by Peekofwar** [Seniorendi/AdvancedPeripherals#598]
### Describe

For some reason, when there are 0 x `mekanism:enriched_tin` for example, the `getItem()` function returns `amount = 1`. The issue seems to only occur when there is a crafting pattern for the item and there are none of the item in the system.

![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/10189526/3c4beda9-9f69-4320-9181-c97fdffca798)
![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/10189526/e9852f9d-ac9b-4e26-99c8-16b11a71ee71)

### Steps to reproduce

1. Add a pattern recipe to the RS system to allow it to craft the item.
2. Lookup the item in the RS system through the Computercraft API.

### Multiplayer?

No

### Version

1.20.1-0.7.39r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Forge 47.2.21

**Comment by zyxkad** [comment]
Not sure if @SirEndii did that on purpose.
I assume not, because the doc did not mention it

**Comment by zyxkad** [comment]
Anyways, I believe that the ME/RS network needs some reforge, may fix that in 0.8

**Comment by SirEndii** [comment]
Nope, not intended 
I thought I already fixed that

**Comment by zyxkad** [comment]
> I thought I already fixed that

I double checked, you fixed the issue for AE, but not RS

**Comment by SirEndii** [comment]
> Anyways, I believe that the ME/RS network needs some reforge, may fix that in 0.8

I already fixed several issues on 0.8

**Comment by zyxkad** [comment]
k I'll check that later

**Comment by zyxkad** [comment]
I see, this is a dup of #577

**Comment by SirEndii** [comment]
But remember, 0.8 is really wip
There is a lot of unfinished stuff which I didn't put in a different branch
For example the "new" system for the ME and RS bridge still needs some attention
