### ISSUE TITLE
Impossible to craft compass turtle

### ISSUE THREAD

**Issue by ARNAUDVictor** [Seniorendi/AdvancedPeripherals#599]
### Describe

Hi ! I see "compass turtle" in JEI but i'm unable to craft it with a turtle and a compass... Is it a bug or something else ? Thanks for your anwser !

Magrets

### Steps to reproduce

Take a turtle, take a compass et try to craft both together or with " turtle.equipLeft()" it says "not a valid upgrade"

### Multiplayer?

No

### Version

1.20.1-0.7.38r

### Minecraft, Forge and maybe other related mods versions

Forge  47.2.21| Minecraft 1.20.1

**Comment by zyxkad** [comment]
Press `F3` + `H`, does your compass contains any NBT? I've heard someone said that NBT will affect

**Comment by ARNAUDVictor** [comment]
Hi, yes it contains NBT, I have attached to this mail a screenshot of the
information.


Thanks for answer !

EDIT : my screenshot don't appear in my anwser... Do you need more information about NBT on this turtle and how I can transfer it ?

**Comment by zyxkad** [comment]
No thanks, but I think this is an issue with CC:T. AP probably cannot do anything about it.

**Comment by zyxkad** [comment]
https://github.com/cc-tweaked/CC-Tweaked/issues/106

**Comment by ARNAUDVictor** [comment]
Thx for your time and you mod have a good day ! I'll follow with SquidDev
now.

**Comment by zyxkad** [comment]
I found that this is hopefully can be fixed, and maybe even more features :)

**Comment by SirEndii** [comment]
Reopen until released
