### ISSUE TITLE
Note block does not trigger allay

### ISSUE THREAD

**Issue by tmvkrpxl0** [Seniorendi/AdvancedPeripherals#603]
### Describe

Playing note on note block by using it as peripheral does not trigger allays.

### Steps to reproduce

1. Place computer
2. Place note block right next to it
3. Summon allay and give it random item to collect
4. Play noteblock

### Multiplayer?

Yes

### Version

1.20.1-0.7.39r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

47.2.30 on Minecraft 1.20.1

**Comment by SirEndii** [comment]
Reopen until released
