### ISSUE TITLE
ME bridge not listing cells in ME Extended Drive

### ISSUE THREAD

**Issue by VOID404** [Seniorendi/AdvancedPeripherals#621]
### Describe

I have advanced computer connected to ME system. ME system has a lot of cells (most in ME Extended drive). 
![2024-05-31_20 51 13](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/9433601/7812f27e-67bd-4d4f-a0a8-b89c25f7b14a)

This program:
```lua
local me = peripheral.find("meBridge")

local cells = me.listCells()

for _, i in ipairs(cells) do
    print(i.item)
end
```
should list all the cells in system. It only lists 3 cells
![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/9433601/d04a64b3-6f34-488a-b706-f6b99713e649)

### Steps to reproduce

1. Connect ME Extended Drive and ME Drive with some cells to ME Bridge
![2024-05-31_21 00 06](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/9433601/a25c990a-086d-4b5f-94fe-89917ca1e902)
2. List cells
![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/9433601/088593d0-9b20-4e48-9b0c-c84d0d956b8b)

Only cells in regular ME Drive are listed

### Multiplayer?

No

### Version

1.20.1-0.7.39r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Forge 47.2.20, Minecraft 1.20.1, ATM9 0.2.59

**Comment by SirEndii** [comment]
Gonna reference #86

**Comment by VOID404** [comment]
[ExtendedAE Curse Forge link](https://www.curseforge.com/minecraft/mc-mods/ex-pattern-provider)
