### ISSUE TITLE
Placed blocks do not retain their custom block name when destroyed

### ISSUE THREAD

**Issue by WiggleWizard** [Seniorendi/AdvancedPeripherals#629]
### Describe

Title says it all. Right now it's not a huge issue in my world because I usually place the blocks then never move them.

It would be SUPER handy if blocks retained their names, especially so in complex system in order to identify them easily without a very involved custom configuration step.

### Steps to reproduce

1) Rename a block from the mod in an anvil and place it down somewhere.
2) Hook up a wired modem and call `getName()` on the block. You'll see the new name.
3) If using Jade (block info mod), the block's new name is never shown, only its original name.
4) Breaking the block reverts it back to its original name.

### Multiplayer?

No

### Version

1.20.1-0.7.39r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Minecraft 1.20.1

**Comment by SirEndii** [comment]
Funny, I never tested that or thought about that

**Comment by WiggleWizard** [comment]
To add to this: `getName()` returns a string that's wrapped with square brackets
