### ISSUE TITLE
Me Bridge given ME Drive lua

### ISSUE THREAD

**Issue by zombiekekshd** [Seniorendi/AdvancedPeripherals#632]
### Describe

The lua won't work because of errors in the lua at lines 42f.

### Steps to reproduce

Start ATM 8
Install the lua on an advanced computer connected to the Bridge and a ME
Run the Lua

### Multiplayer?

Yes

### Version

1.19.2-0.7.35r (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

ATM 8 version 1.1.0

### Screenshots or Videos

![Screenshot 2024-06-08 172947](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/152072801/f2f32637-5cfc-488d-a048-8e79cac7cd3b)

**Comment by dogboy21** [comment]
Could you post a screenshot of your Computer+Bridge setup? It looks like your computer is not connected to the ME Bridge properly

**Comment by zyxkad** [comment]
There is no such method, nor in the document. You have to report to https://github.com/SirEndii/Lua-Projects

**Comment by SirEndii** [comment]
To add something to that
`listDrives` was added in 0.8 and I created that script to test the functionalities a bit and to plan what I want. If you want to use that script, you need to use the dev/0.8 branch
