### ISSUE TITLE
[Issue] Memory Card dosent drop if you break the Inventory Manager  v0.5.1.b

### ISSUE THREAD

**Issue by Kollock5** [Seniorendi/AdvancedPeripherals#64]
**Describe**

Memory Card dosent drop if you break the Inventory Manager  

**Reproduce**

on a Multiplayer Server

1.place inventory manager
2.bound memory card to yourself
3.place it inside the inventory manager
4.break the inventory manger 

**Versions:**

- Forge version: 1.16.5-36.1.2
- AdvancedPeripherals version: 0.5.1.b

**Crashlog/log (Use https://paste.gg or https://pastebin.com to upload your crashlog/log)**

**Comment by Wojbie** [comment]
Should this logic be even fixed? I mean making it so memory cards are not removable from inventory managers would make it more secure? Make it harder for someone to steal your inventory access and everything you carry if they are malevolent.

**Comment by Seniorendi** [comment]
> Should this logic be even fixed? I mean making it so memory cards are not removable from inventory managers would make it more secure? Make it harder for someone to steal your inventory access and everything you carry if they are malevolent.
You're right. I will add a feature to remove your name from every memory card.

**Comment by Seniorendi** [comment]
Fixed the issue with the contents in 0.5.2b.
>  I will add a feature to remove your name from every memory card.

I will add that in the near future.
