### ISSUE TITLE
Peripheral throws NullPointerException when invoking getName method

### ISSUE THREAD

**Issue by wolfieboy09** [Seniorendi/AdvancedPeripherals#640]
### Describe

![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/105564186/b15b6931-2787-4a41-ae2b-e718aa3ad428)

### Steps to reproduce

In a computer, do
```
ed = peripheral.wrap("THE SIDE ITS ON, DOES NOT MATTER")
ed.getName() -- fails
```

### Multiplayer?

No - Global thing with getName

### Version

1.20.1-0.7.40r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Forge 47.3.5 Minecraft 1.20.1

**Comment by wolfieboy09** [comment]
![image](https://github.com/IntelligenceModding/AdvancedPeripherals/assets/105564186/1d279838-03e5-4fba-aaa9-079ba3683966)
So how about it just returns its default name?

**Comment by SirEndii** [comment]
>  So how about it just returns its default name?

Well, that's the bug

**Comment by zyxkad** [comment]
reopen until released
