### ISSUE TITLE
Player Detector: `getPlayerPos` result has typo: `maxHeatlh`

### ISSUE THREAD

**Issue by cyberbit** [Seniorendi/AdvancedPeripherals#647]
### Describe

Seems to be a typo in the return value from `getPlayerPos()`: `maxHealth` in docs is `maxHeatlh` in-game. Apologies in advance.

> Side FYI, the screenshot/video field in the issue template doesn't accept rich text attachments so I have to put it in the description and move it once posted.

### Steps to reproduce

1. Place Player Detector next to computer
2. `lua` -> `peripheral.find('playerDetector').getPlayerPos('gamer')`
3. Review result

### Multiplayer?

No

### Version

1.19.2-0.7.36r (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

Forge 43.4.2 Minecraft 1.19.2

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/2b450199-9db6-4130-b63d-51145d7b058f)

**Comment by zyxkad** [comment]
Dup
- #588
