### ISSUE TITLE
Minecolonies Support for Latest update

### ISSUE THREAD

**Issue by Ashley123477** [Seniorendi/AdvancedPeripherals#652]
### Describe

The latest update of minecolonies minecolonies-1.1.637-1.20.1-beta.jar is not compatible with latest Advanced Peripherals.

### Steps to reproduce

Install both mods
Forge Error

### Multiplayer?

Yes

### Version

1.20.1-0.7.40r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

47.3.0 1.20.1

**Comment by zyxkad** [comment]
See ldtteam/minecolonies#10138
