### ISSUE TITLE
crash version on mc 1.20.1 forge

### ISSUE THREAD

**Issue by gilnett** [Seniorendi/AdvancedPeripherals#653]
### Describe

The mod says that I need to have a version after 1.20.1-1.1.472-BETA or later. So, I installed an older version than that, but it still tells me to use a more recent version.

![image](https://github.com/user-attachments/assets/bf99868d-1e89-4559-92a2-cedf90c0e7ad)

### Steps to reproduce

1. install minecraft farge 1.20.1 
2. add minecolonies and advanced peripherals

### Multiplayer?

No

### Version

1.20.1-0.7.40r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

forge 47.2.20

**Comment by zyxkad** [comment]
dup #652
