### ISSUE TITLE
Environment Detector on turtle bug

### ISSUE THREAD

**Issue by Kevin125566** [Seniorendi/AdvancedPeripherals#655]
### Describe

Calling environmentDetector.scanEntities(5) on a turtle returns nil the second time

### Steps to reproduce

1. Place a turtle with an environment detector in it down
2. Call the scanEntities(range) method twice
3. Second return value is nil

### Multiplayer?

Yes

### Version

1.20.1-0.7.40r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Forge 47.3.0 Minecraft 1.20.1

### Screenshots or Videos

![Screenshot 2024-08-29 060703](https://github.com/user-attachments/assets/0895adc5-c610-4537-b8f6-6c5022426e7e) ![Screenshot 2024-08-29 060831](https://github.com/user-attachments/assets/4f5a49d2-6062-489b-890f-5386ae8f7977)

**Comment by zyxkad** [comment]
This is because scan and other operations have cooldown.
If you do
```lua
entities, err = detector.scanEntities(5)
if not entities then
  printError(err)
end
```
It will show you the error.

You also can check the cooldown by invoking `getOperationCooldown`
