### ISSUE TITLE
Crash when using mod

### ISSUE THREAD

**Issue by TanCY1** [Seniorendi/AdvancedPeripherals#657]
### Describe

[hs_err_pid4388.log](https://github.com/user-attachments/files/16922168/hs_err_pid4388.log)

### Steps to reproduce

Use the mod

### Multiplayer?

No

### Version

1.20.1-0.7.40r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Neoforge 47.1.106

**Comment by SirEndii** [comment]
There is nothing related to AP in that bug report
Try to use AP alone

I am unable to reproduce your issue

**Comment by TanCY1** [comment]
Found out that it was Memory Leak Fix that was causing the crash
