### ISSUE TITLE
[Issue]Redstone integrator does not notify neighbors

### ISSUE THREAD

**Issue by Seniorendi** [Seniorendi/AdvancedPeripherals#66]
Before I forget it..
The redstone integrator does not update the redstone wire which they turn off.

Version 0.5.3b
Forge 36.1.13

**Comment by Seniorendi** [comment]
Fixed in 0.5.4b

**Comment by Peekofwar** [comment]
I've noticed it's not working for redstone repeaters; repeaters are not updated.

**Comment by Seniorendi** [comment]
Fixed in 0.6.2b
