### ISSUE TITLE
[Feature] Add an ingredient table for listCraftableItems() method (RS/ME Bridge)

### ISSUE THREAD

**Issue by iammael** [Seniorendi/AdvancedPeripherals#67]
**Describe your feature idea**

When using the listCraftableItems() method from bridges, it'd be great for debugging purposes to have access to a table giving us the ingredients used to make a pattern.

**Describe alternatives you've considered if you've any**

None.

**Additional context**

Searched for a good 2 hours last night for a pattern with a bugged item on it, would have been 30 seconds if such a table would have been provided.

Current return value for reference:
![listCraftableItems](https://user-images.githubusercontent.com/7931135/117323645-5dab5d00-ae8f-11eb-9aa0-9e29d3ec5836.png)

**Comment by Seniorendi** [comment]
Fixed in 0.6r
