### ISSUE TITLE
[Issue] RS Bridge breaks autocrafting

### ISSUE THREAD

**Issue by iammael** [Seniorendi/AdvancedPeripherals#68]
**Describe**

Calling method listCraftableItems() from the RS Bridge breaks autocrafting (see associated video).

**Reproduce**

1. Call listCraftableItems()
2. Ask for any autocraft from the RS system

**Screenshots/Videos**

https://user-images.githubusercontent.com/7931135/117328081-977e6280-ae93-11eb-8fdb-6e47ee8eab62.mp4

Code used:
```
rs = peripheral.find("rsBridge")

rs.listCraftableItems()
```

**Versions:**

- Forge version: 36.1.2
- AdvancedPeripherals version: 0.5.3b

**Notes:**

Not tested with ME Bridge.

**Comment by Seniorendi** [comment]
Fixed in 0.5.4b
