### ISSUE TITLE
[Issue] rsBridge.getItem({}) with 'nbt' field doesn't work

### ISSUE THREAD

**Issue by XenProject** [Seniorendi/AdvancedPeripherals#70]
**Describe**

getItem() returns wrong written book

replace 'md5Hash' value with value from `/advancedperipherals getHashItem`

**Reproduce**

1. Connect RS Bridge to CC, RS and chest
2. Create 2 different written books and add them to RS network
3. Run program

test.lua
```lua
local rb = peripheral.find('rsBridge');
local md5Hash = "801bfe99b388407f956b8e157d1c0e37";
local chest = peripheral.find('minecraft:chest')

local function debugTable(table)
    textutils.pagedPrint(textutils.serialise(table));
end

local itemTable = { name="minecraft:written_book", nbt=md5Hash, count = 1 };

debugTable(rb.getItem(itemTable));

rb.exportItemToChest(itemTable, peripheral.getName(chest));
```

**Versions:**

- Forge version: 36.1.13
- AdvancedPeripherals version: 0.5b
- Refined Storage version: 1.9.12

**Comment by Seniorendi** [comment]
Fixed in 0.6r
