### ISSUE TITLE
[Feature] Environment Detector - Mekanism Radiation

### ISSUE THREAD

**Issue by Peekofwar** [Seniorendi/AdvancedPeripherals#71]
Something that I wish I could do, is detect radiation from Mekanism. Mekanism itself does not have any redstone or block-based radiation detection equipment. This would be useful for warning people of radiation at a location.

**Comment by Seniorendi** [comment]
Sounds like a good feature

**Comment by Seniorendi** [comment]
Added in 0.6.2b
