### ISSUE TITLE
[Issue] v0.6r - Fission Reactor Adapter Incorrect Methods

### ISSUE THREAD

**Issue by Peekofwar** [Seniorendi/AdvancedPeripherals#72]
I hooked up my Mekanism fission reactor only to notice that it's showing the wrong methods. For example, I'm not even seeing `activate()` or `scram()` functions.

![image](https://user-images.githubusercontent.com/10189526/119065015-7f2d3e00-b991-11eb-9f83-228b65fe6b9f.png)

**Reproduce**

1. Network a fission reactor into a terminal
2. Open the terminal Lua prompt
3. Enter `perifs = peripheral.getNames()` to get a table of the available peripherals
4. Enter `perifs` to display the table... The fission reactor should be on slot 2 if nothing else is connected. If it doesn't show up, ensure that the modem on the fission reactor is activated and repeat step 3.
5. Enter `peripheral.getMethods(perifs[2])` (replacing `2` with the correct slot number if applicable)

...

**Screenshots/Videos**

**Versions:**

- Forge: 36.1.0
- Advanced Peripherals: 0.6r
- Mekanism: 10.0.21.448
- Mekanism Generators: 10.0.21.448

**Comment by Seniorendi** [comment]
https://docs.srendi.de/peripheralproxy/getstarted/#how-does-it-work
I explain here how the system works. You need to connect the computer with the peripheral proxy. And the peripheral proxy needs to be facing the logic adapter

**Comment by Peekofwar** [comment]
> https://docs.srendi.de/peripheralproxy/getstarted/#how-does-it-work
> I explain here how the system works. You need to connect the computer with the peripheral proxy. And the peripheral proxy needs to be facing the logic adapter

Ah, I didn't see it mentioned on the Fission reactor integration page

**Comment by Seniorendi** [comment]
Yeah, it works the same for every integration in advanced peripherals.

**Comment by Peekofwar** [comment]
> Yeah, it works the same for every integration in advanced peripherals.

Wait, how do I craft it? JEI isn't showing a recipe, and I don't see one on the WIKI.

**Comment by Seniorendi** [comment]
Ouch. Forgot the recipe... If you want, you can give you the block via creative. I will add a recipe tomorrow.

**Comment by Peekofwar** [comment]
> Ouch. Forgot the recipe... If you want, you can give you the block via creative. I will add a recipe tomorrow.

I might try and make a datapack in the meantime...
