### ISSUE TITLE
[Issue] Redstone Integrator lacks description when pressing ctrl

### ISSUE THREAD

**Issue by Lupus590** [Seniorendi/AdvancedPeripherals#73]
**Describe**

Redstone Integrator lacks description when pressing ctrl

**Reproduce**

1. look up item in jei
2. hover over and press ctrl

**Screenshots/Videos**

![image](https://user-images.githubusercontent.com/9790321/119170082-aef44880-ba5a-11eb-9d59-9e49407919bb.png)

**Versions:**

- Forge version: 36.1.0
- AdvancedPeripherals version: 0.6r

**Crashlog/log (Use https://paste.gg or https://pastebin.com to upload your crashlog/log)**
https://gist.github.com/Lupus590/1aff09cc86b72d99f9fc96cd7c4fc83a

**Comment by Seniorendi** [comment]
Fixed in 0.6.1b
