### ISSUE TITLE
[Issue] No zombie computer scientist texture

### ISSUE THREAD

**Issue by Lupus590** [Seniorendi/AdvancedPeripherals#74]
**Describe**
Found this in my log when reporting #73 

```
[17:34:15] [Render thread/WARN] [minecraft/TextureManager]: Failed to load texture: advancedperipherals:textures/entity/zombie_villager/profession/computer_scientist.png
```

**Reproduce**

1. lookup a villager trade in JEI with [Just Enough Resources](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)? I'm not really sure

**Versions:**

- Forge version: 36.1.0
- AdvancedPeripherals version: 0.6r

**Crashlog/log (Use https://paste.gg or https://pastebin.com to upload your crashlog/log)**
https://gist.github.com/Lupus590/1aff09cc86b72d99f9fc96cd7c4fc83a

**Comment by Seniorendi** [comment]
Fixed in 0.6.1b
