### ISSUE TITLE
[Issue] Just Enough Resources finds the villager trade for ME brdge when AE is not installed

### ISSUE THREAD

**Issue by Lupus590** [Seniorendi/AdvancedPeripherals#75]
**Describe**

Assuming that the RS bridge has one too I would assume that the ME one should also be removed when AE is not installed.
(I have neither installed)

**Reproduce**

1. In an environment without AE and RS, look up the bridge recipes in JEI with [Just Enough Resources](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
2. note that the ME bridge has a villager trade 'recipe' but the RS one doesn't

...

**Screenshots/Videos**

![image](https://user-images.githubusercontent.com/9790321/119171106-0941d900-ba5c-11eb-9dbd-adcbf6ac11cc.png)

**Versions:**

- Forge version: 36.1.0
- AdvancedPeripherals version: 0.6r

**Crashlog/log (Use https://paste.gg or https://pastebin.com to upload your crashlog/log)**
https://gist.github.com/Lupus590/1aff09cc86b72d99f9fc96cd7c4fc83a

**Comment by Seniorendi** [comment]
![image](https://user-images.githubusercontent.com/67484093/119171938-8cb3f800-ba65-11eb-9f47-f62ee8c73574.png)
Could you send me the full text there? I want to add that to the language files.

**Comment by Lupus590** [comment]
![image](https://user-images.githubusercontent.com/9790321/119172099-62f6d300-ba5d-11eb-8568-4a0397f12fe8.png)
`entity.minecraft.villager.advancedperipherals:computer_scientist`

**Comment by Seniorendi** [comment]
Fixed in 0.6.1b
