### ISSUE TITLE
[Feature] Normal Noteblock Intergration

### ISSUE THREAD

**Issue by Dibucci** [Seniorendi/AdvancedPeripherals#76]
simaler to the 1.7.10 OpenPeripherals I was wondering if you could make it so that the computers for CCtweeked will work with the Note blocks that are part of the base game. yes we have speaker blocks but i would love to use actual note blocks to use a program that i used in an older version and see if i can get the thing to work in 1.16.5. I would really apreciate this since OpenPeripherals most likely wont be getting updated to this version

**Comment by Seniorendi** [comment]
Mh, because our integration system is made for tile entities(A noteblock is not a tile entity), I will for now clear the milestone until I have the time to improve our system.

**Comment by SirEndii** [comment]
Done, will be added in 0.7.4

**Comment by SirEndii** [comment]
Added in 0.7.4r
