### ISSUE TITLE
[Issue] Calling rsBridge.listItems() while someone is in the an rs grid causes the grid to freeze

### ISSUE THREAD

**Issue by NumbuhFour** [Seniorendi/AdvancedPeripherals#79]
**Describe**

If a script calls listItems on a rsBridge while someone is in an access grid for refined storage (I was using a crafting grid) the grid freezes and is unable to have items pulled out.
Auto-recipies from JEI still work, I just can't manually pull any items out.

**Reproduce**

1. Make a computer and rsBridge
2. Place them such that the computer accesses the rsBridge and the rsBridge access some Refined Storage network
3. Ensure that the RefinedStorage network has some drive, some contents, and a grid for access
4. Enter the computer and enter lua
5. Enter the following code:
```
rb = peripherial.find('rsBridge')
while true do rb.listItems() sleep(3) end
```
6. Run the code and then exit the computer
7. Go into rs access grid
8. Observe that you can click on items to grab them from the rs system and click again to put them back
9. After 3 seconds, try to click on an item in the rs system again

Expected: I should not be interrupted by the script and still be able to grab items from the rs system
Result: I cannot grab items from the rs system after listItems is called

**Versions:**

- Forge version: 36.1.16
- AdvancedPeripherals version: 0.5.4b
- Refined Storage: 1.9.12
- Refined Storage Addons: 0.7.2

**Comment by Seniorendi** [comment]
Yea, we already fixed that in version 0.6b. I recommend to update the mod.
