### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by NillerMedDild** [Seniorendi/AdvancedPeripherals#81]
**Describe**

Crash on server startup.

**Reproduce**

1. Make a server with AP
2. Try to start it
3. Crash

**Versions:**

- Forge version: 1.16.5-36.1.16
- AdvancedPeripherals version: 0.6.2.1b

**Crashlog/log (Use https://paste.gg or https://pastebin.com to upload your crashlog/log)**
https://gist.github.com/NillerMedDild/1ab78d7967815f3e032d1d27f9c66148

**Comment by Seniorendi** [comment]
[advancedperipherals-0.6.2.1b.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/6541504/advancedperipherals-0.6.2.1b.zip)
Hey, could you test it with this version?

**Comment by NillerMedDild** [comment]
That works 👍

**Comment by NillerMedDild** [comment]
... The client crashes when connecting though. New crash: https://gist.github.com/NillerMedDild/abaeac40d9bb996cb0ae9d2d1e9e9583

**Comment by NillerMedDild** [comment]
This is in a newly generated server by the way, no turtles or anything present.

**Comment by Seniorendi** [comment]
[advancedperipherals-0.6.2.1b.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/6542278/advancedperipherals-0.6.2.1b.zip)
Hey, could you try if this version fixes the issue? Unzip the file before using it.

**Comment by NillerMedDild** [comment]
That fixes the crash-on-join, I'd say it's ready for release 😄

**Comment by Seniorendi** [comment]
Yea, I'll release it tomorrow, I need to fix another issue.
Thank you for the report 👍🏻

**Comment by NillerMedDild** [comment]
Sounds good! No rush from my side, I'm only using the latest version in dev.
