### ISSUE TITLE
Chat Box peripheral unlinking from computer

### ISSUE THREAD

**Issue by Alexsteele4121** [Seniorendi/AdvancedPeripherals#83]
No matter where I am in the overworld, the chat box works just fine. But if I enter the nether and type the trigger word in chat the computer stops receiving commands from the chat box, the only events I'm catching are the 1st party events. Even after I get back to the overworld, I have to remove the chat box and replace it before it will start working again. I am using the mod 'Immersive Portals' and the 'Chunk Loaders' mod to keep the computers active. The Chat Box only seems to freeze if I type the trigger word in the nether. If I am just going to the nether and back without using chat, the computer continues to receiving the events just fine.

1. I run the startup program that takes advantage of the chat box and it works perfectly.
2. I enter the nether, via the 'Immersive Portals' mod (Idk if it's relevant), and type a trigger word in chat with no response.
3. The computer stops receiving command from the chat box entirely.
4. I have to break and replace the chat box to start pulling events from it again.

- MC version: 1.16.5
- Forge version: 36.1.16
- AdvancedPeripherals version: 0.6.2.1b

No big deal at all, just a heads up. loving the mod.

**Comment by Seniorendi** [comment]
Hey, could you use the command `/advancedperipherals debug` before you enter the nether and when you exit the nether and send the outputs here.

**Comment by Alexsteele4121** [comment]
Before I enter the nether I received: [[BlockPos{x=-325, y=73, z=-140}]]
Afterwards: [[]]

That's if I say the trigger word while in the nether

Otherwise I received [[BlockPos{x=-325, y=73, z=-140}]] both times.

**Comment by Seniorendi** [comment]
[advancedperipherals-0.6.3b.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/6554335/advancedperipherals-0.6.3b.zip)
Hey, could you try it with this version? Unzip the file before you use it.

**Comment by Seniorendi** [comment]
Fixed in 0.6.4b

**Comment by Alexsteele4121** [comment]
Works perfectly, thank you!
