### ISSUE TITLE
[Issue] getPlayerPos returns Nil if the Player Detector and Player have a negative x and or z values. But only if the Player has a lower value than the Detector.

### ISSUE THREAD

**Issue by henkeeman** [Seniorendi/AdvancedPeripherals#95]
**Description**

If the Player and the Player Detector both have a negative z or x value but the player has a lesser value the Player Detectors getPlayerPos() returns nil.

If the Player has a negative x or z value but the Player Detector has a positive x and z value it seems to work fine.

**Example:**
The Player Detector is located on the -100, 63, 40 and the player is located on -101, 63, 40 getPlayerPos() returns nil.
Same thing with the z-axis if the Players z value is lower than the Player Detector.

**Steps to reproduce the behavior:**

1. Place down computer and Player Detector on a negative x or and z value.
2. Position yourself so that you have a lower x and or z value than the Player Detector.
3. Wrap the Player Detector and input the getPlayerPos("Username") function 

**Screenshots**
Lower cords : ![getPlayerPosLowerCords](https://user-images.githubusercontent.com/55483865/120925875-e7428a80-c6da-11eb-8db0-a9951cfb5f40.png)

Same cords : ![getPlayerPosSameCords](https://user-images.githubusercontent.com/55483865/120925895-f88b9700-c6da-11eb-90c6-de906ce37bde.png)

**Versions:**

- Forge version: 36.1.24 - MC - 1.16.5
- AdvancedPeripherals version: 0.6.5b

**Comment by Seniorendi** [comment]
[advancedperipherals-0.6.5b.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/6604651/advancedperipherals-0.6.5b.zip)
Hey, could you try it with this version?
Unzip the file before using

**Comment by henkeeman** [comment]
It does not seem to be working at all anymore. The getPlayerPos() just returns nil now, even with positive coordinates.

**Comment by Seniorendi** [comment]
[advancedperipherals-0.6.6b.zip](https://github.com/Seniorendi/AdvancedPeripherals/files/6611458/advancedperipherals-0.6.6b.zip)
Hey, this version should work. Could you try it?
Unzip the file before using it

**Comment by henkeeman** [comment]
It seems to be working great now! Thank you very much :D

**Comment by Seniorendi** [comment]
Fixed in 0.6.6b
